/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewItemFromReceiptDto } from './NewItemFromReceiptDto';
import {
    NewItemFromReceiptDtoFromJSON,
    NewItemFromReceiptDtoFromJSONTyped,
    NewItemFromReceiptDtoToJSON,
    NewItemFromReceiptDtoToJSONTyped,
} from './NewItemFromReceiptDto';

/**
 * 
 * @export
 * @interface AcceptExtractionLineDto
 */
export interface AcceptExtractionLineDto {
    /**
     * Quantity received, in the item's base unit — editable from what was extracted
     */
    quantity: number;
    /**
     * Unit price — editable from what was extracted. Can be left unset and filled in later, but must be set before the receipt can be confirmed.
     */
    unitPrice?: number;
    /**
     * An existing item, belonging to the current tenant. Mutually exclusive with createNewItem.
     */
    itemId?: string;
    /**
     * Set to true, with newItem populated, to create a new item for this line. Mutually exclusive with itemId.
     */
    createNewItem?: boolean;
    /**
     * 
     */
    newItem?: NewItemFromReceiptDto;
}

/**
 * Check if a given object implements the AcceptExtractionLineDto interface.
 */
export function instanceOfAcceptExtractionLineDto(value: object): value is AcceptExtractionLineDto {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function AcceptExtractionLineDtoFromJSON(json: any): AcceptExtractionLineDto {
    return AcceptExtractionLineDtoFromJSONTyped(json, false);
}

export function AcceptExtractionLineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptExtractionLineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'createNewItem': json['createNewItem'] == null ? undefined : json['createNewItem'],
        'newItem': json['newItem'] == null ? undefined : NewItemFromReceiptDtoFromJSON(json['newItem']),
    };
}

export function AcceptExtractionLineDtoToJSON(json: any): AcceptExtractionLineDto {
    return AcceptExtractionLineDtoToJSONTyped(json, false);
}

export function AcceptExtractionLineDtoToJSONTyped(value?: AcceptExtractionLineDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
        'itemId': value['itemId'],
        'createNewItem': value['createNewItem'],
        'newItem': NewItemFromReceiptDtoToJSON(value['newItem']),
    };
}

