/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewItemFromRecipeScanDto } from './NewItemFromRecipeScanDto';
import {
    NewItemFromRecipeScanDtoFromJSON,
    NewItemFromRecipeScanDtoFromJSONTyped,
    NewItemFromRecipeScanDtoToJSON,
    NewItemFromRecipeScanDtoToJSONTyped,
} from './NewItemFromRecipeScanDto';

/**
 * 
 * @export
 * @interface AcceptRecipeExtractionLineDto
 */
export interface AcceptRecipeExtractionLineDto {
    /**
     * Net quantity to use for this ingredient — in the item's own base unit for an itemId line, or in the referenced recipe's own yield unit for a recipeId (subrecipe) line, same semantics as CreateRecipeIngredientDto.quantityNet. Editable from what was extracted (rawQuantity/rawUnit are unvalidated AI text, never used directly).
     */
    quantityNet: number;
    /**
     * Expected waste percentage (0-99.99), same semantics as CreateRecipeIngredientDto.wastePct. Defaults to 0 if omitted.
     */
    wastePct?: number;
    /**
     * An existing item, belonging to the current tenant. Mutually exclusive with recipeId and createNewItem.
     */
    itemId?: string;
    /**
     * An existing recipe, belonging to the current tenant, to use as a subrecipe ingredient (this scanned ingredient is really a reference to one of your own other recipes). Mutually exclusive with itemId and createNewItem.
     */
    recipeId?: string;
    /**
     * Set to true, with newItem populated, to create a new catalog item for this line. Mutually exclusive with itemId/recipeId.
     */
    createNewItem?: boolean;
    /**
     * 
     */
    newItem?: NewItemFromRecipeScanDto;
}

/**
 * Check if a given object implements the AcceptRecipeExtractionLineDto interface.
 */
export function instanceOfAcceptRecipeExtractionLineDto(value: object): value is AcceptRecipeExtractionLineDto {
    if (!('quantityNet' in value) || value['quantityNet'] === undefined) return false;
    return true;
}

export function AcceptRecipeExtractionLineDtoFromJSON(json: any): AcceptRecipeExtractionLineDto {
    return AcceptRecipeExtractionLineDtoFromJSONTyped(json, false);
}

export function AcceptRecipeExtractionLineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptRecipeExtractionLineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'quantityNet': json['quantityNet'],
        'wastePct': json['wastePct'] == null ? undefined : json['wastePct'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'recipeId': json['recipeId'] == null ? undefined : json['recipeId'],
        'createNewItem': json['createNewItem'] == null ? undefined : json['createNewItem'],
        'newItem': json['newItem'] == null ? undefined : NewItemFromRecipeScanDtoFromJSON(json['newItem']),
    };
}

export function AcceptRecipeExtractionLineDtoToJSON(json: any): AcceptRecipeExtractionLineDto {
    return AcceptRecipeExtractionLineDtoToJSONTyped(json, false);
}

export function AcceptRecipeExtractionLineDtoToJSONTyped(value?: AcceptRecipeExtractionLineDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantityNet': value['quantityNet'],
        'wastePct': value['wastePct'],
        'itemId': value['itemId'],
        'recipeId': value['recipeId'],
        'createNewItem': value['createNewItem'],
        'newItem': NewItemFromRecipeScanDtoToJSON(value['newItem']),
    };
}

