/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaptureWasteDto
 */
export interface CaptureWasteDto {
    /**
     * 
     */
    sourceType: CaptureWasteDtoSourceTypeEnum;
    /**
     * ID of an existing location, belonging to the current tenant
     */
    locationId: string;
    /**
     * Already-transcribed text (voice-to-text or OCR) — kept for traceability and used for a basic name match against the tenant's items.
     */
    rawText: string;
    /**
     * The upstream transcription/OCR's own confidence (0-100). Below 80, or when no item could be matched, or when quantity is unknown, this record is forced into REVIEW regardless of this value.
     */
    confidence: number;
    /**
     * Quantity, if the upstream extraction produced one. Omit if unknown — the record is forced into REVIEW for a human to fill it in.
     */
    quantity?: number;
    /**
     * Omit if unknown — defaults to 'Otro'.
     */
    reason?: CaptureWasteDtoReasonEnum;
    /**
     * 
     */
    notes?: string;
}


/**
 * @export
 */
export const CaptureWasteDtoSourceTypeEnum = {
    Manual: 'manual',
    Voice: 'voice',
    Photo: 'photo',
} as const;
export type CaptureWasteDtoSourceTypeEnum = typeof CaptureWasteDtoSourceTypeEnum[keyof typeof CaptureWasteDtoSourceTypeEnum];

/**
 * @export
 */
export const CaptureWasteDtoReasonEnum = {
    MalEstado: 'Mal estado',
    Caducado: 'Caducado',
    Rotura: 'Rotura',
    ErrorDeProduccin: 'Error de producción',
    Quemado: 'Quemado',
    SobranteNoReutilizable: 'Sobrante no reutilizable',
    ContaminacinCruzada: 'Contaminación cruzada',
    DevolucinInterna: 'Devolución interna',
    PruebaTest: 'Prueba / test',
    Otro: 'Otro',
} as const;
export type CaptureWasteDtoReasonEnum = typeof CaptureWasteDtoReasonEnum[keyof typeof CaptureWasteDtoReasonEnum];


/**
 * Check if a given object implements the CaptureWasteDto interface.
 */
export function instanceOfCaptureWasteDto(value: object): value is CaptureWasteDto {
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('rawText' in value) || value['rawText'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    return true;
}

export function CaptureWasteDtoFromJSON(json: any): CaptureWasteDto {
    return CaptureWasteDtoFromJSONTyped(json, false);
}

export function CaptureWasteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptureWasteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceType': json['sourceType'],
        'locationId': json['locationId'],
        'rawText': json['rawText'],
        'confidence': json['confidence'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CaptureWasteDtoToJSON(json: any): CaptureWasteDto {
    return CaptureWasteDtoToJSONTyped(json, false);
}

export function CaptureWasteDtoToJSONTyped(value?: CaptureWasteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceType': value['sourceType'],
        'locationId': value['locationId'],
        'rawText': value['rawText'],
        'confidence': value['confidence'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'notes': value['notes'],
    };
}

