/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteRegistrationResponseDto
 */
export interface CompleteRegistrationResponseDto {
    /**
     * ID of the newly created tenant
     */
    tenantId: string;
    /**
     * Always true right now — kept as an explicit field (not a comment the frontend has to remember) because it's easy to get wrong: the JWT used to CALL this endpoint still has tenant_id absent after this returns. custom_access_token_hook only reads user_profiles at TOKEN ISSUANCE time, and this endpoint just created that row — it doesn't retroactively change an already-issued token. The client must obtain a new one (refresh-token grant, or a fresh login) before tenant_id shows up in a JWT claim.
     */
    requiresNewToken: boolean;
}

/**
 * Check if a given object implements the CompleteRegistrationResponseDto interface.
 */
export function instanceOfCompleteRegistrationResponseDto(value: object): value is CompleteRegistrationResponseDto {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('requiresNewToken' in value) || value['requiresNewToken'] === undefined) return false;
    return true;
}

export function CompleteRegistrationResponseDtoFromJSON(json: any): CompleteRegistrationResponseDto {
    return CompleteRegistrationResponseDtoFromJSONTyped(json, false);
}

export function CompleteRegistrationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteRegistrationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenantId'],
        'requiresNewToken': json['requiresNewToken'],
    };
}

export function CompleteRegistrationResponseDtoToJSON(json: any): CompleteRegistrationResponseDto {
    return CompleteRegistrationResponseDtoToJSONTyped(json, false);
}

export function CompleteRegistrationResponseDtoToJSONTyped(value?: CompleteRegistrationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenantId': value['tenantId'],
        'requiresNewToken': value['requiresNewToken'],
    };
}

