/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteRegistrationDto
 */
export interface CompleteRegistrationDto {
    /**
     * 
     */
    restaurantName: string;
    /**
     * 
     */
    address?: string;
    /**
     * 
     */
    postalCode?: string;
    /**
     * ID of an existing plan (must exist in plans)
     */
    planId: string;
}

/**
 * Check if a given object implements the CompleteRegistrationDto interface.
 */
export function instanceOfCompleteRegistrationDto(value: object): value is CompleteRegistrationDto {
    if (!('restaurantName' in value) || value['restaurantName'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    return true;
}

export function CompleteRegistrationDtoFromJSON(json: any): CompleteRegistrationDto {
    return CompleteRegistrationDtoFromJSONTyped(json, false);
}

export function CompleteRegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteRegistrationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'restaurantName': json['restaurantName'],
        'address': json['address'] == null ? undefined : json['address'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'planId': json['planId'],
    };
}

export function CompleteRegistrationDtoToJSON(json: any): CompleteRegistrationDto {
    return CompleteRegistrationDtoToJSONTyped(json, false);
}

export function CompleteRegistrationDtoToJSONTyped(value?: CompleteRegistrationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'restaurantName': value['restaurantName'],
        'address': value['address'],
        'postalCode': value['postalCode'],
        'planId': value['planId'],
    };
}

