/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmLoginCodeDto
 */
export interface ConfirmLoginCodeDto {
    /**
     * 
     */
    email: string;
    /**
     * The code sent by POST /auth/verify-login-code. Length is not hardcoded to 6 here — GoTrue is the actual source of truth for what a valid code looks like, this is just a sane upper bound.
     */
    code: string;
}

/**
 * Check if a given object implements the ConfirmLoginCodeDto interface.
 */
export function instanceOfConfirmLoginCodeDto(value: object): value is ConfirmLoginCodeDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ConfirmLoginCodeDtoFromJSON(json: any): ConfirmLoginCodeDto {
    return ConfirmLoginCodeDtoFromJSONTyped(json, false);
}

export function ConfirmLoginCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmLoginCodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function ConfirmLoginCodeDtoToJSON(json: any): ConfirmLoginCodeDto {
    return ConfirmLoginCodeDtoToJSONTyped(json, false);
}

export function ConfirmLoginCodeDtoToJSONTyped(value?: ConfirmLoginCodeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

