/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderDto
 */
export interface CreateOrderDto {
    /**
     * ID of an existing location, belonging to the current tenant
     */
    locationId: string;
    /**
     * 
     */
    note?: string;
}

/**
 * Check if a given object implements the CreateOrderDto interface.
 */
export function instanceOfCreateOrderDto(value: object): value is CreateOrderDto {
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    return true;
}

export function CreateOrderDtoFromJSON(json: any): CreateOrderDto {
    return CreateOrderDtoFromJSONTyped(json, false);
}

export function CreateOrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'locationId': json['locationId'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreateOrderDtoToJSON(json: any): CreateOrderDto {
    return CreateOrderDtoToJSONTyped(json, false);
}

export function CreateOrderDtoToJSONTyped(value?: CreateOrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationId': value['locationId'],
        'note': value['note'],
    };
}

