/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStockLotDto
 */
export interface CreateStockLotDto {
    /**
     * ID of an existing item, belonging to the current tenant
     */
    itemId: string;
    /**
     * ID of an existing location, belonging to the current tenant
     */
    locationId: string;
    /**
     * ID of the supplier this lot was received from, if known
     */
    supplierId?: string;
    /**
     * Quantity received, in the item's base unit
     */
    quantityReceived: number;
    /**
     * Cost per base unit for this specific lot
     */
    unitCost: number;
    /**
     * When this lot was received — drives FIFO consumption order (oldest received_at consumed first)
     */
    receivedAt: string;
}

/**
 * Check if a given object implements the CreateStockLotDto interface.
 */
export function instanceOfCreateStockLotDto(value: object): value is CreateStockLotDto {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('quantityReceived' in value) || value['quantityReceived'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    if (!('receivedAt' in value) || value['receivedAt'] === undefined) return false;
    return true;
}

export function CreateStockLotDtoFromJSON(json: any): CreateStockLotDto {
    return CreateStockLotDtoFromJSONTyped(json, false);
}

export function CreateStockLotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStockLotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'locationId': json['locationId'],
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'quantityReceived': json['quantityReceived'],
        'unitCost': json['unitCost'],
        'receivedAt': json['receivedAt'],
    };
}

export function CreateStockLotDtoToJSON(json: any): CreateStockLotDto {
    return CreateStockLotDtoToJSONTyped(json, false);
}

export function CreateStockLotDtoToJSONTyped(value?: CreateStockLotDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'locationId': value['locationId'],
        'supplierId': value['supplierId'],
        'quantityReceived': value['quantityReceived'],
        'unitCost': value['unitCost'],
        'receivedAt': value['receivedAt'],
    };
}

