/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSupplierDto
 */
export interface CreateSupplierDto {
    /**
     * Supplier name
     */
    name: string;
    /**
     * Tax ID / CUIT
     */
    taxId?: string;
    /**
     * Contact phone
     */
    phone?: string;
    /**
     * Contact email
     */
    email?: string;
    /**
     * Address
     */
    address?: string;
}

/**
 * Check if a given object implements the CreateSupplierDto interface.
 */
export function instanceOfCreateSupplierDto(value: object): value is CreateSupplierDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSupplierDtoFromJSON(json: any): CreateSupplierDto {
    return CreateSupplierDtoFromJSONTyped(json, false);
}

export function CreateSupplierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSupplierDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'taxId': json['taxId'] == null ? undefined : json['taxId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function CreateSupplierDtoToJSON(json: any): CreateSupplierDto {
    return CreateSupplierDtoToJSONTyped(json, false);
}

export function CreateSupplierDtoToJSONTyped(value?: CreateSupplierDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'taxId': value['taxId'],
        'phone': value['phone'],
        'email': value['email'],
        'address': value['address'],
    };
}

