/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSupplierItemPriceDto
 */
export interface CreateSupplierItemPriceDto {
    /**
     * ID of an existing supplier to link to this item
     */
    supplierId: string;
    /**
     * Price this supplier charges for this item
     */
    price: number;
    /**
     * Purchase-unit to base-unit conversion factor (e.g. 24 if this supplier sells by the box and the item's base unit is 'unit', with 24 units per box)
     */
    unitConversionFactor?: number;
    /**
     * Marks this as the preferred supplier for the item. Setting true automatically unmarks any other price row for the same item that was previously preferred.
     */
    isPreferred?: boolean;
}

/**
 * Check if a given object implements the CreateSupplierItemPriceDto interface.
 */
export function instanceOfCreateSupplierItemPriceDto(value: object): value is CreateSupplierItemPriceDto {
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function CreateSupplierItemPriceDtoFromJSON(json: any): CreateSupplierItemPriceDto {
    return CreateSupplierItemPriceDtoFromJSONTyped(json, false);
}

export function CreateSupplierItemPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSupplierItemPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierId': json['supplierId'],
        'price': json['price'],
        'unitConversionFactor': json['unitConversionFactor'] == null ? undefined : json['unitConversionFactor'],
        'isPreferred': json['isPreferred'] == null ? undefined : json['isPreferred'],
    };
}

export function CreateSupplierItemPriceDtoToJSON(json: any): CreateSupplierItemPriceDto {
    return CreateSupplierItemPriceDtoToJSONTyped(json, false);
}

export function CreateSupplierItemPriceDtoToJSONTyped(value?: CreateSupplierItemPriceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supplierId': value['supplierId'],
        'price': value['price'],
        'unitConversionFactor': value['unitConversionFactor'],
        'isPreferred': value['isPreferred'],
    };
}

