/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderLineDto
 */
export interface CreateOrderLineDto {
    /**
     * ID of an existing item, belonging to the current tenant
     */
    itemId: string;
    /**
     * ID of an existing supplier, belonging to the current tenant. Optional — a line can be left 'pendiente' with no supplier assigned yet.
     */
    supplierId?: string;
    /**
     * Quantity to order, in the item's base unit
     */
    quantity: number;
}

/**
 * Check if a given object implements the CreateOrderLineDto interface.
 */
export function instanceOfCreateOrderLineDto(value: object): value is CreateOrderLineDto {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CreateOrderLineDtoFromJSON(json: any): CreateOrderLineDto {
    return CreateOrderLineDtoFromJSONTyped(json, false);
}

export function CreateOrderLineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderLineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'quantity': json['quantity'],
    };
}

export function CreateOrderLineDtoToJSON(json: any): CreateOrderLineDto {
    return CreateOrderLineDtoToJSONTyped(json, false);
}

export function CreateOrderLineDtoToJSONTyped(value?: CreateOrderLineDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'supplierId': value['supplierId'],
        'quantity': value['quantity'],
    };
}

