/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReceiptDto
 */
export interface CreateReceiptDto {
    /**
     * ID of an existing location, belonging to the current tenant
     */
    locationId: string;
    /**
     * ID of an existing supplier, if already known
     */
    supplierId?: string;
    /**
     * 
     */
    note?: string;
}

/**
 * Check if a given object implements the CreateReceiptDto interface.
 */
export function instanceOfCreateReceiptDto(value: object): value is CreateReceiptDto {
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    return true;
}

export function CreateReceiptDtoFromJSON(json: any): CreateReceiptDto {
    return CreateReceiptDtoFromJSONTyped(json, false);
}

export function CreateReceiptDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReceiptDto {
    if (json == null) {
        return json;
    }
    return {
        
        'locationId': json['locationId'],
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreateReceiptDtoToJSON(json: any): CreateReceiptDto {
    return CreateReceiptDtoToJSONTyped(json, false);
}

export function CreateReceiptDtoToJSONTyped(value?: CreateReceiptDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationId': value['locationId'],
        'supplierId': value['supplierId'],
        'note': value['note'],
    };
}

