/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWasteDto
 */
export interface CreateWasteDto {
    /**
     * ID of an existing item, belonging to the current tenant
     */
    itemId: string;
    /**
     * ID of an existing location, belonging to the current tenant
     */
    locationId: string;
    /**
     * Quantity wasted, in the item's base unit
     */
    quantity: number;
    /**
     * Must be one of the fixed reason list
     */
    reason: CreateWasteDtoReasonEnum;
    /**
     * 
     */
    notes?: string;
}


/**
 * @export
 */
export const CreateWasteDtoReasonEnum = {
    MalEstado: 'Mal estado',
    Caducado: 'Caducado',
    Rotura: 'Rotura',
    ErrorDeProduccin: 'Error de producción',
    Quemado: 'Quemado',
    SobranteNoReutilizable: 'Sobrante no reutilizable',
    ContaminacinCruzada: 'Contaminación cruzada',
    DevolucinInterna: 'Devolución interna',
    PruebaTest: 'Prueba / test',
    Otro: 'Otro',
} as const;
export type CreateWasteDtoReasonEnum = typeof CreateWasteDtoReasonEnum[keyof typeof CreateWasteDtoReasonEnum];


/**
 * Check if a given object implements the CreateWasteDto interface.
 */
export function instanceOfCreateWasteDto(value: object): value is CreateWasteDto {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function CreateWasteDtoFromJSON(json: any): CreateWasteDto {
    return CreateWasteDtoFromJSONTyped(json, false);
}

export function CreateWasteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWasteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'locationId': json['locationId'],
        'quantity': json['quantity'],
        'reason': json['reason'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CreateWasteDtoToJSON(json: any): CreateWasteDto {
    return CreateWasteDtoToJSONTyped(json, false);
}

export function CreateWasteDtoToJSONTyped(value?: CreateWasteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'locationId': value['locationId'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'notes': value['notes'],
    };
}

