/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductionDto
 */
export interface CreateProductionDto {
    /**
     * Recipe being produced, must belong to the current tenant
     */
    recipeId: string;
    /**
     * Location this production happened at, and whose stock_lots get consumed
     */
    locationId: string;
    /**
     * How many of the recipe's yieldFinalUnit/portions were produced. Ingredient consumption and cost_snapshot both scale by quantityProduced / recipe.yieldPortions.
     */
    quantityProduced: number;
}

/**
 * Check if a given object implements the CreateProductionDto interface.
 */
export function instanceOfCreateProductionDto(value: object): value is CreateProductionDto {
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('quantityProduced' in value) || value['quantityProduced'] === undefined) return false;
    return true;
}

export function CreateProductionDtoFromJSON(json: any): CreateProductionDto {
    return CreateProductionDtoFromJSONTyped(json, false);
}

export function CreateProductionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recipeId': json['recipeId'],
        'locationId': json['locationId'],
        'quantityProduced': json['quantityProduced'],
    };
}

export function CreateProductionDtoToJSON(json: any): CreateProductionDto {
    return CreateProductionDtoToJSONTyped(json, false);
}

export function CreateProductionDtoToJSONTyped(value?: CreateProductionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipeId': value['recipeId'],
        'locationId': value['locationId'],
        'quantityProduced': value['quantityProduced'],
    };
}

