/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLocationDto
 */
export interface CreateLocationDto {
    /**
     * Location name
     */
    name: string;
    /**
     * Address
     */
    address?: string;
}

/**
 * Check if a given object implements the CreateLocationDto interface.
 */
export function instanceOfCreateLocationDto(value: object): value is CreateLocationDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateLocationDtoFromJSON(json: any): CreateLocationDto {
    return CreateLocationDtoFromJSONTyped(json, false);
}

export function CreateLocationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLocationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function CreateLocationDtoToJSON(json: any): CreateLocationDto {
    return CreateLocationDtoToJSONTyped(json, false);
}

export function CreateLocationDtoToJSONTyped(value?: CreateLocationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
    };
}

