/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ItemResponseDto
 */
export interface ItemResponseDto {
    /**
     * Item ID
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    unit: string;
    /**
     * 
     */
    category?: object | null;
    /**
     * 
     */
    minStock?: object | null;
    /**
     * 
     */
    maxStock?: object | null;
    /**
     * 
     */
    wasteDefaultPct?: object | null;
    /**
     * 
     */
    isActive: boolean;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ItemResponseDto interface.
 */
export function instanceOfItemResponseDto(value: object): value is ItemResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ItemResponseDtoFromJSON(json: any): ItemResponseDto {
    return ItemResponseDtoFromJSONTyped(json, false);
}

export function ItemResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'unit': json['unit'],
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'minStock': json['minStock'] === undefined ? undefined : json['minStock'] === null ? null : json['minStock'],
        'maxStock': json['maxStock'] === undefined ? undefined : json['maxStock'] === null ? null : json['maxStock'],
        'wasteDefaultPct': json['wasteDefaultPct'] === undefined ? undefined : json['wasteDefaultPct'] === null ? null : json['wasteDefaultPct'],
        'isActive': json['isActive'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function ItemResponseDtoToJSON(json: any): ItemResponseDto {
    return ItemResponseDtoToJSONTyped(json, false);
}

export function ItemResponseDtoToJSONTyped(value?: ItemResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'unit': value['unit'],
        'category': value['category'],
        'minStock': value['minStock'],
        'maxStock': value['maxStock'],
        'wasteDefaultPct': value['wasteDefaultPct'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

