/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface LocationResponseDto
 */
export interface LocationResponseDto {
    /**
     * Location ID
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    address?: object | null;
    /**
     * 
     */
    isActive: boolean;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the LocationResponseDto interface.
 */
export function instanceOfLocationResponseDto(value: object): value is LocationResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function LocationResponseDtoFromJSON(json: any): LocationResponseDto {
    return LocationResponseDtoFromJSONTyped(json, false);
}

export function LocationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'address': json['address'] === undefined ? undefined : json['address'] === null ? null : json['address'],
        'isActive': json['isActive'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function LocationResponseDtoToJSON(json: any): LocationResponseDto {
    return LocationResponseDtoToJSONTyped(json, false);
}

export function LocationResponseDtoToJSONTyped(value?: LocationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'address': value['address'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

