/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewItemFromReceiptDto
 */
export interface NewItemFromReceiptDto {
    /**
     * Item name
     */
    name: string;
    /**
     * Base unit of measure
     */
    unit: string;
    /**
     * 
     */
    category?: string;
    /**
     * 
     */
    minStock?: number;
    /**
     * 
     */
    maxStock?: number;
    /**
     * 
     */
    wasteDefaultPct?: number;
}

/**
 * Check if a given object implements the NewItemFromReceiptDto interface.
 */
export function instanceOfNewItemFromReceiptDto(value: object): value is NewItemFromReceiptDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function NewItemFromReceiptDtoFromJSON(json: any): NewItemFromReceiptDto {
    return NewItemFromReceiptDtoFromJSONTyped(json, false);
}

export function NewItemFromReceiptDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewItemFromReceiptDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'unit': json['unit'],
        'category': json['category'] == null ? undefined : json['category'],
        'minStock': json['minStock'] == null ? undefined : json['minStock'],
        'maxStock': json['maxStock'] == null ? undefined : json['maxStock'],
        'wasteDefaultPct': json['wasteDefaultPct'] == null ? undefined : json['wasteDefaultPct'],
    };
}

export function NewItemFromReceiptDtoToJSON(json: any): NewItemFromReceiptDto {
    return NewItemFromReceiptDtoToJSONTyped(json, false);
}

export function NewItemFromReceiptDtoToJSONTyped(value?: NewItemFromReceiptDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'unit': value['unit'],
        'category': value['category'],
        'minStock': value['minStock'],
        'maxStock': value['maxStock'],
        'wasteDefaultPct': value['wasteDefaultPct'],
    };
}

