/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderSuggestionResponseDto
 */
export interface OrderSuggestionResponseDto {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    itemName: string;
    /**
     * Sum of stock_lots.quantity_remaining for this item at this location
     */
    currentStock: number;
    /**
     * 
     */
    minStock: number;
    /**
     * 
     */
    maxStock: number;
    /**
     * maxStock - currentStock, per the legacy formula
     */
    suggestedQuantity: number;
}

/**
 * Check if a given object implements the OrderSuggestionResponseDto interface.
 */
export function instanceOfOrderSuggestionResponseDto(value: object): value is OrderSuggestionResponseDto {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('itemName' in value) || value['itemName'] === undefined) return false;
    if (!('currentStock' in value) || value['currentStock'] === undefined) return false;
    if (!('minStock' in value) || value['minStock'] === undefined) return false;
    if (!('maxStock' in value) || value['maxStock'] === undefined) return false;
    if (!('suggestedQuantity' in value) || value['suggestedQuantity'] === undefined) return false;
    return true;
}

export function OrderSuggestionResponseDtoFromJSON(json: any): OrderSuggestionResponseDto {
    return OrderSuggestionResponseDtoFromJSONTyped(json, false);
}

export function OrderSuggestionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSuggestionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'itemName': json['itemName'],
        'currentStock': json['currentStock'],
        'minStock': json['minStock'],
        'maxStock': json['maxStock'],
        'suggestedQuantity': json['suggestedQuantity'],
    };
}

export function OrderSuggestionResponseDtoToJSON(json: any): OrderSuggestionResponseDto {
    return OrderSuggestionResponseDtoToJSONTyped(json, false);
}

export function OrderSuggestionResponseDtoToJSONTyped(value?: OrderSuggestionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'currentStock': value['currentStock'],
        'minStock': value['minStock'],
        'maxStock': value['maxStock'],
        'suggestedQuantity': value['suggestedQuantity'],
    };
}

