/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { OrderLineResponseDto } from './OrderLineResponseDto';
import {
    OrderLineResponseDtoFromJSON,
    OrderLineResponseDtoFromJSONTyped,
    OrderLineResponseDtoToJSON,
    OrderLineResponseDtoToJSONTyped,
} from './OrderLineResponseDto';

/**
 * 
 * @export
 * @interface OrderDetailResponseDto
 */
export interface OrderDetailResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * 
     */
    status: OrderDetailResponseDtoStatusEnum;
    /**
     * user_profiles.id of who created this order
     */
    responsibleUserId?: object | null;
    /**
     * 
     */
    note?: object | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    lines: Array<OrderLineResponseDto>;
}


/**
 * @export
 */
export const OrderDetailResponseDtoStatusEnum = {
    Draft: 'DRAFT',
    Confirmed: 'CONFIRMED',
    Archived: 'ARCHIVED',
} as const;
export type OrderDetailResponseDtoStatusEnum = typeof OrderDetailResponseDtoStatusEnum[keyof typeof OrderDetailResponseDtoStatusEnum];


/**
 * Check if a given object implements the OrderDetailResponseDto interface.
 */
export function instanceOfOrderDetailResponseDto(value: object): value is OrderDetailResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function OrderDetailResponseDtoFromJSON(json: any): OrderDetailResponseDto {
    return OrderDetailResponseDtoFromJSONTyped(json, false);
}

export function OrderDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'locationId': json['locationId'],
        'status': json['status'],
        'responsibleUserId': json['responsibleUserId'] === undefined ? undefined : json['responsibleUserId'] === null ? null : json['responsibleUserId'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'lines': ((json['lines'] as Array<any>).map(OrderLineResponseDtoFromJSON)),
    };
}

export function OrderDetailResponseDtoToJSON(json: any): OrderDetailResponseDto {
    return OrderDetailResponseDtoToJSONTyped(json, false);
}

export function OrderDetailResponseDtoToJSONTyped(value?: OrderDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'locationId': value['locationId'],
        'status': value['status'],
        'responsibleUserId': value['responsibleUserId'],
        'note': value['note'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'lines': ((value['lines'] as Array<any>).map(OrderLineResponseDtoToJSON)),
    };
}

