/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface OrderResponseDto
 */
export interface OrderResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * 
     */
    status: OrderResponseDtoStatusEnum;
    /**
     * user_profiles.id of who created this order
     */
    responsibleUserId?: object | null;
    /**
     * 
     */
    note?: object | null;
    /**
     * 
     */
    createdAt: Date;
}


/**
 * @export
 */
export const OrderResponseDtoStatusEnum = {
    Draft: 'DRAFT',
    Confirmed: 'CONFIRMED',
    Archived: 'ARCHIVED',
} as const;
export type OrderResponseDtoStatusEnum = typeof OrderResponseDtoStatusEnum[keyof typeof OrderResponseDtoStatusEnum];


/**
 * Check if a given object implements the OrderResponseDto interface.
 */
export function instanceOfOrderResponseDto(value: object): value is OrderResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrderResponseDtoFromJSON(json: any): OrderResponseDto {
    return OrderResponseDtoFromJSONTyped(json, false);
}

export function OrderResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'locationId': json['locationId'],
        'status': json['status'],
        'responsibleUserId': json['responsibleUserId'] === undefined ? undefined : json['responsibleUserId'] === null ? null : json['responsibleUserId'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function OrderResponseDtoToJSON(json: any): OrderResponseDto {
    return OrderResponseDtoToJSONTyped(json, false);
}

export function OrderResponseDtoToJSONTyped(value?: OrderResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'locationId': value['locationId'],
        'status': value['status'],
        'responsibleUserId': value['responsibleUserId'],
        'note': value['note'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

