/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface OrderLineResponseDto
 */
export interface OrderLineResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    orderId: string;
    /**
     * 
     */
    itemId: string;
    /**
     * null while this line is 'pendiente' — no supplier chosen yet
     */
    supplierId?: object | null;
    /**
     * 
     */
    quantity: number;
    /**
     * 
     */
    isChecked: boolean;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the OrderLineResponseDto interface.
 */
export function instanceOfOrderLineResponseDto(value: object): value is OrderLineResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('isChecked' in value) || value['isChecked'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrderLineResponseDtoFromJSON(json: any): OrderLineResponseDto {
    return OrderLineResponseDtoFromJSONTyped(json, false);
}

export function OrderLineResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderLineResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'orderId': json['orderId'],
        'itemId': json['itemId'],
        'supplierId': json['supplierId'] === undefined ? undefined : json['supplierId'] === null ? null : json['supplierId'],
        'quantity': json['quantity'],
        'isChecked': json['isChecked'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function OrderLineResponseDtoToJSON(json: any): OrderLineResponseDto {
    return OrderLineResponseDtoToJSONTyped(json, false);
}

export function OrderLineResponseDtoToJSONTyped(value?: OrderLineResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'orderId': value['orderId'],
        'itemId': value['itemId'],
        'supplierId': value['supplierId'],
        'quantity': value['quantity'],
        'isChecked': value['isChecked'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

