/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionResponseDto
 */
export interface ProductionResponseDto {
    /**
     * Production ID
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    recipeId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * 
     */
    quantityProduced: number;
    /**
     * The recipe's costAdjusted at the time of production, scaled by quantityProduced / yieldPortions — frozen permanently, never recalculated.
     */
    costSnapshot: number;
    /**
     * 
     */
    producedAt: Date;
    /**
     * user_profiles.id of who recorded this production
     */
    createdBy?: object | null;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ProductionResponseDto interface.
 */
export function instanceOfProductionResponseDto(value: object): value is ProductionResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('quantityProduced' in value) || value['quantityProduced'] === undefined) return false;
    if (!('costSnapshot' in value) || value['costSnapshot'] === undefined) return false;
    if (!('producedAt' in value) || value['producedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProductionResponseDtoFromJSON(json: any): ProductionResponseDto {
    return ProductionResponseDtoFromJSONTyped(json, false);
}

export function ProductionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'recipeId': json['recipeId'],
        'locationId': json['locationId'],
        'quantityProduced': json['quantityProduced'],
        'costSnapshot': json['costSnapshot'],
        'producedAt': (json['producedAt'] == null ? json['producedAt'] : parseDateTime(json['producedAt'])),
        'createdBy': json['createdBy'] === undefined ? undefined : json['createdBy'] === null ? null : json['createdBy'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function ProductionResponseDtoToJSON(json: any): ProductionResponseDto {
    return ProductionResponseDtoToJSONTyped(json, false);
}

export function ProductionResponseDtoToJSONTyped(value?: ProductionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'recipeId': value['recipeId'],
        'locationId': value['locationId'],
        'quantityProduced': value['quantityProduced'],
        'costSnapshot': value['costSnapshot'],
        'producedAt': value['producedAt'] == null ? value['producedAt'] : serializeDateTime(value['producedAt']),
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

