/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptExtractionLineResponseDto
 */
export interface ReceiptExtractionLineResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    extractionRunId: string;
    /**
     * 
     */
    rawItemName?: object | null;
    /**
     * 
     */
    rawQuantity?: object | null;
    /**
     * 
     */
    rawUnit?: object | null;
    /**
     * 
     */
    rawPrice?: object | null;
    /**
     * Automatic name-match against the tenant's items, if any — informational, the human still picks/confirms via accept
     */
    matchedItemId?: object | null;
    /**
     * Minimum of this line's per-field extraction confidences
     */
    confidence?: object | null;
    /**
     * 
     */
    reviewStatus: ReceiptExtractionLineResponseDtoReviewStatusEnum;
    /**
     * 
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ReceiptExtractionLineResponseDtoReviewStatusEnum = {
    Pending: 'PENDING',
    Accepted: 'ACCEPTED',
    Rejected: 'REJECTED',
} as const;
export type ReceiptExtractionLineResponseDtoReviewStatusEnum = typeof ReceiptExtractionLineResponseDtoReviewStatusEnum[keyof typeof ReceiptExtractionLineResponseDtoReviewStatusEnum];


/**
 * Check if a given object implements the ReceiptExtractionLineResponseDto interface.
 */
export function instanceOfReceiptExtractionLineResponseDto(value: object): value is ReceiptExtractionLineResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('extractionRunId' in value) || value['extractionRunId'] === undefined) return false;
    if (!('reviewStatus' in value) || value['reviewStatus'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReceiptExtractionLineResponseDtoFromJSON(json: any): ReceiptExtractionLineResponseDto {
    return ReceiptExtractionLineResponseDtoFromJSONTyped(json, false);
}

export function ReceiptExtractionLineResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptExtractionLineResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'extractionRunId': json['extractionRunId'],
        'rawItemName': json['rawItemName'] === undefined ? undefined : json['rawItemName'] === null ? null : json['rawItemName'],
        'rawQuantity': json['rawQuantity'] === undefined ? undefined : json['rawQuantity'] === null ? null : json['rawQuantity'],
        'rawUnit': json['rawUnit'] === undefined ? undefined : json['rawUnit'] === null ? null : json['rawUnit'],
        'rawPrice': json['rawPrice'] === undefined ? undefined : json['rawPrice'] === null ? null : json['rawPrice'],
        'matchedItemId': json['matchedItemId'] === undefined ? undefined : json['matchedItemId'] === null ? null : json['matchedItemId'],
        'confidence': json['confidence'] === undefined ? undefined : json['confidence'] === null ? null : json['confidence'],
        'reviewStatus': json['reviewStatus'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function ReceiptExtractionLineResponseDtoToJSON(json: any): ReceiptExtractionLineResponseDto {
    return ReceiptExtractionLineResponseDtoToJSONTyped(json, false);
}

export function ReceiptExtractionLineResponseDtoToJSONTyped(value?: ReceiptExtractionLineResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'extractionRunId': value['extractionRunId'],
        'rawItemName': value['rawItemName'],
        'rawQuantity': value['rawQuantity'],
        'rawUnit': value['rawUnit'],
        'rawPrice': value['rawPrice'],
        'matchedItemId': value['matchedItemId'],
        'confidence': value['confidence'],
        'reviewStatus': value['reviewStatus'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

