/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ReceiptExtractionRunResponseDto } from './ReceiptExtractionRunResponseDto';
import {
    ReceiptExtractionRunResponseDtoFromJSON,
    ReceiptExtractionRunResponseDtoFromJSONTyped,
    ReceiptExtractionRunResponseDtoToJSON,
    ReceiptExtractionRunResponseDtoToJSONTyped,
} from './ReceiptExtractionRunResponseDto';
import type { ReceiptLineResponseDto } from './ReceiptLineResponseDto';
import {
    ReceiptLineResponseDtoFromJSON,
    ReceiptLineResponseDtoFromJSONTyped,
    ReceiptLineResponseDtoToJSON,
    ReceiptLineResponseDtoToJSONTyped,
} from './ReceiptLineResponseDto';

/**
 * 
 * @export
 * @interface ReceiptDetailResponseDto
 */
export interface ReceiptDetailResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * null until resolved — see PATCH /receipts/:id
     */
    supplierId?: object | null;
    /**
     * 
     */
    status: ReceiptDetailResponseDtoStatusEnum;
    /**
     * 
     */
    docNumber?: object | null;
    /**
     * 
     */
    docDate?: object | null;
    /**
     * 
     */
    note?: object | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * Set when confirmed (status -> CONFIRMED)
     */
    validatedAt?: object | null;
    /**
     * 
     */
    lines: Array<ReceiptLineResponseDto>;
    /**
     * null if no extraction has been run yet for this receipt
     */
    latestExtractionRun?: ReceiptExtractionRunResponseDto | null;
}


/**
 * @export
 */
export const ReceiptDetailResponseDtoStatusEnum = {
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    Archived: 'ARCHIVED',
    Canceled: 'CANCELED',
} as const;
export type ReceiptDetailResponseDtoStatusEnum = typeof ReceiptDetailResponseDtoStatusEnum[keyof typeof ReceiptDetailResponseDtoStatusEnum];


/**
 * Check if a given object implements the ReceiptDetailResponseDto interface.
 */
export function instanceOfReceiptDetailResponseDto(value: object): value is ReceiptDetailResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function ReceiptDetailResponseDtoFromJSON(json: any): ReceiptDetailResponseDto {
    return ReceiptDetailResponseDtoFromJSONTyped(json, false);
}

export function ReceiptDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'locationId': json['locationId'],
        'supplierId': json['supplierId'] === undefined ? undefined : json['supplierId'] === null ? null : json['supplierId'],
        'status': json['status'],
        'docNumber': json['docNumber'] === undefined ? undefined : json['docNumber'] === null ? null : json['docNumber'],
        'docDate': json['docDate'] === undefined ? undefined : json['docDate'] === null ? null : json['docDate'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'validatedAt': json['validatedAt'] === undefined ? undefined : json['validatedAt'] === null ? null : json['validatedAt'],
        'lines': ((json['lines'] as Array<any>).map(ReceiptLineResponseDtoFromJSON)),
        'latestExtractionRun': json['latestExtractionRun'] === undefined ? undefined : json['latestExtractionRun'] === null ? null : ReceiptExtractionRunResponseDtoFromJSON(json['latestExtractionRun']),
    };
}

export function ReceiptDetailResponseDtoToJSON(json: any): ReceiptDetailResponseDto {
    return ReceiptDetailResponseDtoToJSONTyped(json, false);
}

export function ReceiptDetailResponseDtoToJSONTyped(value?: ReceiptDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'locationId': value['locationId'],
        'supplierId': value['supplierId'],
        'status': value['status'],
        'docNumber': value['docNumber'],
        'docDate': value['docDate'],
        'note': value['note'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'validatedAt': value['validatedAt'],
        'lines': ((value['lines'] as Array<any>).map(ReceiptLineResponseDtoToJSON)),
        'latestExtractionRun': ReceiptExtractionRunResponseDtoToJSON(value['latestExtractionRun']),
    };
}

