/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ReceiptExtractionLineResponseDto } from './ReceiptExtractionLineResponseDto';
import {
    ReceiptExtractionLineResponseDtoFromJSON,
    ReceiptExtractionLineResponseDtoFromJSONTyped,
    ReceiptExtractionLineResponseDtoToJSON,
    ReceiptExtractionLineResponseDtoToJSONTyped,
} from './ReceiptExtractionLineResponseDto';

/**
 * 
 * @export
 * @interface ReceiptExtractionRunResponseDto
 */
export interface ReceiptExtractionRunResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    receiptId: string;
    /**
     * Private Storage object path — not a fetchable URL by itself, see DocumentStorageService
     */
    documentUrl: string;
    /**
     * The full ExtractionResult exactly as the AI provider returned it
     */
    rawResult: { [key: string]: any; };
    /**
     * 
     */
    createdAt: Date;
    /**
     * Only this run's lines still pending review (reviewStatus === PENDING)
     */
    pendingLines: Array<ReceiptExtractionLineResponseDto>;
}

/**
 * Check if a given object implements the ReceiptExtractionRunResponseDto interface.
 */
export function instanceOfReceiptExtractionRunResponseDto(value: object): value is ReceiptExtractionRunResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('receiptId' in value) || value['receiptId'] === undefined) return false;
    if (!('documentUrl' in value) || value['documentUrl'] === undefined) return false;
    if (!('rawResult' in value) || value['rawResult'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('pendingLines' in value) || value['pendingLines'] === undefined) return false;
    return true;
}

export function ReceiptExtractionRunResponseDtoFromJSON(json: any): ReceiptExtractionRunResponseDto {
    return ReceiptExtractionRunResponseDtoFromJSONTyped(json, false);
}

export function ReceiptExtractionRunResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptExtractionRunResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'receiptId': json['receiptId'],
        'documentUrl': json['documentUrl'],
        'rawResult': json['rawResult'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'pendingLines': ((json['pendingLines'] as Array<any>).map(ReceiptExtractionLineResponseDtoFromJSON)),
    };
}

export function ReceiptExtractionRunResponseDtoToJSON(json: any): ReceiptExtractionRunResponseDto {
    return ReceiptExtractionRunResponseDtoToJSONTyped(json, false);
}

export function ReceiptExtractionRunResponseDtoToJSONTyped(value?: ReceiptExtractionRunResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'receiptId': value['receiptId'],
        'documentUrl': value['documentUrl'],
        'rawResult': value['rawResult'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'pendingLines': ((value['pendingLines'] as Array<any>).map(ReceiptExtractionLineResponseDtoToJSON)),
    };
}

