/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptResponseDto
 */
export interface ReceiptResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * null until resolved — see PATCH /receipts/:id
     */
    supplierId?: object | null;
    /**
     * 
     */
    status: ReceiptResponseDtoStatusEnum;
    /**
     * 
     */
    docNumber?: object | null;
    /**
     * 
     */
    docDate?: object | null;
    /**
     * 
     */
    note?: object | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * Set when confirmed (status -> CONFIRMED)
     */
    validatedAt?: object | null;
}


/**
 * @export
 */
export const ReceiptResponseDtoStatusEnum = {
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    Archived: 'ARCHIVED',
    Canceled: 'CANCELED',
} as const;
export type ReceiptResponseDtoStatusEnum = typeof ReceiptResponseDtoStatusEnum[keyof typeof ReceiptResponseDtoStatusEnum];


/**
 * Check if a given object implements the ReceiptResponseDto interface.
 */
export function instanceOfReceiptResponseDto(value: object): value is ReceiptResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReceiptResponseDtoFromJSON(json: any): ReceiptResponseDto {
    return ReceiptResponseDtoFromJSONTyped(json, false);
}

export function ReceiptResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'locationId': json['locationId'],
        'supplierId': json['supplierId'] === undefined ? undefined : json['supplierId'] === null ? null : json['supplierId'],
        'status': json['status'],
        'docNumber': json['docNumber'] === undefined ? undefined : json['docNumber'] === null ? null : json['docNumber'],
        'docDate': json['docDate'] === undefined ? undefined : json['docDate'] === null ? null : json['docDate'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'validatedAt': json['validatedAt'] === undefined ? undefined : json['validatedAt'] === null ? null : json['validatedAt'],
    };
}

export function ReceiptResponseDtoToJSON(json: any): ReceiptResponseDto {
    return ReceiptResponseDtoToJSONTyped(json, false);
}

export function ReceiptResponseDtoToJSONTyped(value?: ReceiptResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'locationId': value['locationId'],
        'supplierId': value['supplierId'],
        'status': value['status'],
        'docNumber': value['docNumber'],
        'docDate': value['docDate'],
        'note': value['note'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'validatedAt': value['validatedAt'],
    };
}

