/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptLineResponseDto
 */
export interface ReceiptLineResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    receiptId: string;
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    quantity: number;
    /**
     * Can be null until filled in — required before the receipt can be confirmed
     */
    unitPrice?: object | null;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ReceiptLineResponseDto interface.
 */
export function instanceOfReceiptLineResponseDto(value: object): value is ReceiptLineResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('receiptId' in value) || value['receiptId'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReceiptLineResponseDtoFromJSON(json: any): ReceiptLineResponseDto {
    return ReceiptLineResponseDtoFromJSONTyped(json, false);
}

export function ReceiptLineResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptLineResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'receiptId': json['receiptId'],
        'itemId': json['itemId'],
        'quantity': json['quantity'],
        'unitPrice': json['unitPrice'] === undefined ? undefined : json['unitPrice'] === null ? null : json['unitPrice'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function ReceiptLineResponseDtoToJSON(json: any): ReceiptLineResponseDto {
    return ReceiptLineResponseDtoToJSONTyped(json, false);
}

export function ReceiptLineResponseDtoToJSONTyped(value?: ReceiptLineResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'receiptId': value['receiptId'],
        'itemId': value['itemId'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

