/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeResponseDto
 */
export interface RecipeResponseDto {
    /**
     * Recipe ID
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    code?: object | null;
    /**
     * 
     */
    category?: object | null;
    /**
     * 
     */
    subcategory?: object | null;
    /**
     * 
     */
    yieldPortions: number;
    /**
     * 
     */
    yieldFinalUnit?: object | null;
    /**
     * 
     */
    contingencyPct: number;
    /**
     * 
     */
    targetFoodCostPct: number;
    /**
     * 
     */
    targetMarginPct: number;
    /**
     * 
     */
    manualPrice?: object | null;
    /**
     * 
     */
    prepTimeMin?: object | null;
    /**
     * 
     */
    cookTimeMin?: object | null;
    /**
     * 
     */
    laborHourlyCost?: object | null;
    /**
     * 
     */
    laborPeople?: object | null;
    /**
     * 
     */
    prepSteps?: object | null;
    /**
     * 
     */
    allergens?: object | null;
    /**
     * Finished-good item this recipe produces, if any — see POST /productions
     */
    producedItemId?: object | null;
    /**
     * 
     */
    isActive: boolean;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the RecipeResponseDto interface.
 */
export function instanceOfRecipeResponseDto(value: object): value is RecipeResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('yieldPortions' in value) || value['yieldPortions'] === undefined) return false;
    if (!('contingencyPct' in value) || value['contingencyPct'] === undefined) return false;
    if (!('targetFoodCostPct' in value) || value['targetFoodCostPct'] === undefined) return false;
    if (!('targetMarginPct' in value) || value['targetMarginPct'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RecipeResponseDtoFromJSON(json: any): RecipeResponseDto {
    return RecipeResponseDtoFromJSONTyped(json, false);
}

export function RecipeResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'code': json['code'] === undefined ? undefined : json['code'] === null ? null : json['code'],
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'subcategory': json['subcategory'] === undefined ? undefined : json['subcategory'] === null ? null : json['subcategory'],
        'yieldPortions': json['yieldPortions'],
        'yieldFinalUnit': json['yieldFinalUnit'] === undefined ? undefined : json['yieldFinalUnit'] === null ? null : json['yieldFinalUnit'],
        'contingencyPct': json['contingencyPct'],
        'targetFoodCostPct': json['targetFoodCostPct'],
        'targetMarginPct': json['targetMarginPct'],
        'manualPrice': json['manualPrice'] === undefined ? undefined : json['manualPrice'] === null ? null : json['manualPrice'],
        'prepTimeMin': json['prepTimeMin'] === undefined ? undefined : json['prepTimeMin'] === null ? null : json['prepTimeMin'],
        'cookTimeMin': json['cookTimeMin'] === undefined ? undefined : json['cookTimeMin'] === null ? null : json['cookTimeMin'],
        'laborHourlyCost': json['laborHourlyCost'] === undefined ? undefined : json['laborHourlyCost'] === null ? null : json['laborHourlyCost'],
        'laborPeople': json['laborPeople'] === undefined ? undefined : json['laborPeople'] === null ? null : json['laborPeople'],
        'prepSteps': json['prepSteps'] === undefined ? undefined : json['prepSteps'] === null ? null : json['prepSteps'],
        'allergens': json['allergens'] === undefined ? undefined : json['allergens'] === null ? null : json['allergens'],
        'producedItemId': json['producedItemId'] === undefined ? undefined : json['producedItemId'] === null ? null : json['producedItemId'],
        'isActive': json['isActive'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function RecipeResponseDtoToJSON(json: any): RecipeResponseDto {
    return RecipeResponseDtoToJSONTyped(json, false);
}

export function RecipeResponseDtoToJSONTyped(value?: RecipeResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'code': value['code'],
        'category': value['category'],
        'subcategory': value['subcategory'],
        'yieldPortions': value['yieldPortions'],
        'yieldFinalUnit': value['yieldFinalUnit'],
        'contingencyPct': value['contingencyPct'],
        'targetFoodCostPct': value['targetFoodCostPct'],
        'targetMarginPct': value['targetMarginPct'],
        'manualPrice': value['manualPrice'],
        'prepTimeMin': value['prepTimeMin'],
        'cookTimeMin': value['cookTimeMin'],
        'laborHourlyCost': value['laborHourlyCost'],
        'laborPeople': value['laborPeople'],
        'prepSteps': value['prepSteps'],
        'allergens': value['allergens'],
        'producedItemId': value['producedItemId'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

