/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeCostLineResponseDto } from './RecipeCostLineResponseDto';
import {
    RecipeCostLineResponseDtoFromJSON,
    RecipeCostLineResponseDtoFromJSONTyped,
    RecipeCostLineResponseDtoToJSON,
    RecipeCostLineResponseDtoToJSONTyped,
} from './RecipeCostLineResponseDto';

/**
 * 
 * @export
 * @interface RecipeCostResponseDto
 */
export interface RecipeCostResponseDto {
    /**
     * 
     */
    recipeId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * 
     */
    lines: Array<RecipeCostLineResponseDto>;
    /**
     * Sum of every line.lineCost
     */
    costBase: number;
    /**
     * 
     */
    contingencyPct: number;
    /**
     * costBase * (1 + contingencyPct / 100)
     */
    costAdjusted: number;
    /**
     * 
     */
    yieldPortions: number;
    /**
     * costAdjusted / yieldPortions
     */
    costPerPortion: number;
    /**
     * Finished-good item this recipe produces, if any — a POST /productions of this recipe will also create a stock_lot of this item at costAdjusted / quantityProduced per unit.
     */
    producedItemId?: object | null;
}

/**
 * Check if a given object implements the RecipeCostResponseDto interface.
 */
export function instanceOfRecipeCostResponseDto(value: object): value is RecipeCostResponseDto {
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    if (!('costBase' in value) || value['costBase'] === undefined) return false;
    if (!('contingencyPct' in value) || value['contingencyPct'] === undefined) return false;
    if (!('costAdjusted' in value) || value['costAdjusted'] === undefined) return false;
    if (!('yieldPortions' in value) || value['yieldPortions'] === undefined) return false;
    if (!('costPerPortion' in value) || value['costPerPortion'] === undefined) return false;
    return true;
}

export function RecipeCostResponseDtoFromJSON(json: any): RecipeCostResponseDto {
    return RecipeCostResponseDtoFromJSONTyped(json, false);
}

export function RecipeCostResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeCostResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recipeId': json['recipeId'],
        'locationId': json['locationId'],
        'lines': ((json['lines'] as Array<any>).map(RecipeCostLineResponseDtoFromJSON)),
        'costBase': json['costBase'],
        'contingencyPct': json['contingencyPct'],
        'costAdjusted': json['costAdjusted'],
        'yieldPortions': json['yieldPortions'],
        'costPerPortion': json['costPerPortion'],
        'producedItemId': json['producedItemId'] === undefined ? undefined : json['producedItemId'] === null ? null : json['producedItemId'],
    };
}

export function RecipeCostResponseDtoToJSON(json: any): RecipeCostResponseDto {
    return RecipeCostResponseDtoToJSONTyped(json, false);
}

export function RecipeCostResponseDtoToJSONTyped(value?: RecipeCostResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipeId': value['recipeId'],
        'locationId': value['locationId'],
        'lines': ((value['lines'] as Array<any>).map(RecipeCostLineResponseDtoToJSON)),
        'costBase': value['costBase'],
        'contingencyPct': value['contingencyPct'],
        'costAdjusted': value['costAdjusted'],
        'yieldPortions': value['yieldPortions'],
        'costPerPortion': value['costPerPortion'],
        'producedItemId': value['producedItemId'],
    };
}

