/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeCostLineResponseDto
 */
export interface RecipeCostLineResponseDto {
    /**
     * 
     */
    recipeIngredientId: string;
    /**
     * Set for an item line, null for a subrecipe line
     */
    itemId?: object | null;
    /**
     * 
     */
    itemName?: object | null;
    /**
     * Set for a subrecipe line, null for an item line
     */
    subrecipeId?: object | null;
    /**
     * 
     */
    subrecipeName?: object | null;
    /**
     * 
     */
    quantityNet: number;
    /**
     * 
     */
    wastePct: number;
    /**
     * 
     */
    quantityGross: number;
    /**
     * Item line: unit cost of the oldest stock_lots row with quantity_remaining > 0 for this item at the given location, NOT supplier_item_prices (see CLAUDE.md). Subrecipe line: the subrecipe's own costBase / yieldPortions, recursively computed.
     */
    unitCost: number;
    /**
     * Item line: quantityGross * unitCost. Subrecipe line: quantityNet * unitCost (see CLAUDE.md's Subrecipes section for why).
     */
    lineCost: number;
}

/**
 * Check if a given object implements the RecipeCostLineResponseDto interface.
 */
export function instanceOfRecipeCostLineResponseDto(value: object): value is RecipeCostLineResponseDto {
    if (!('recipeIngredientId' in value) || value['recipeIngredientId'] === undefined) return false;
    if (!('quantityNet' in value) || value['quantityNet'] === undefined) return false;
    if (!('wastePct' in value) || value['wastePct'] === undefined) return false;
    if (!('quantityGross' in value) || value['quantityGross'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    if (!('lineCost' in value) || value['lineCost'] === undefined) return false;
    return true;
}

export function RecipeCostLineResponseDtoFromJSON(json: any): RecipeCostLineResponseDto {
    return RecipeCostLineResponseDtoFromJSONTyped(json, false);
}

export function RecipeCostLineResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeCostLineResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recipeIngredientId': json['recipeIngredientId'],
        'itemId': json['itemId'] === undefined ? undefined : json['itemId'] === null ? null : json['itemId'],
        'itemName': json['itemName'] === undefined ? undefined : json['itemName'] === null ? null : json['itemName'],
        'subrecipeId': json['subrecipeId'] === undefined ? undefined : json['subrecipeId'] === null ? null : json['subrecipeId'],
        'subrecipeName': json['subrecipeName'] === undefined ? undefined : json['subrecipeName'] === null ? null : json['subrecipeName'],
        'quantityNet': json['quantityNet'],
        'wastePct': json['wastePct'],
        'quantityGross': json['quantityGross'],
        'unitCost': json['unitCost'],
        'lineCost': json['lineCost'],
    };
}

export function RecipeCostLineResponseDtoToJSON(json: any): RecipeCostLineResponseDto {
    return RecipeCostLineResponseDtoToJSONTyped(json, false);
}

export function RecipeCostLineResponseDtoToJSONTyped(value?: RecipeCostLineResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipeIngredientId': value['recipeIngredientId'],
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'subrecipeId': value['subrecipeId'],
        'subrecipeName': value['subrecipeName'],
        'quantityNet': value['quantityNet'],
        'wastePct': value['wastePct'],
        'quantityGross': value['quantityGross'],
        'unitCost': value['unitCost'],
        'lineCost': value['lineCost'],
    };
}

