/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RecipeExtractionLineResponseDto } from './RecipeExtractionLineResponseDto';
import {
    RecipeExtractionLineResponseDtoFromJSON,
    RecipeExtractionLineResponseDtoFromJSONTyped,
    RecipeExtractionLineResponseDtoToJSON,
    RecipeExtractionLineResponseDtoToJSONTyped,
} from './RecipeExtractionLineResponseDto';

/**
 * 
 * @export
 * @interface RecipeExtractionRunResponseDto
 */
export interface RecipeExtractionRunResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * Private Storage object path — not a fetchable URL by itself, see DocumentStorageService
     */
    documentUrl: string;
    /**
     * The full ExtractionResult exactly as the AI provider returned it
     */
    rawResult: { [key: string]: any; };
    /**
     * 
     */
    suggestedName?: object | null;
    /**
     * 
     */
    suggestedYieldPortions?: object | null;
    /**
     * 
     */
    suggestedPrepSteps?: object | null;
    /**
     * 
     */
    status: RecipeExtractionRunResponseDtoStatusEnum;
    /**
     * 
     */
    createdAt: Date;
    /**
     * This run's proposed ingredient lines, in ANY reviewStatus (unlike Receipts' pendingLines, there is exactly one run per scan draft, so a human reviewing it needs to see everything, not just what's still pending).
     */
    lines: Array<RecipeExtractionLineResponseDto>;
}


/**
 * @export
 */
export const RecipeExtractionRunResponseDtoStatusEnum = {
    Pending: 'PENDING',
    Committed: 'COMMITTED',
    Discarded: 'DISCARDED',
} as const;
export type RecipeExtractionRunResponseDtoStatusEnum = typeof RecipeExtractionRunResponseDtoStatusEnum[keyof typeof RecipeExtractionRunResponseDtoStatusEnum];


/**
 * Check if a given object implements the RecipeExtractionRunResponseDto interface.
 */
export function instanceOfRecipeExtractionRunResponseDto(value: object): value is RecipeExtractionRunResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('documentUrl' in value) || value['documentUrl'] === undefined) return false;
    if (!('rawResult' in value) || value['rawResult'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function RecipeExtractionRunResponseDtoFromJSON(json: any): RecipeExtractionRunResponseDto {
    return RecipeExtractionRunResponseDtoFromJSONTyped(json, false);
}

export function RecipeExtractionRunResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeExtractionRunResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'documentUrl': json['documentUrl'],
        'rawResult': json['rawResult'],
        'suggestedName': json['suggestedName'] === undefined ? undefined : json['suggestedName'] === null ? null : json['suggestedName'],
        'suggestedYieldPortions': json['suggestedYieldPortions'] === undefined ? undefined : json['suggestedYieldPortions'] === null ? null : json['suggestedYieldPortions'],
        'suggestedPrepSteps': json['suggestedPrepSteps'] === undefined ? undefined : json['suggestedPrepSteps'] === null ? null : json['suggestedPrepSteps'],
        'status': json['status'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'lines': ((json['lines'] as Array<any>).map(RecipeExtractionLineResponseDtoFromJSON)),
    };
}

export function RecipeExtractionRunResponseDtoToJSON(json: any): RecipeExtractionRunResponseDto {
    return RecipeExtractionRunResponseDtoToJSONTyped(json, false);
}

export function RecipeExtractionRunResponseDtoToJSONTyped(value?: RecipeExtractionRunResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'documentUrl': value['documentUrl'],
        'rawResult': value['rawResult'],
        'suggestedName': value['suggestedName'],
        'suggestedYieldPortions': value['suggestedYieldPortions'],
        'suggestedPrepSteps': value['suggestedPrepSteps'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'lines': ((value['lines'] as Array<any>).map(RecipeExtractionLineResponseDtoToJSON)),
    };
}

