/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeExtractionLineResponseDto
 */
export interface RecipeExtractionLineResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    tenantId: string;
    /**
     * 
     */
    extractionRunId: string;
    /**
     * 
     */
    rawIngredientName?: object | null;
    /**
     * 
     */
    rawQuantity?: object | null;
    /**
     * 
     */
    rawUnit?: object | null;
    /**
     * Automatic name-match against the tenant's items, if any — informational until accepted, at which point it reflects what was actually chosen.
     */
    matchedItemId?: object | null;
    /**
     * Automatic name-match against the tenant's OWN recipes (as a possible subrecipe), if any — mutually exclusive with matchedItemId.
     */
    matchedRecipeId?: object | null;
    /**
     * Minimum of this line's per-field extraction confidences
     */
    confidence?: object | null;
    /**
     * Confirmed net quantity — null until this line is accepted (POST .../accept sets it, possibly edited from rawQuantity/rawUnit).
     */
    quantityNet?: object | null;
    /**
     * Confirmed waste percentage — 0 until accepted sets otherwise.
     */
    wastePct: number;
    /**
     * 
     */
    reviewStatus: RecipeExtractionLineResponseDtoReviewStatusEnum;
    /**
     * 
     */
    createdAt: Date;
}


/**
 * @export
 */
export const RecipeExtractionLineResponseDtoReviewStatusEnum = {
    Pending: 'PENDING',
    Accepted: 'ACCEPTED',
    Rejected: 'REJECTED',
} as const;
export type RecipeExtractionLineResponseDtoReviewStatusEnum = typeof RecipeExtractionLineResponseDtoReviewStatusEnum[keyof typeof RecipeExtractionLineResponseDtoReviewStatusEnum];


/**
 * Check if a given object implements the RecipeExtractionLineResponseDto interface.
 */
export function instanceOfRecipeExtractionLineResponseDto(value: object): value is RecipeExtractionLineResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('extractionRunId' in value) || value['extractionRunId'] === undefined) return false;
    if (!('wastePct' in value) || value['wastePct'] === undefined) return false;
    if (!('reviewStatus' in value) || value['reviewStatus'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RecipeExtractionLineResponseDtoFromJSON(json: any): RecipeExtractionLineResponseDto {
    return RecipeExtractionLineResponseDtoFromJSONTyped(json, false);
}

export function RecipeExtractionLineResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeExtractionLineResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'extractionRunId': json['extractionRunId'],
        'rawIngredientName': json['rawIngredientName'] === undefined ? undefined : json['rawIngredientName'] === null ? null : json['rawIngredientName'],
        'rawQuantity': json['rawQuantity'] === undefined ? undefined : json['rawQuantity'] === null ? null : json['rawQuantity'],
        'rawUnit': json['rawUnit'] === undefined ? undefined : json['rawUnit'] === null ? null : json['rawUnit'],
        'matchedItemId': json['matchedItemId'] === undefined ? undefined : json['matchedItemId'] === null ? null : json['matchedItemId'],
        'matchedRecipeId': json['matchedRecipeId'] === undefined ? undefined : json['matchedRecipeId'] === null ? null : json['matchedRecipeId'],
        'confidence': json['confidence'] === undefined ? undefined : json['confidence'] === null ? null : json['confidence'],
        'quantityNet': json['quantityNet'] === undefined ? undefined : json['quantityNet'] === null ? null : json['quantityNet'],
        'wastePct': json['wastePct'],
        'reviewStatus': json['reviewStatus'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function RecipeExtractionLineResponseDtoToJSON(json: any): RecipeExtractionLineResponseDto {
    return RecipeExtractionLineResponseDtoToJSONTyped(json, false);
}

export function RecipeExtractionLineResponseDtoToJSONTyped(value?: RecipeExtractionLineResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'extractionRunId': value['extractionRunId'],
        'rawIngredientName': value['rawIngredientName'],
        'rawQuantity': value['rawQuantity'],
        'rawUnit': value['rawUnit'],
        'matchedItemId': value['matchedItemId'],
        'matchedRecipeId': value['matchedRecipeId'],
        'confidence': value['confidence'],
        'quantityNet': value['quantityNet'],
        'wastePct': value['wastePct'],
        'reviewStatus': value['reviewStatus'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

