/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ItemResponseDto } from './ItemResponseDto';
import {
    ItemResponseDtoFromJSON,
    ItemResponseDtoFromJSONTyped,
    ItemResponseDtoToJSON,
    ItemResponseDtoToJSONTyped,
} from './ItemResponseDto';

/**
 * 
 * @export
 * @interface RecipeIngredientResponseDto
 */
export interface RecipeIngredientResponseDto {
    /**
     * Recipe ingredient line ID
     */
    id: string;
    /**
     * 
     */
    recipeId: string;
    /**
     * Set for an item line, null for a subrecipe line
     */
    itemId?: object | null;
    /**
     * Set for a subrecipe line, null for an item line
     */
    subrecipeId?: object | null;
    /**
     * 
     */
    quantityNet: number;
    /**
     * 
     */
    wastePct: number;
    /**
     * quantityNet / (1 - wastePct/100) — always computed on read, never stored (see recipe_ingredients migration).
     */
    quantityGross: number;
    /**
     * 
     */
    createdAt: Date;
    /**
     * Populated only for an item line — null for a subrecipe line
     */
    item?: ItemResponseDto | null;
}

/**
 * Check if a given object implements the RecipeIngredientResponseDto interface.
 */
export function instanceOfRecipeIngredientResponseDto(value: object): value is RecipeIngredientResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('quantityNet' in value) || value['quantityNet'] === undefined) return false;
    if (!('wastePct' in value) || value['wastePct'] === undefined) return false;
    if (!('quantityGross' in value) || value['quantityGross'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RecipeIngredientResponseDtoFromJSON(json: any): RecipeIngredientResponseDto {
    return RecipeIngredientResponseDtoFromJSONTyped(json, false);
}

export function RecipeIngredientResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeIngredientResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'recipeId': json['recipeId'],
        'itemId': json['itemId'] === undefined ? undefined : json['itemId'] === null ? null : json['itemId'],
        'subrecipeId': json['subrecipeId'] === undefined ? undefined : json['subrecipeId'] === null ? null : json['subrecipeId'],
        'quantityNet': json['quantityNet'],
        'wastePct': json['wastePct'],
        'quantityGross': json['quantityGross'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'item': json['item'] === undefined ? undefined : json['item'] === null ? null : ItemResponseDtoFromJSON(json['item']),
    };
}

export function RecipeIngredientResponseDtoToJSON(json: any): RecipeIngredientResponseDto {
    return RecipeIngredientResponseDtoToJSONTyped(json, false);
}

export function RecipeIngredientResponseDtoToJSONTyped(value?: RecipeIngredientResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'recipeId': value['recipeId'],
        'itemId': value['itemId'],
        'subrecipeId': value['subrecipeId'],
        'quantityNet': value['quantityNet'],
        'wastePct': value['wastePct'],
        'quantityGross': value['quantityGross'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'item': ItemResponseDtoToJSON(value['item']),
    };
}

