/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponseDto
 */
export interface RegisterResponseDto {
    /**
     * Supabase Auth JWT — tenant_id claim absent
     */
    accessToken: string;
    /**
     * 
     */
    refreshToken: string;
    /**
     * 
     */
    expiresIn: number;
    /**
     * 
     */
    tokenType: string;
    /**
     * Supabase Auth user ID (auth.users.id)
     */
    userId: string;
    /**
     * 
     */
    email: string;
}

/**
 * Check if a given object implements the RegisterResponseDto interface.
 */
export function instanceOfRegisterResponseDto(value: object): value is RegisterResponseDto {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RegisterResponseDtoFromJSON(json: any): RegisterResponseDto {
    return RegisterResponseDtoFromJSONTyped(json, false);
}

export function RegisterResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'expiresIn': json['expiresIn'],
        'tokenType': json['tokenType'],
        'userId': json['userId'],
        'email': json['email'],
    };
}

export function RegisterResponseDtoToJSON(json: any): RegisterResponseDto {
    return RegisterResponseDtoToJSONTyped(json, false);
}

export function RegisterResponseDtoToJSONTyped(value?: RegisterResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'expiresIn': value['expiresIn'],
        'tokenType': value['tokenType'],
        'userId': value['userId'],
        'email': value['email'],
    };
}

