/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * 
     */
    firstName: string;
    /**
     * 
     */
    lastName: string;
    /**
     * 
     */
    email: string;
    /**
     * Minimum 8 characters. No other complexity rule enforced yet.
     */
    password: string;
    /**
     * Must be true — the UI shows this checkbox at this step because this is where personal data starts being processed. false or missing is rejected with 400 TERMS_NOT_ACCEPTED (not a generic validation error, so the frontend can show a dedicated message).
     */
    termsAccepted: boolean;
    /**
     * Identifier of the T&C version shown to the user. Must match the version the backend currently recognizes as current (see CURRENT_TERMS_VERSION) — a mismatch is rejected the same way as termsAccepted: false (400 TERMS_NOT_ACCEPTED), since a stale frontend showing an outdated document needs the same fix: reload and re-accept the current one.
     */
    termsVersion: string;
}

/**
 * Check if a given object implements the RegisterDto interface.
 */
export function instanceOfRegisterDto(value: object): value is RegisterDto {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('termsAccepted' in value) || value['termsAccepted'] === undefined) return false;
    if (!('termsVersion' in value) || value['termsVersion'] === undefined) return false;
    return true;
}

export function RegisterDtoFromJSON(json: any): RegisterDto {
    return RegisterDtoFromJSONTyped(json, false);
}

export function RegisterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'password': json['password'],
        'termsAccepted': json['termsAccepted'],
        'termsVersion': json['termsVersion'],
    };
}

export function RegisterDtoToJSON(json: any): RegisterDto {
    return RegisterDtoToJSONTyped(json, false);
}

export function RegisterDtoToJSONTyped(value?: RegisterDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'password': value['password'],
        'termsAccepted': value['termsAccepted'],
        'termsVersion': value['termsVersion'],
    };
}

