/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface StockLotResponseDto
 */
export interface StockLotResponseDto {
    /**
     * Stock lot ID
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    locationId: string;
    /**
     * 
     */
    supplierId?: object | null;
    /**
     * 
     */
    quantityReceived: number;
    /**
     * Remaining quantity from this lot — only changed internally by FIFO consumption, never directly editable
     */
    quantityRemaining: number;
    /**
     * 
     */
    unitCost: number;
    /**
     * 
     */
    receivedAt: Date;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the StockLotResponseDto interface.
 */
export function instanceOfStockLotResponseDto(value: object): value is StockLotResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('quantityReceived' in value) || value['quantityReceived'] === undefined) return false;
    if (!('quantityRemaining' in value) || value['quantityRemaining'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    if (!('receivedAt' in value) || value['receivedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function StockLotResponseDtoFromJSON(json: any): StockLotResponseDto {
    return StockLotResponseDtoFromJSONTyped(json, false);
}

export function StockLotResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockLotResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'itemId': json['itemId'],
        'locationId': json['locationId'],
        'supplierId': json['supplierId'] === undefined ? undefined : json['supplierId'] === null ? null : json['supplierId'],
        'quantityReceived': json['quantityReceived'],
        'quantityRemaining': json['quantityRemaining'],
        'unitCost': json['unitCost'],
        'receivedAt': (json['receivedAt'] == null ? json['receivedAt'] : parseDateTime(json['receivedAt'])),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function StockLotResponseDtoToJSON(json: any): StockLotResponseDto {
    return StockLotResponseDtoToJSONTyped(json, false);
}

export function StockLotResponseDtoToJSONTyped(value?: StockLotResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'itemId': value['itemId'],
        'locationId': value['locationId'],
        'supplierId': value['supplierId'],
        'quantityReceived': value['quantityReceived'],
        'quantityRemaining': value['quantityRemaining'],
        'unitCost': value['unitCost'],
        'receivedAt': value['receivedAt'] == null ? value['receivedAt'] : serializeDateTime(value['receivedAt']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

