/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { SupplierResponseDto } from './SupplierResponseDto';
import {
    SupplierResponseDtoFromJSON,
    SupplierResponseDtoFromJSONTyped,
    SupplierResponseDtoToJSON,
    SupplierResponseDtoToJSONTyped,
} from './SupplierResponseDto';

/**
 * 
 * @export
 * @interface SupplierItemPriceResponseDto
 */
export interface SupplierItemPriceResponseDto {
    /**
     * Price row ID
     */
    id: string;
    /**
     * Item ID this price belongs to
     */
    itemId: string;
    /**
     * Supplier ID this price is from
     */
    supplierId: string;
    /**
     * Price this supplier charges
     */
    price: number;
    /**
     * 
     */
    unitConversionFactor?: object | null;
    /**
     * 
     */
    isPreferred: boolean;
    /**
     * 
     */
    validFrom: Date;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    supplier: SupplierResponseDto;
}

/**
 * Check if a given object implements the SupplierItemPriceResponseDto interface.
 */
export function instanceOfSupplierItemPriceResponseDto(value: object): value is SupplierItemPriceResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('isPreferred' in value) || value['isPreferred'] === undefined) return false;
    if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('supplier' in value) || value['supplier'] === undefined) return false;
    return true;
}

export function SupplierItemPriceResponseDtoFromJSON(json: any): SupplierItemPriceResponseDto {
    return SupplierItemPriceResponseDtoFromJSONTyped(json, false);
}

export function SupplierItemPriceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierItemPriceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['itemId'],
        'supplierId': json['supplierId'],
        'price': json['price'],
        'unitConversionFactor': json['unitConversionFactor'] === undefined ? undefined : json['unitConversionFactor'] === null ? null : json['unitConversionFactor'],
        'isPreferred': json['isPreferred'],
        'validFrom': (json['validFrom'] == null ? json['validFrom'] : parseDateTime(json['validFrom'])),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'supplier': SupplierResponseDtoFromJSON(json['supplier']),
    };
}

export function SupplierItemPriceResponseDtoToJSON(json: any): SupplierItemPriceResponseDto {
    return SupplierItemPriceResponseDtoToJSONTyped(json, false);
}

export function SupplierItemPriceResponseDtoToJSONTyped(value?: SupplierItemPriceResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'itemId': value['itemId'],
        'supplierId': value['supplierId'],
        'price': value['price'],
        'unitConversionFactor': value['unitConversionFactor'],
        'isPreferred': value['isPreferred'],
        'validFrom': value['validFrom'] == null ? value['validFrom'] : serializeDateTime(value['validFrom']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'supplier': SupplierResponseDtoToJSON(value['supplier']),
    };
}

