/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SupplierResponseDto
 */
export interface SupplierResponseDto {
    /**
     * Supplier ID
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    taxId?: object | null;
    /**
     * 
     */
    phone?: object | null;
    /**
     * 
     */
    email?: object | null;
    /**
     * 
     */
    address?: object | null;
    /**
     * 
     */
    isActive: boolean;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the SupplierResponseDto interface.
 */
export function instanceOfSupplierResponseDto(value: object): value is SupplierResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SupplierResponseDtoFromJSON(json: any): SupplierResponseDto {
    return SupplierResponseDtoFromJSONTyped(json, false);
}

export function SupplierResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'name': json['name'],
        'taxId': json['taxId'] === undefined ? undefined : json['taxId'] === null ? null : json['taxId'],
        'phone': json['phone'] === undefined ? undefined : json['phone'] === null ? null : json['phone'],
        'email': json['email'] === undefined ? undefined : json['email'] === null ? null : json['email'],
        'address': json['address'] === undefined ? undefined : json['address'] === null ? null : json['address'],
        'isActive': json['isActive'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function SupplierResponseDtoToJSON(json: any): SupplierResponseDto {
    return SupplierResponseDtoToJSONTyped(json, false);
}

export function SupplierResponseDtoToJSONTyped(value?: SupplierResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'name': value['name'],
        'taxId': value['taxId'],
        'phone': value['phone'],
        'email': value['email'],
        'address': value['address'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

