/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSupplierDto
 */
export interface UpdateSupplierDto {
    /**
     * Supplier name
     */
    name?: string;
    /**
     * Tax ID / CUIT
     */
    taxId?: string;
    /**
     * Contact phone
     */
    phone?: string;
    /**
     * Contact email
     */
    email?: string;
    /**
     * Address
     */
    address?: string;
}

/**
 * Check if a given object implements the UpdateSupplierDto interface.
 */
export function instanceOfUpdateSupplierDto(value: object): value is UpdateSupplierDto {
    return true;
}

export function UpdateSupplierDtoFromJSON(json: any): UpdateSupplierDto {
    return UpdateSupplierDtoFromJSONTyped(json, false);
}

export function UpdateSupplierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSupplierDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'taxId': json['taxId'] == null ? undefined : json['taxId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function UpdateSupplierDtoToJSON(json: any): UpdateSupplierDto {
    return UpdateSupplierDtoToJSONTyped(json, false);
}

export function UpdateSupplierDtoToJSONTyped(value?: UpdateSupplierDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'taxId': value['taxId'],
        'phone': value['phone'],
        'email': value['email'],
        'address': value['address'],
    };
}

