/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSupplierItemPriceDto
 */
export interface UpdateSupplierItemPriceDto {
    /**
     * Price this supplier charges for this item
     */
    price?: number;
    /**
     * Purchase-unit to base-unit conversion factor (e.g. 24 if this supplier sells by the box and the item's base unit is 'unit', with 24 units per box)
     */
    unitConversionFactor?: number;
    /**
     * Marks this as the preferred supplier for the item. Setting true automatically unmarks any other price row for the same item that was previously preferred.
     */
    isPreferred?: boolean;
}

/**
 * Check if a given object implements the UpdateSupplierItemPriceDto interface.
 */
export function instanceOfUpdateSupplierItemPriceDto(value: object): value is UpdateSupplierItemPriceDto {
    return true;
}

export function UpdateSupplierItemPriceDtoFromJSON(json: any): UpdateSupplierItemPriceDto {
    return UpdateSupplierItemPriceDtoFromJSONTyped(json, false);
}

export function UpdateSupplierItemPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSupplierItemPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'price': json['price'] == null ? undefined : json['price'],
        'unitConversionFactor': json['unitConversionFactor'] == null ? undefined : json['unitConversionFactor'],
        'isPreferred': json['isPreferred'] == null ? undefined : json['isPreferred'],
    };
}

export function UpdateSupplierItemPriceDtoToJSON(json: any): UpdateSupplierItemPriceDto {
    return UpdateSupplierItemPriceDtoToJSONTyped(json, false);
}

export function UpdateSupplierItemPriceDtoToJSONTyped(value?: UpdateSupplierItemPriceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': value['price'],
        'unitConversionFactor': value['unitConversionFactor'],
        'isPreferred': value['isPreferred'],
    };
}

