/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateItemDto
 */
export interface UpdateItemDto {
    /**
     * Item name
     */
    name?: string;
    /**
     * Base unit of measure
     */
    unit?: string;
    /**
     * Item category
     */
    category?: string;
    /**
     * Minimum stock before alerting
     */
    minStock?: number;
    /**
     * Recommended maximum stock
     */
    maxStock?: number;
    /**
     * Default expected waste percentage (0-100)
     */
    wasteDefaultPct?: number;
}

/**
 * Check if a given object implements the UpdateItemDto interface.
 */
export function instanceOfUpdateItemDto(value: object): value is UpdateItemDto {
    return true;
}

export function UpdateItemDtoFromJSON(json: any): UpdateItemDto {
    return UpdateItemDtoFromJSONTyped(json, false);
}

export function UpdateItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'category': json['category'] == null ? undefined : json['category'],
        'minStock': json['minStock'] == null ? undefined : json['minStock'],
        'maxStock': json['maxStock'] == null ? undefined : json['maxStock'],
        'wasteDefaultPct': json['wasteDefaultPct'] == null ? undefined : json['wasteDefaultPct'],
    };
}

export function UpdateItemDtoToJSON(json: any): UpdateItemDto {
    return UpdateItemDtoToJSONTyped(json, false);
}

export function UpdateItemDtoToJSONTyped(value?: UpdateItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'unit': value['unit'],
        'category': value['category'],
        'minStock': value['minStock'],
        'maxStock': value['maxStock'],
        'wasteDefaultPct': value['wasteDefaultPct'],
    };
}

