/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWasteDto
 */
export interface UpdateWasteDto {
    /**
     * ID of an existing item, belonging to the current tenant
     */
    itemId?: string;
    /**
     * Quantity wasted, in the item's base unit
     */
    quantity?: number;
    /**
     * 
     */
    reason?: UpdateWasteDtoReasonEnum;
    /**
     * 
     */
    notes?: string;
}


/**
 * @export
 */
export const UpdateWasteDtoReasonEnum = {
    MalEstado: 'Mal estado',
    Caducado: 'Caducado',
    Rotura: 'Rotura',
    ErrorDeProduccin: 'Error de producción',
    Quemado: 'Quemado',
    SobranteNoReutilizable: 'Sobrante no reutilizable',
    ContaminacinCruzada: 'Contaminación cruzada',
    DevolucinInterna: 'Devolución interna',
    PruebaTest: 'Prueba / test',
    Otro: 'Otro',
} as const;
export type UpdateWasteDtoReasonEnum = typeof UpdateWasteDtoReasonEnum[keyof typeof UpdateWasteDtoReasonEnum];


/**
 * Check if a given object implements the UpdateWasteDto interface.
 */
export function instanceOfUpdateWasteDto(value: object): value is UpdateWasteDto {
    return true;
}

export function UpdateWasteDtoFromJSON(json: any): UpdateWasteDto {
    return UpdateWasteDtoFromJSONTyped(json, false);
}

export function UpdateWasteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWasteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function UpdateWasteDtoToJSON(json: any): UpdateWasteDto {
    return UpdateWasteDtoToJSONTyped(json, false);
}

export function UpdateWasteDtoToJSONTyped(value?: UpdateWasteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'notes': value['notes'],
    };
}

