/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReceiptDto
 */
export interface UpdateReceiptDto {
    /**
     * 
     */
    supplierId?: string;
    /**
     * 
     */
    docNumber?: string;
    /**
     * 
     */
    docDate?: string;
    /**
     * 
     */
    note?: string;
}

/**
 * Check if a given object implements the UpdateReceiptDto interface.
 */
export function instanceOfUpdateReceiptDto(value: object): value is UpdateReceiptDto {
    return true;
}

export function UpdateReceiptDtoFromJSON(json: any): UpdateReceiptDto {
    return UpdateReceiptDtoFromJSONTyped(json, false);
}

export function UpdateReceiptDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReceiptDto {
    if (json == null) {
        return json;
    }
    return {
        
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'docNumber': json['docNumber'] == null ? undefined : json['docNumber'],
        'docDate': json['docDate'] == null ? undefined : json['docDate'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function UpdateReceiptDtoToJSON(json: any): UpdateReceiptDto {
    return UpdateReceiptDtoToJSONTyped(json, false);
}

export function UpdateReceiptDtoToJSONTyped(value?: UpdateReceiptDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'supplierId': value['supplierId'],
        'docNumber': value['docNumber'],
        'docDate': value['docDate'],
        'note': value['note'],
    };
}

