/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRecipeExtractionRunDto
 */
export interface UpdateRecipeExtractionRunDto {
    /**
     * 
     */
    suggestedName?: string;
    /**
     * 
     */
    suggestedYieldPortions?: number;
    /**
     * 
     */
    suggestedPrepSteps?: string;
}

/**
 * Check if a given object implements the UpdateRecipeExtractionRunDto interface.
 */
export function instanceOfUpdateRecipeExtractionRunDto(value: object): value is UpdateRecipeExtractionRunDto {
    return true;
}

export function UpdateRecipeExtractionRunDtoFromJSON(json: any): UpdateRecipeExtractionRunDto {
    return UpdateRecipeExtractionRunDtoFromJSONTyped(json, false);
}

export function UpdateRecipeExtractionRunDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecipeExtractionRunDto {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestedName': json['suggestedName'] == null ? undefined : json['suggestedName'],
        'suggestedYieldPortions': json['suggestedYieldPortions'] == null ? undefined : json['suggestedYieldPortions'],
        'suggestedPrepSteps': json['suggestedPrepSteps'] == null ? undefined : json['suggestedPrepSteps'],
    };
}

export function UpdateRecipeExtractionRunDtoToJSON(json: any): UpdateRecipeExtractionRunDto {
    return UpdateRecipeExtractionRunDtoToJSONTyped(json, false);
}

export function UpdateRecipeExtractionRunDtoToJSONTyped(value?: UpdateRecipeExtractionRunDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestedName': value['suggestedName'],
        'suggestedYieldPortions': value['suggestedYieldPortions'],
        'suggestedPrepSteps': value['suggestedPrepSteps'],
    };
}

