/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLocationDto
 */
export interface UpdateLocationDto {
    /**
     * Location name
     */
    name?: string;
    /**
     * Address
     */
    address?: string;
}

/**
 * Check if a given object implements the UpdateLocationDto interface.
 */
export function instanceOfUpdateLocationDto(value: object): value is UpdateLocationDto {
    return true;
}

export function UpdateLocationDtoFromJSON(json: any): UpdateLocationDto {
    return UpdateLocationDtoFromJSONTyped(json, false);
}

export function UpdateLocationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLocationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function UpdateLocationDtoToJSON(json: any): UpdateLocationDto {
    return UpdateLocationDtoToJSONTyped(json, false);
}

export function UpdateLocationDtoToJSONTyped(value?: UpdateLocationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
    };
}

