/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateStockLotDto
 */
export interface UpdateStockLotDto {
    /**
     * Corrected cost per base unit for this lot
     */
    unitCost: number;
}

/**
 * Check if a given object implements the UpdateStockLotDto interface.
 */
export function instanceOfUpdateStockLotDto(value: object): value is UpdateStockLotDto {
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    return true;
}

export function UpdateStockLotDtoFromJSON(json: any): UpdateStockLotDto {
    return UpdateStockLotDtoFromJSONTyped(json, false);
}

export function UpdateStockLotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStockLotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'unitCost': json['unitCost'],
    };
}

export function UpdateStockLotDtoToJSON(json: any): UpdateStockLotDto {
    return UpdateStockLotDtoToJSONTyped(json, false);
}

export function UpdateStockLotDtoToJSONTyped(value?: UpdateStockLotDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unitCost': value['unitCost'],
    };
}

