/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRecipeIngredientDto
 */
export interface UpdateRecipeIngredientDto {
    /**
     * An existing recipe, belonging to the current tenant, used as a subrecipe ingredient. Mutually exclusive with itemId. Cannot equal the parent recipe itself.
     */
    subrecipeId?: string;
    /**
     * Net quantity used. For an item line, in the item's own base unit (items.unit) — no conversion happens here. For a subrecipe line, in the same 'yield unit' as the subrecipe's own yieldPortions (and, when set, its producedItemId's stock) — see CLAUDE.md's Subrecipes section.
     */
    quantityNet?: number;
    /**
     * Expected waste percentage for this ingredient in this recipe (0-99.99). Capped below 100: quantityGross = quantityNet / (1 - wastePct/100), which is undefined at exactly 100. For a subrecipe line: still used for consumption (quantityGross), but ignored for costing, which always uses quantityNet for a subrecipe line regardless of wastePct — see CLAUDE.md's Subrecipes section.
     */
    wastePct?: number;
}

/**
 * Check if a given object implements the UpdateRecipeIngredientDto interface.
 */
export function instanceOfUpdateRecipeIngredientDto(value: object): value is UpdateRecipeIngredientDto {
    return true;
}

export function UpdateRecipeIngredientDtoFromJSON(json: any): UpdateRecipeIngredientDto {
    return UpdateRecipeIngredientDtoFromJSONTyped(json, false);
}

export function UpdateRecipeIngredientDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecipeIngredientDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subrecipeId': json['subrecipeId'] == null ? undefined : json['subrecipeId'],
        'quantityNet': json['quantityNet'] == null ? undefined : json['quantityNet'],
        'wastePct': json['wastePct'] == null ? undefined : json['wastePct'],
    };
}

export function UpdateRecipeIngredientDtoToJSON(json: any): UpdateRecipeIngredientDto {
    return UpdateRecipeIngredientDtoToJSONTyped(json, false);
}

export function UpdateRecipeIngredientDtoToJSONTyped(value?: UpdateRecipeIngredientDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subrecipeId': value['subrecipeId'],
        'quantityNet': value['quantityNet'],
        'wastePct': value['wastePct'],
    };
}

