/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRecipeDto
 */
export interface UpdateRecipeDto {
    /**
     * Recipe name
     */
    name?: string;
    /**
     * Internal recipe code
     */
    code?: string;
    /**
     * 
     */
    category?: string;
    /**
     * 
     */
    subcategory?: string;
    /**
     * How many portions this recipe yields. Defaults to 1.
     */
    yieldPortions?: number;
    /**
     * Unit the final yield is measured in when it isn't just portions (e.g. a sauce batch yields 'kg', not just N portions)
     */
    yieldFinalUnit?: string;
    /**
     * Extra percentage added on top of the summed ingredient cost, to cover unaccounted losses. Defaults to 0.
     */
    contingencyPct?: number;
    /**
     * Target food cost as a percentage of price. Defaults to 30.
     */
    targetFoodCostPct?: number;
    /**
     * Target margin as a percentage of price. Defaults to 70.
     */
    targetMarginPct?: number;
    /**
     * Manually fixed sale price, overriding target-based pricing
     */
    manualPrice?: number;
    /**
     * Prep time, in minutes
     */
    prepTimeMin?: number;
    /**
     * Cook time, in minutes
     */
    cookTimeMin?: number;
    /**
     * Labor cost per hour, for this recipe
     */
    laborHourlyCost?: number;
    /**
     * Number of people required to prep this recipe
     */
    laborPeople?: number;
    /**
     * Free-text prep steps
     */
    prepSteps?: string;
    /**
     * Free-text allergen list
     */
    allergens?: string;
    /**
     * ID of an existing item this recipe produces, belonging to the current tenant. When set, every production of this recipe also creates a stock_lot of this item (see POST /productions). Leave unset for a recipe that only consumes ingredients — the default, unchanged behavior.
     */
    producedItemId?: string;
}

/**
 * Check if a given object implements the UpdateRecipeDto interface.
 */
export function instanceOfUpdateRecipeDto(value: object): value is UpdateRecipeDto {
    return true;
}

export function UpdateRecipeDtoFromJSON(json: any): UpdateRecipeDto {
    return UpdateRecipeDtoFromJSONTyped(json, false);
}

export function UpdateRecipeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecipeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'category': json['category'] == null ? undefined : json['category'],
        'subcategory': json['subcategory'] == null ? undefined : json['subcategory'],
        'yieldPortions': json['yieldPortions'] == null ? undefined : json['yieldPortions'],
        'yieldFinalUnit': json['yieldFinalUnit'] == null ? undefined : json['yieldFinalUnit'],
        'contingencyPct': json['contingencyPct'] == null ? undefined : json['contingencyPct'],
        'targetFoodCostPct': json['targetFoodCostPct'] == null ? undefined : json['targetFoodCostPct'],
        'targetMarginPct': json['targetMarginPct'] == null ? undefined : json['targetMarginPct'],
        'manualPrice': json['manualPrice'] == null ? undefined : json['manualPrice'],
        'prepTimeMin': json['prepTimeMin'] == null ? undefined : json['prepTimeMin'],
        'cookTimeMin': json['cookTimeMin'] == null ? undefined : json['cookTimeMin'],
        'laborHourlyCost': json['laborHourlyCost'] == null ? undefined : json['laborHourlyCost'],
        'laborPeople': json['laborPeople'] == null ? undefined : json['laborPeople'],
        'prepSteps': json['prepSteps'] == null ? undefined : json['prepSteps'],
        'allergens': json['allergens'] == null ? undefined : json['allergens'],
        'producedItemId': json['producedItemId'] == null ? undefined : json['producedItemId'],
    };
}

export function UpdateRecipeDtoToJSON(json: any): UpdateRecipeDto {
    return UpdateRecipeDtoToJSONTyped(json, false);
}

export function UpdateRecipeDtoToJSONTyped(value?: UpdateRecipeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'code': value['code'],
        'category': value['category'],
        'subcategory': value['subcategory'],
        'yieldPortions': value['yieldPortions'],
        'yieldFinalUnit': value['yieldFinalUnit'],
        'contingencyPct': value['contingencyPct'],
        'targetFoodCostPct': value['targetFoodCostPct'],
        'targetMarginPct': value['targetMarginPct'],
        'manualPrice': value['manualPrice'],
        'prepTimeMin': value['prepTimeMin'],
        'cookTimeMin': value['cookTimeMin'],
        'laborHourlyCost': value['laborHourlyCost'],
        'laborPeople': value['laborPeople'],
        'prepSteps': value['prepSteps'],
        'allergens': value['allergens'],
        'producedItemId': value['producedItemId'],
    };
}

