/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrderLineDto
 */
export interface UpdateOrderLineDto {
    /**
     * 
     */
    quantity?: number;
    /**
     * 
     */
    supplierId?: string;
    /**
     * Manual checklist flag — no business logic attached to it
     */
    isChecked?: boolean;
}

/**
 * Check if a given object implements the UpdateOrderLineDto interface.
 */
export function instanceOfUpdateOrderLineDto(value: object): value is UpdateOrderLineDto {
    return true;
}

export function UpdateOrderLineDtoFromJSON(json: any): UpdateOrderLineDto {
    return UpdateOrderLineDtoFromJSONTyped(json, false);
}

export function UpdateOrderLineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderLineDto {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'isChecked': json['isChecked'] == null ? undefined : json['isChecked'],
    };
}

export function UpdateOrderLineDtoToJSON(json: any): UpdateOrderLineDto {
    return UpdateOrderLineDtoToJSONTyped(json, false);
}

export function UpdateOrderLineDtoToJSONTyped(value?: UpdateOrderLineDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'supplierId': value['supplierId'],
        'isChecked': value['isChecked'],
    };
}

