/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageCounterResponseDto
 */
export interface UsageCounterResponseDto {
    /**
     * 
     */
    counterKey: UsageCounterResponseDtoCounterKeyEnum;
    /**
     * First day of the calendar month this count covers (YYYY-MM-DD).
     */
    periodStart: string;
    /**
     * How many successful AI calls of this kind happened so far this period. 0 if unused — every known counterKey is always present in the response, not just the ones with activity.
     */
    count: number;
}


/**
 * @export
 */
export const UsageCounterResponseDtoCounterKeyEnum = {
    ReceiptScans: 'receipt_scans',
    RecipeScans: 'recipe_scans',
} as const;
export type UsageCounterResponseDtoCounterKeyEnum = typeof UsageCounterResponseDtoCounterKeyEnum[keyof typeof UsageCounterResponseDtoCounterKeyEnum];


/**
 * Check if a given object implements the UsageCounterResponseDto interface.
 */
export function instanceOfUsageCounterResponseDto(value: object): value is UsageCounterResponseDto {
    if (!('counterKey' in value) || value['counterKey'] === undefined) return false;
    if (!('periodStart' in value) || value['periodStart'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function UsageCounterResponseDtoFromJSON(json: any): UsageCounterResponseDto {
    return UsageCounterResponseDtoFromJSONTyped(json, false);
}

export function UsageCounterResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageCounterResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'counterKey': json['counterKey'],
        'periodStart': json['periodStart'],
        'count': json['count'],
    };
}

export function UsageCounterResponseDtoToJSON(json: any): UsageCounterResponseDto {
    return UsageCounterResponseDtoToJSONTyped(json, false);
}

export function UsageCounterResponseDtoToJSONTyped(value?: UsageCounterResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'counterKey': value['counterKey'],
        'periodStart': value['periodStart'],
        'count': value['count'],
    };
}

