/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyLoginCodeDto
 */
export interface VerifyLoginCodeDto {
    /**
     * Email of the account currently rejecting logins with ACCOUNT_LOCKED_VERIFY_EMAIL. This endpoint always responds the same way whether or not the email belongs to a real account — it never confirms or denies an email's existence.
     */
    email: string;
}

/**
 * Check if a given object implements the VerifyLoginCodeDto interface.
 */
export function instanceOfVerifyLoginCodeDto(value: object): value is VerifyLoginCodeDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VerifyLoginCodeDtoFromJSON(json: any): VerifyLoginCodeDto {
    return VerifyLoginCodeDtoFromJSONTyped(json, false);
}

export function VerifyLoginCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyLoginCodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function VerifyLoginCodeDtoToJSON(json: any): VerifyLoginCodeDto {
    return VerifyLoginCodeDtoToJSONTyped(json, false);
}

export function VerifyLoginCodeDtoToJSONTyped(value?: VerifyLoginCodeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

