/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WasteByItemResponseDto } from './WasteByItemResponseDto';
import {
    WasteByItemResponseDtoFromJSON,
    WasteByItemResponseDtoFromJSONTyped,
    WasteByItemResponseDtoToJSON,
    WasteByItemResponseDtoToJSONTyped,
} from './WasteByItemResponseDto';
import type { WasteByResponsibleResponseDto } from './WasteByResponsibleResponseDto';
import {
    WasteByResponsibleResponseDtoFromJSON,
    WasteByResponsibleResponseDtoFromJSONTyped,
    WasteByResponsibleResponseDtoToJSON,
    WasteByResponsibleResponseDtoToJSONTyped,
} from './WasteByResponsibleResponseDto';
import type { WasteByReasonResponseDto } from './WasteByReasonResponseDto';
import {
    WasteByReasonResponseDtoFromJSON,
    WasteByReasonResponseDtoFromJSONTyped,
    WasteByReasonResponseDtoToJSON,
    WasteByReasonResponseDtoToJSONTyped,
} from './WasteByReasonResponseDto';

/**
 * 
 * @export
 * @interface WasteAnalyticsResponseDto
 */
export interface WasteAnalyticsResponseDto {
    /**
     * Sum of costSnapshot across every matching CONFIRMED record
     */
    totalCost: number;
    /**
     * 
     */
    totalRecords: number;
    /**
     * 
     */
    byItem: Array<WasteByItemResponseDto>;
    /**
     * 
     */
    byReason: Array<WasteByReasonResponseDto>;
    /**
     * 
     */
    byResponsible: Array<WasteByResponsibleResponseDto>;
}

/**
 * Check if a given object implements the WasteAnalyticsResponseDto interface.
 */
export function instanceOfWasteAnalyticsResponseDto(value: object): value is WasteAnalyticsResponseDto {
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('totalRecords' in value) || value['totalRecords'] === undefined) return false;
    if (!('byItem' in value) || value['byItem'] === undefined) return false;
    if (!('byReason' in value) || value['byReason'] === undefined) return false;
    if (!('byResponsible' in value) || value['byResponsible'] === undefined) return false;
    return true;
}

export function WasteAnalyticsResponseDtoFromJSON(json: any): WasteAnalyticsResponseDto {
    return WasteAnalyticsResponseDtoFromJSONTyped(json, false);
}

export function WasteAnalyticsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WasteAnalyticsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCost': json['totalCost'],
        'totalRecords': json['totalRecords'],
        'byItem': ((json['byItem'] as Array<any>).map(WasteByItemResponseDtoFromJSON)),
        'byReason': ((json['byReason'] as Array<any>).map(WasteByReasonResponseDtoFromJSON)),
        'byResponsible': ((json['byResponsible'] as Array<any>).map(WasteByResponsibleResponseDtoFromJSON)),
    };
}

export function WasteAnalyticsResponseDtoToJSON(json: any): WasteAnalyticsResponseDto {
    return WasteAnalyticsResponseDtoToJSONTyped(json, false);
}

export function WasteAnalyticsResponseDtoToJSONTyped(value?: WasteAnalyticsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCost': value['totalCost'],
        'totalRecords': value['totalRecords'],
        'byItem': ((value['byItem'] as Array<any>).map(WasteByItemResponseDtoToJSON)),
        'byReason': ((value['byReason'] as Array<any>).map(WasteByReasonResponseDtoToJSON)),
        'byResponsible': ((value['byResponsible'] as Array<any>).map(WasteByResponsibleResponseDtoToJSON)),
    };
}

