/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface WasteResponseDto
 */
export interface WasteResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * Owning tenant ID
     */
    tenantId: string;
    /**
     * null when a voice/photo capture could not confidently match an item — must be resolved before this record can be confirmed
     */
    itemId?: object | null;
    /**
     * 
     */
    locationId: string;
    /**
     * 
     */
    quantity: number;
    /**
     * 
     */
    reason: WasteResponseDtoReasonEnum;
    /**
     * 
     */
    status: WasteResponseDtoStatusEnum;
    /**
     * 
     */
    sourceType: WasteResponseDtoSourceTypeEnum;
    /**
     * 
     */
    confidence: number;
    /**
     * 
     */
    rawText?: object | null;
    /**
     * Only set once CONFIRMED — quantity * the FIFO unit cost at confirmation time
     */
    costSnapshot?: object | null;
    /**
     * user_profiles.id of who reported this — always the creator
     */
    responsibleUserId?: object | null;
    /**
     * 
     */
    notes?: object | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    confirmedAt?: object | null;
}


/**
 * @export
 */
export const WasteResponseDtoReasonEnum = {
    MalEstado: 'Mal estado',
    Caducado: 'Caducado',
    Rotura: 'Rotura',
    ErrorDeProduccin: 'Error de producción',
    Quemado: 'Quemado',
    SobranteNoReutilizable: 'Sobrante no reutilizable',
    ContaminacinCruzada: 'Contaminación cruzada',
    DevolucinInterna: 'Devolución interna',
    PruebaTest: 'Prueba / test',
    Otro: 'Otro',
} as const;
export type WasteResponseDtoReasonEnum = typeof WasteResponseDtoReasonEnum[keyof typeof WasteResponseDtoReasonEnum];

/**
 * @export
 */
export const WasteResponseDtoStatusEnum = {
    Draft: 'DRAFT',
    Review: 'REVIEW',
    Confirmed: 'CONFIRMED',
    Cancelled: 'CANCELLED',
} as const;
export type WasteResponseDtoStatusEnum = typeof WasteResponseDtoStatusEnum[keyof typeof WasteResponseDtoStatusEnum];

/**
 * @export
 */
export const WasteResponseDtoSourceTypeEnum = {
    Manual: 'manual',
    Voice: 'voice',
    Photo: 'photo',
} as const;
export type WasteResponseDtoSourceTypeEnum = typeof WasteResponseDtoSourceTypeEnum[keyof typeof WasteResponseDtoSourceTypeEnum];


/**
 * Check if a given object implements the WasteResponseDto interface.
 */
export function instanceOfWasteResponseDto(value: object): value is WasteResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('locationId' in value) || value['locationId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WasteResponseDtoFromJSON(json: any): WasteResponseDto {
    return WasteResponseDtoFromJSONTyped(json, false);
}

export function WasteResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WasteResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tenantId': json['tenantId'],
        'itemId': json['itemId'] === undefined ? undefined : json['itemId'] === null ? null : json['itemId'],
        'locationId': json['locationId'],
        'quantity': json['quantity'],
        'reason': json['reason'],
        'status': json['status'],
        'sourceType': json['sourceType'],
        'confidence': json['confidence'],
        'rawText': json['rawText'] === undefined ? undefined : json['rawText'] === null ? null : json['rawText'],
        'costSnapshot': json['costSnapshot'] === undefined ? undefined : json['costSnapshot'] === null ? null : json['costSnapshot'],
        'responsibleUserId': json['responsibleUserId'] === undefined ? undefined : json['responsibleUserId'] === null ? null : json['responsibleUserId'],
        'notes': json['notes'] === undefined ? undefined : json['notes'] === null ? null : json['notes'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'confirmedAt': json['confirmedAt'] === undefined ? undefined : json['confirmedAt'] === null ? null : json['confirmedAt'],
    };
}

export function WasteResponseDtoToJSON(json: any): WasteResponseDto {
    return WasteResponseDtoToJSONTyped(json, false);
}

export function WasteResponseDtoToJSONTyped(value?: WasteResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenantId': value['tenantId'],
        'itemId': value['itemId'],
        'locationId': value['locationId'],
        'quantity': value['quantity'],
        'reason': value['reason'],
        'status': value['status'],
        'sourceType': value['sourceType'],
        'confidence': value['confidence'],
        'rawText': value['rawText'],
        'costSnapshot': value['costSnapshot'],
        'responsibleUserId': value['responsibleUserId'],
        'notes': value['notes'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'confirmedAt': value['confirmedAt'],
    };
}

