/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WasteByReasonResponseDto
 */
export interface WasteByReasonResponseDto {
    /**
     * 
     */
    reason: string;
    /**
     * 
     */
    totalCost: number;
    /**
     * 
     */
    recordCount: number;
}

/**
 * Check if a given object implements the WasteByReasonResponseDto interface.
 */
export function instanceOfWasteByReasonResponseDto(value: object): value is WasteByReasonResponseDto {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('recordCount' in value) || value['recordCount'] === undefined) return false;
    return true;
}

export function WasteByReasonResponseDtoFromJSON(json: any): WasteByReasonResponseDto {
    return WasteByReasonResponseDtoFromJSONTyped(json, false);
}

export function WasteByReasonResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WasteByReasonResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'totalCost': json['totalCost'],
        'recordCount': json['recordCount'],
    };
}

export function WasteByReasonResponseDtoToJSON(json: any): WasteByReasonResponseDto {
    return WasteByReasonResponseDtoToJSONTyped(json, false);
}

export function WasteByReasonResponseDtoToJSONTyped(value?: WasteByReasonResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'totalCost': value['totalCost'],
        'recordCount': value['recordCount'],
    };
}

