/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WasteByResponsibleResponseDto
 */
export interface WasteByResponsibleResponseDto {
    /**
     * 
     */
    responsibleUserId?: object | null;
    /**
     * 
     */
    totalCost: number;
    /**
     * 
     */
    recordCount: number;
}

/**
 * Check if a given object implements the WasteByResponsibleResponseDto interface.
 */
export function instanceOfWasteByResponsibleResponseDto(value: object): value is WasteByResponsibleResponseDto {
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('recordCount' in value) || value['recordCount'] === undefined) return false;
    return true;
}

export function WasteByResponsibleResponseDtoFromJSON(json: any): WasteByResponsibleResponseDto {
    return WasteByResponsibleResponseDtoFromJSONTyped(json, false);
}

export function WasteByResponsibleResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WasteByResponsibleResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'responsibleUserId': json['responsibleUserId'] === undefined ? undefined : json['responsibleUserId'] === null ? null : json['responsibleUserId'],
        'totalCost': json['totalCost'],
        'recordCount': json['recordCount'],
    };
}

export function WasteByResponsibleResponseDtoToJSON(json: any): WasteByResponsibleResponseDto {
    return WasteByResponsibleResponseDtoToJSONTyped(json, false);
}

export function WasteByResponsibleResponseDtoToJSONTyped(value?: WasteByResponsibleResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responsibleUserId': value['responsibleUserId'],
        'totalCost': value['totalCost'],
        'recordCount': value['recordCount'],
    };
}

