/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WasteByItemResponseDto
 */
export interface WasteByItemResponseDto {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    itemName: string;
    /**
     * 
     */
    totalCost: number;
    /**
     * 
     */
    totalQuantity: number;
    /**
     * 
     */
    recordCount: number;
}

/**
 * Check if a given object implements the WasteByItemResponseDto interface.
 */
export function instanceOfWasteByItemResponseDto(value: object): value is WasteByItemResponseDto {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('itemName' in value) || value['itemName'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('totalQuantity' in value) || value['totalQuantity'] === undefined) return false;
    if (!('recordCount' in value) || value['recordCount'] === undefined) return false;
    return true;
}

export function WasteByItemResponseDtoFromJSON(json: any): WasteByItemResponseDto {
    return WasteByItemResponseDtoFromJSONTyped(json, false);
}

export function WasteByItemResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WasteByItemResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'itemName': json['itemName'],
        'totalCost': json['totalCost'],
        'totalQuantity': json['totalQuantity'],
        'recordCount': json['recordCount'],
    };
}

export function WasteByItemResponseDtoToJSON(json: any): WasteByItemResponseDto {
    return WasteByItemResponseDtoToJSONTyped(json, false);
}

export function WasteByItemResponseDtoToJSONTyped(value?: WasteByItemResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'totalCost': value['totalCost'],
        'totalQuantity': value['totalQuantity'],
        'recordCount': value['recordCount'],
    };
}

