/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CompleteRegistrationDto,
    CompleteRegistrationDtoFromJSON,
    CompleteRegistrationDtoToJSON,
} from '../models/CompleteRegistrationDto';
import {
    type CompleteRegistrationResponseDto,
    CompleteRegistrationResponseDtoFromJSON,
    CompleteRegistrationResponseDtoToJSON,
} from '../models/CompleteRegistrationResponseDto';
import {
    type ConfirmLoginCodeDto,
    ConfirmLoginCodeDtoFromJSON,
    ConfirmLoginCodeDtoToJSON,
} from '../models/ConfirmLoginCodeDto';
import {
    type ConfirmLoginCodeResponseDto,
    ConfirmLoginCodeResponseDtoFromJSON,
    ConfirmLoginCodeResponseDtoToJSON,
} from '../models/ConfirmLoginCodeResponseDto';
import {
    type RegisterDto,
    RegisterDtoFromJSON,
    RegisterDtoToJSON,
} from '../models/RegisterDto';
import {
    type RegisterResponseDto,
    RegisterResponseDtoFromJSON,
    RegisterResponseDtoToJSON,
} from '../models/RegisterResponseDto';
import {
    type VerifyLoginCodeDto,
    VerifyLoginCodeDtoFromJSON,
    VerifyLoginCodeDtoToJSON,
} from '../models/VerifyLoginCodeDto';

export interface AuthControllerCompleteRegistrationRequest {
    /**
     * 
     */
    completeRegistrationDto: CompleteRegistrationDto;
}

export interface AuthControllerConfirmLoginCodeRequest {
    /**
     * 
     */
    confirmLoginCodeDto: ConfirmLoginCodeDto;
}

export interface AuthControllerRegisterRequest {
    /**
     * 
     */
    registerDto: RegisterDto;
}

export interface AuthControllerVerifyLoginCodeRequest {
    /**
     * 
     */
    verifyLoginCodeDto: VerifyLoginCodeDto;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authControllerCompleteRegistration without sending the request
     */
    async authControllerCompleteRegistrationRequestOpts(requestParameters: AuthControllerCompleteRegistrationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['completeRegistrationDto'] == null) {
            throw new runtime.RequiredError(
                'completeRegistrationDto',
                'Required parameter "completeRegistrationDto" was null or undefined when calling authControllerCompleteRegistration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/complete-registration`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteRegistrationDtoToJSON(requestParameters['completeRegistrationDto']),
        };
    }

    /**
     * Requires the access_token from POST /auth/register (or any valid token for a user without a tenant yet). Persists the terms_accepted_at/termsVersion that were captured in step one (carried in this token\'s app_metadata claim, not resent in this body — see CLAUDE.md), creates the tenant (owned by the calling user), activates planId immediately (no payment gate in this beta phase), and stamps trial_started_at. The response\'s requiresNewToken always being true is the important part for the frontend: the JWT used to call this endpoint keeps tenant_id absent even after this succeeds — request a new one (refresh-token grant or re-login) before relying on that claim.
     * Create the tenant and activate a plan (step 2 of 2)
     */
    async authControllerCompleteRegistrationRaw(requestParameters: AuthControllerCompleteRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompleteRegistrationResponseDto>> {
        const requestOptions = await this.authControllerCompleteRegistrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompleteRegistrationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Requires the access_token from POST /auth/register (or any valid token for a user without a tenant yet). Persists the terms_accepted_at/termsVersion that were captured in step one (carried in this token\'s app_metadata claim, not resent in this body — see CLAUDE.md), creates the tenant (owned by the calling user), activates planId immediately (no payment gate in this beta phase), and stamps trial_started_at. The response\'s requiresNewToken always being true is the important part for the frontend: the JWT used to call this endpoint keeps tenant_id absent even after this succeeds — request a new one (refresh-token grant or re-login) before relying on that claim.
     * Create the tenant and activate a plan (step 2 of 2)
     */
    async authControllerCompleteRegistration(requestParameters: AuthControllerCompleteRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompleteRegistrationResponseDto> {
        const response = await this.authControllerCompleteRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerConfirmLoginCode without sending the request
     */
    async authControllerConfirmLoginCodeRequestOpts(requestParameters: AuthControllerConfirmLoginCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['confirmLoginCodeDto'] == null) {
            throw new runtime.RequiredError(
                'confirmLoginCodeDto',
                'Required parameter "confirmLoginCodeDto" was null or undefined when calling authControllerConfirmLoginCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/confirm-login-code`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmLoginCodeDtoToJSON(requestParameters['confirmLoginCodeDto']),
        };
    }

    /**
     * Verifies the code against Supabase Auth (POST /auth/v1/verify, type=email) and, if valid, clears the account\'s failed-login lock (mixziapp.login_attempts.failed_count -> 0) so the next password attempt is no longer rejected. A valid code IS a real Supabase Auth sign-in under the hood, so the response is a full session — the client can use it directly instead of being forced to retry the password login a second time.
     * Confirm the code from POST /auth/verify-login-code
     */
    async authControllerConfirmLoginCodeRaw(requestParameters: AuthControllerConfirmLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmLoginCodeResponseDto>> {
        const requestOptions = await this.authControllerConfirmLoginCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmLoginCodeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Verifies the code against Supabase Auth (POST /auth/v1/verify, type=email) and, if valid, clears the account\'s failed-login lock (mixziapp.login_attempts.failed_count -> 0) so the next password attempt is no longer rejected. A valid code IS a real Supabase Auth sign-in under the hood, so the response is a full session — the client can use it directly instead of being forced to retry the password login a second time.
     * Confirm the code from POST /auth/verify-login-code
     */
    async authControllerConfirmLoginCode(requestParameters: AuthControllerConfirmLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmLoginCodeResponseDto> {
        const response = await this.authControllerConfirmLoginCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerRegister without sending the request
     */
    async authControllerRegisterRequestOpts(requestParameters: AuthControllerRegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerDto'] == null) {
            throw new runtime.RequiredError(
                'registerDto',
                'Required parameter "registerDto" was null or undefined when calling authControllerRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterDtoToJSON(requestParameters['registerDto']),
        };
    }

    /**
     * Creates the Auth user only — no tenant, no user_profiles row yet. Returns a session (access/refresh token) exactly like a normal login. The returned access_token has no tenant_id claim; call POST /auth/complete-registration next, then obtain a NEW token (see that endpoint) before the claim appears. termsAccepted/termsVersion are required here (this is where the UI shows the checkbox — personal data starts being processed at this step) but aren\'t persisted until complete-registration, since user_profiles doesn\'t exist yet; they travel via the JWT\'s app_metadata claim in the meantime (not user_metadata — that\'s user-editable and unsuitable for evidence, see CLAUDE.md).
     * Create a Supabase Auth account (step 1 of 2)
     */
    async authControllerRegisterRaw(requestParameters: AuthControllerRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterResponseDto>> {
        const requestOptions = await this.authControllerRegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates the Auth user only — no tenant, no user_profiles row yet. Returns a session (access/refresh token) exactly like a normal login. The returned access_token has no tenant_id claim; call POST /auth/complete-registration next, then obtain a NEW token (see that endpoint) before the claim appears. termsAccepted/termsVersion are required here (this is where the UI shows the checkbox — personal data starts being processed at this step) but aren\'t persisted until complete-registration, since user_profiles doesn\'t exist yet; they travel via the JWT\'s app_metadata claim in the meantime (not user_metadata — that\'s user-editable and unsuitable for evidence, see CLAUDE.md).
     * Create a Supabase Auth account (step 1 of 2)
     */
    async authControllerRegister(requestParameters: AuthControllerRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterResponseDto> {
        const response = await this.authControllerRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerVerifyLoginCode without sending the request
     */
    async authControllerVerifyLoginCodeRequestOpts(requestParameters: AuthControllerVerifyLoginCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyLoginCodeDto'] == null) {
            throw new runtime.RequiredError(
                'verifyLoginCodeDto',
                'Required parameter "verifyLoginCodeDto" was null or undefined when calling authControllerVerifyLoginCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/verify-login-code`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyLoginCodeDtoToJSON(requestParameters['verifyLoginCodeDto']),
        };
    }

    /**
     * Call this after a login attempt fails with GoTrue\'s ACCOUNT_LOCKED_VERIFY_EMAIL message (5 consecutive failed password attempts — see CLAUDE.md\'s Password Verification Attempt Hook design note). Triggers Supabase Auth\'s own Email OTP send (POST /auth/v1/otp under the hood) using the mailer already configured for the project. Always responds 200 with an empty body, whether or not the email belongs to a real account — this endpoint never confirms or denies that.
     * Send an email verification code to unlock a locked account
     */
    async authControllerVerifyLoginCodeRaw(requestParameters: AuthControllerVerifyLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.authControllerVerifyLoginCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Call this after a login attempt fails with GoTrue\'s ACCOUNT_LOCKED_VERIFY_EMAIL message (5 consecutive failed password attempts — see CLAUDE.md\'s Password Verification Attempt Hook design note). Triggers Supabase Auth\'s own Email OTP send (POST /auth/v1/otp under the hood) using the mailer already configured for the project. Always responds 200 with an empty body, whether or not the email belongs to a real account — this endpoint never confirms or denies that.
     * Send an email verification code to unlock a locked account
     */
    async authControllerVerifyLoginCode(requestParameters: AuthControllerVerifyLoginCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerVerifyLoginCodeRaw(requestParameters, initOverrides);
    }

}
