/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateItemDto,
    CreateItemDtoFromJSON,
    CreateItemDtoToJSON,
} from '../models/CreateItemDto';
import {
    type ItemResponseDto,
    ItemResponseDtoFromJSON,
    ItemResponseDtoToJSON,
} from '../models/ItemResponseDto';
import {
    type UpdateItemDto,
    UpdateItemDtoFromJSON,
    UpdateItemDtoToJSON,
} from '../models/UpdateItemDto';

export interface CatalogControllerCreateRequest {
    /**
     * 
     */
    createItemDto: CreateItemDto;
}

export interface CatalogControllerFindOneRequest {
    /**
     * Item ID
     */
    id: string;
}

export interface CatalogControllerRemoveRequest {
    /**
     * Item ID
     */
    id: string;
}

export interface CatalogControllerUpdateRequest {
    /**
     * Item ID
     */
    id: string;
    /**
     * 
     */
    updateItemDto: UpdateItemDto;
}

/**
 * 
 */
export class CatalogApi extends runtime.BaseAPI {

    /**
     * Creates request options for catalogControllerCreate without sending the request
     */
    async catalogControllerCreateRequestOpts(requestParameters: CatalogControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createItemDto'] == null) {
            throw new runtime.RequiredError(
                'createItemDto',
                'Required parameter "createItemDto" was null or undefined when calling catalogControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateItemDtoToJSON(requestParameters['createItemDto']),
        };
    }

    /**
     * Create an item in the current tenant\'s catalog
     */
    async catalogControllerCreateRaw(requestParameters: CatalogControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemResponseDto>> {
        const requestOptions = await this.catalogControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create an item in the current tenant\'s catalog
     */
    async catalogControllerCreate(requestParameters: CatalogControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemResponseDto> {
        const response = await this.catalogControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for catalogControllerFindAll without sending the request
     */
    async catalogControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns only active items (is_active = true) for the authenticated user\'s tenant.
     * List the current tenant\'s catalog items
     */
    async catalogControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItemResponseDto>>> {
        const requestOptions = await this.catalogControllerFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItemResponseDtoFromJSON));
    }

    /**
     * Returns only active items (is_active = true) for the authenticated user\'s tenant.
     * List the current tenant\'s catalog items
     */
    async catalogControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItemResponseDto>> {
        const response = await this.catalogControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for catalogControllerFindOne without sending the request
     */
    async catalogControllerFindOneRequestOpts(requestParameters: CatalogControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling catalogControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a catalog item by ID
     */
    async catalogControllerFindOneRaw(requestParameters: CatalogControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemResponseDto>> {
        const requestOptions = await this.catalogControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a catalog item by ID
     */
    async catalogControllerFindOne(requestParameters: CatalogControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemResponseDto> {
        const response = await this.catalogControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for catalogControllerRemove without sending the request
     */
    async catalogControllerRemoveRequestOpts(requestParameters: CatalogControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling catalogControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Not a physical DELETE: sets is_active = false. The item stops appearing in GET /catalog but still exists in the database.
     * Deactivate a catalog item (soft delete)
     */
    async catalogControllerRemoveRaw(requestParameters: CatalogControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemResponseDto>> {
        const requestOptions = await this.catalogControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemResponseDtoFromJSON(jsonValue));
    }

    /**
     * Not a physical DELETE: sets is_active = false. The item stops appearing in GET /catalog but still exists in the database.
     * Deactivate a catalog item (soft delete)
     */
    async catalogControllerRemove(requestParameters: CatalogControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemResponseDto> {
        const response = await this.catalogControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for catalogControllerUpdate without sending the request
     */
    async catalogControllerUpdateRequestOpts(requestParameters: CatalogControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling catalogControllerUpdate().'
            );
        }

        if (requestParameters['updateItemDto'] == null) {
            throw new runtime.RequiredError(
                'updateItemDto',
                'Required parameter "updateItemDto" was null or undefined when calling catalogControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateItemDtoToJSON(requestParameters['updateItemDto']),
        };
    }

    /**
     * Edit fields of a catalog item
     */
    async catalogControllerUpdateRaw(requestParameters: CatalogControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ItemResponseDto>> {
        const requestOptions = await this.catalogControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemResponseDtoFromJSON(jsonValue));
    }

    /**
     * Edit fields of a catalog item
     */
    async catalogControllerUpdate(requestParameters: CatalogControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ItemResponseDto> {
        const response = await this.catalogControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
