/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateLocationDto,
    CreateLocationDtoFromJSON,
    CreateLocationDtoToJSON,
} from '../models/CreateLocationDto';
import {
    type LocationResponseDto,
    LocationResponseDtoFromJSON,
    LocationResponseDtoToJSON,
} from '../models/LocationResponseDto';
import {
    type UpdateLocationDto,
    UpdateLocationDtoFromJSON,
    UpdateLocationDtoToJSON,
} from '../models/UpdateLocationDto';

export interface LocationsControllerCreateRequest {
    /**
     * 
     */
    createLocationDto: CreateLocationDto;
}

export interface LocationsControllerFindOneRequest {
    /**
     * Location ID
     */
    id: string;
}

export interface LocationsControllerRemoveRequest {
    /**
     * Location ID
     */
    id: string;
}

export interface LocationsControllerUpdateRequest {
    /**
     * Location ID
     */
    id: string;
    /**
     * 
     */
    updateLocationDto: UpdateLocationDto;
}

/**
 * 
 */
export class LocationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for locationsControllerCreate without sending the request
     */
    async locationsControllerCreateRequestOpts(requestParameters: LocationsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createLocationDto'] == null) {
            throw new runtime.RequiredError(
                'createLocationDto',
                'Required parameter "createLocationDto" was null or undefined when calling locationsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/locations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLocationDtoToJSON(requestParameters['createLocationDto']),
        };
    }

    /**
     * Create a location for the current tenant
     */
    async locationsControllerCreateRaw(requestParameters: LocationsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationResponseDto>> {
        const requestOptions = await this.locationsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a location for the current tenant
     */
    async locationsControllerCreate(requestParameters: LocationsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationResponseDto> {
        const response = await this.locationsControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for locationsControllerFindAll without sending the request
     */
    async locationsControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/locations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns only active locations (is_active = true) for the authenticated user\'s tenant.
     * List the current tenant\'s locations
     */
    async locationsControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LocationResponseDto>>> {
        const requestOptions = await this.locationsControllerFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LocationResponseDtoFromJSON));
    }

    /**
     * Returns only active locations (is_active = true) for the authenticated user\'s tenant.
     * List the current tenant\'s locations
     */
    async locationsControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LocationResponseDto>> {
        const response = await this.locationsControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for locationsControllerFindOne without sending the request
     */
    async locationsControllerFindOneRequestOpts(requestParameters: LocationsControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling locationsControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/locations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a location by ID
     */
    async locationsControllerFindOneRaw(requestParameters: LocationsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationResponseDto>> {
        const requestOptions = await this.locationsControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a location by ID
     */
    async locationsControllerFindOne(requestParameters: LocationsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationResponseDto> {
        const response = await this.locationsControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for locationsControllerRemove without sending the request
     */
    async locationsControllerRemoveRequestOpts(requestParameters: LocationsControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling locationsControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/locations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Not a physical DELETE: sets is_active = false. Existing stock_lots rows at this location are left untouched.
     * Deactivate a location (soft delete)
     */
    async locationsControllerRemoveRaw(requestParameters: LocationsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationResponseDto>> {
        const requestOptions = await this.locationsControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Not a physical DELETE: sets is_active = false. Existing stock_lots rows at this location are left untouched.
     * Deactivate a location (soft delete)
     */
    async locationsControllerRemove(requestParameters: LocationsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationResponseDto> {
        const response = await this.locationsControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for locationsControllerUpdate without sending the request
     */
    async locationsControllerUpdateRequestOpts(requestParameters: LocationsControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling locationsControllerUpdate().'
            );
        }

        if (requestParameters['updateLocationDto'] == null) {
            throw new runtime.RequiredError(
                'updateLocationDto',
                'Required parameter "updateLocationDto" was null or undefined when calling locationsControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/locations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateLocationDtoToJSON(requestParameters['updateLocationDto']),
        };
    }

    /**
     * Edit fields of a location
     */
    async locationsControllerUpdateRaw(requestParameters: LocationsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationResponseDto>> {
        const requestOptions = await this.locationsControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Edit fields of a location
     */
    async locationsControllerUpdate(requestParameters: LocationsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationResponseDto> {
        const response = await this.locationsControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
