/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateOrderDto,
    CreateOrderDtoFromJSON,
    CreateOrderDtoToJSON,
} from '../models/CreateOrderDto';
import {
    type CreateOrderLineDto,
    CreateOrderLineDtoFromJSON,
    CreateOrderLineDtoToJSON,
} from '../models/CreateOrderLineDto';
import {
    type OrderDetailResponseDto,
    OrderDetailResponseDtoFromJSON,
    OrderDetailResponseDtoToJSON,
} from '../models/OrderDetailResponseDto';
import {
    type OrderLineResponseDto,
    OrderLineResponseDtoFromJSON,
    OrderLineResponseDtoToJSON,
} from '../models/OrderLineResponseDto';
import {
    type OrderResponseDto,
    OrderResponseDtoFromJSON,
    OrderResponseDtoToJSON,
} from '../models/OrderResponseDto';
import {
    type OrderSuggestionResponseDto,
    OrderSuggestionResponseDtoFromJSON,
    OrderSuggestionResponseDtoToJSON,
} from '../models/OrderSuggestionResponseDto';
import {
    type UpdateOrderLineDto,
    UpdateOrderLineDtoFromJSON,
    UpdateOrderLineDtoToJSON,
} from '../models/UpdateOrderLineDto';

export interface OrdersControllerAddLineRequest {
    /**
     * Order ID
     */
    id: string;
    /**
     * 
     */
    createOrderLineDto: CreateOrderLineDto;
}

export interface OrdersControllerArchiveRequest {
    /**
     * Order ID
     */
    id: string;
}

export interface OrdersControllerConfirmRequest {
    /**
     * Order ID
     */
    id: string;
}

export interface OrdersControllerCreateRequest {
    /**
     * 
     */
    createOrderDto: CreateOrderDto;
}

export interface OrdersControllerFindAllRequest {
    /**
     * 
     */
    status?: OrdersControllerFindAllStatusEnum;
    /**
     * 
     */
    locationId?: string;
}

export interface OrdersControllerFindOneRequest {
    /**
     * Order ID
     */
    id: string;
}

export interface OrdersControllerGetSuggestionsRequest {
    /**
     * Location whose stock to check against min/max thresholds
     */
    locationId: string;
}

export interface OrdersControllerRemoveRequest {
    /**
     * Order ID
     */
    id: string;
}

export interface OrdersControllerRemoveLineRequest {
    /**
     * Order ID
     */
    id: string;
    /**
     * Order line ID
     */
    lineId: string;
}

export interface OrdersControllerReopenRequest {
    /**
     * Order ID
     */
    id: string;
}

export interface OrdersControllerRestoreRequest {
    /**
     * Order ID
     */
    id: string;
}

export interface OrdersControllerUpdateLineRequest {
    /**
     * Order ID
     */
    id: string;
    /**
     * Order line ID
     */
    lineId: string;
    /**
     * 
     */
    updateOrderLineDto: UpdateOrderLineDto;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for ordersControllerAddLine without sending the request
     */
    async ordersControllerAddLineRequestOpts(requestParameters: OrdersControllerAddLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerAddLine().'
            );
        }

        if (requestParameters['createOrderLineDto'] == null) {
            throw new runtime.RequiredError(
                'createOrderLineDto',
                'Required parameter "createOrderLineDto" was null or undefined when calling ordersControllerAddLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/lines`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrderLineDtoToJSON(requestParameters['createOrderLineDto']),
        };
    }

    /**
     * Not allowed once the order is CONFIRMED or ARCHIVED.
     * Add a line to a DRAFT order
     */
    async ordersControllerAddLineRaw(requestParameters: OrdersControllerAddLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderLineResponseDto>> {
        const requestOptions = await this.ordersControllerAddLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * Not allowed once the order is CONFIRMED or ARCHIVED.
     * Add a line to a DRAFT order
     */
    async ordersControllerAddLine(requestParameters: OrdersControllerAddLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderLineResponseDto> {
        const response = await this.ordersControllerAddLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerArchive without sending the request
     */
    async ordersControllerArchiveRequestOpts(requestParameters: OrdersControllerArchiveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerArchive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/archive`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * CONFIRMED -> ARCHIVED only.
     * Archive an order
     */
    async ordersControllerArchiveRaw(requestParameters: OrdersControllerArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderResponseDto>> {
        const requestOptions = await this.ordersControllerArchiveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderResponseDtoFromJSON(jsonValue));
    }

    /**
     * CONFIRMED -> ARCHIVED only.
     * Archive an order
     */
    async ordersControllerArchive(requestParameters: OrdersControllerArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderResponseDto> {
        const response = await this.ordersControllerArchiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerConfirm without sending the request
     */
    async ordersControllerConfirmRequestOpts(requestParameters: OrdersControllerConfirmRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerConfirm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/confirm`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * DRAFT -> CONFIRMED. Freezes the lines (no more edits) and has no effect on stock whatsoever — only a future Receipts module moves stock.
     * Confirm an order
     */
    async ordersControllerConfirmRaw(requestParameters: OrdersControllerConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderResponseDto>> {
        const requestOptions = await this.ordersControllerConfirmRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderResponseDtoFromJSON(jsonValue));
    }

    /**
     * DRAFT -> CONFIRMED. Freezes the lines (no more edits) and has no effect on stock whatsoever — only a future Receipts module moves stock.
     * Confirm an order
     */
    async ordersControllerConfirm(requestParameters: OrdersControllerConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderResponseDto> {
        const response = await this.ordersControllerConfirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerCreate without sending the request
     */
    async ordersControllerCreateRequestOpts(requestParameters: OrdersControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOrderDto'] == null) {
            throw new runtime.RequiredError(
                'createOrderDto',
                'Required parameter "createOrderDto" was null or undefined when calling ordersControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrderDtoToJSON(requestParameters['createOrderDto']),
        };
    }

    /**
     * Always starts as DRAFT — add lines afterward via POST /orders/:id/lines.
     * Create a new order
     */
    async ordersControllerCreateRaw(requestParameters: OrdersControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderResponseDto>> {
        const requestOptions = await this.ordersControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderResponseDtoFromJSON(jsonValue));
    }

    /**
     * Always starts as DRAFT — add lines afterward via POST /orders/:id/lines.
     * Create a new order
     */
    async ordersControllerCreate(requestParameters: OrdersControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderResponseDto> {
        const response = await this.ordersControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerFindAll without sending the request
     */
    async ordersControllerFindAllRequestOpts(requestParameters: OrdersControllerFindAllRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Optionally filtered by status and/or locationId. Newest first.
     * List the current tenant\'s orders
     */
    async ordersControllerFindAllRaw(requestParameters: OrdersControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderResponseDto>>> {
        const requestOptions = await this.ordersControllerFindAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderResponseDtoFromJSON));
    }

    /**
     * Optionally filtered by status and/or locationId. Newest first.
     * List the current tenant\'s orders
     */
    async ordersControllerFindAll(requestParameters: OrdersControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderResponseDto>> {
        const response = await this.ordersControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerFindOne without sending the request
     */
    async ordersControllerFindOneRequestOpts(requestParameters: OrdersControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an order by ID, including its lines
     */
    async ordersControllerFindOneRaw(requestParameters: OrdersControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDetailResponseDto>> {
        const requestOptions = await this.ordersControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDetailResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get an order by ID, including its lines
     */
    async ordersControllerFindOne(requestParameters: OrdersControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDetailResponseDto> {
        const response = await this.ordersControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerGetSuggestions without sending the request
     */
    async ordersControllerGetSuggestionsRequestOpts(requestParameters: OrdersControllerGetSuggestionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError(
                'locationId',
                'Required parameter "locationId" was null or undefined when calling ordersControllerGetSuggestions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/suggestions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read-only — creates nothing. For every active item with both minStock and maxStock set, if the current stock at locationId is below minStock, suggests maxStock - currentStock. Items missing either threshold never appear here.
     * Suggest order quantities based on min/max stock thresholds
     */
    async ordersControllerGetSuggestionsRaw(requestParameters: OrdersControllerGetSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderSuggestionResponseDto>>> {
        const requestOptions = await this.ordersControllerGetSuggestionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderSuggestionResponseDtoFromJSON));
    }

    /**
     * Read-only — creates nothing. For every active item with both minStock and maxStock set, if the current stock at locationId is below minStock, suggests maxStock - currentStock. Items missing either threshold never appear here.
     * Suggest order quantities based on min/max stock thresholds
     */
    async ordersControllerGetSuggestions(requestParameters: OrdersControllerGetSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderSuggestionResponseDto>> {
        const response = await this.ordersControllerGetSuggestionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerRemove without sending the request
     */
    async ordersControllerRemoveRequestOpts(requestParameters: OrdersControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Physical delete of the order and its lines (order_lines cascade). Only allowed from DRAFT — a CONFIRMED or ARCHIVED order is a record of intent, not an abandoned draft.
     * Delete a DRAFT order
     */
    async ordersControllerRemoveRaw(requestParameters: OrdersControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderResponseDto>> {
        const requestOptions = await this.ordersControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderResponseDtoFromJSON(jsonValue));
    }

    /**
     * Physical delete of the order and its lines (order_lines cascade). Only allowed from DRAFT — a CONFIRMED or ARCHIVED order is a record of intent, not an abandoned draft.
     * Delete a DRAFT order
     */
    async ordersControllerRemove(requestParameters: OrdersControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderResponseDto> {
        const response = await this.ordersControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerRemoveLine without sending the request
     */
    async ordersControllerRemoveLineRequestOpts(requestParameters: OrdersControllerRemoveLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerRemoveLine().'
            );
        }

        if (requestParameters['lineId'] == null) {
            throw new runtime.RequiredError(
                'lineId',
                'Required parameter "lineId" was null or undefined when calling ordersControllerRemoveLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/lines/{lineId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{lineId}', encodeURIComponent(String(requestParameters['lineId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Not allowed once the order is CONFIRMED or ARCHIVED.
     * Remove a line from a DRAFT order
     */
    async ordersControllerRemoveLineRaw(requestParameters: OrdersControllerRemoveLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderLineResponseDto>> {
        const requestOptions = await this.ordersControllerRemoveLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * Not allowed once the order is CONFIRMED or ARCHIVED.
     * Remove a line from a DRAFT order
     */
    async ordersControllerRemoveLine(requestParameters: OrdersControllerRemoveLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderLineResponseDto> {
        const response = await this.ordersControllerRemoveLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerReopen without sending the request
     */
    async ordersControllerReopenRequestOpts(requestParameters: OrdersControllerReopenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerReopen().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/reopen`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * CONFIRMED -> DRAFT, unlocking its lines again — the inverse of confirm. Distinct from restore (see below): this order was never archived.
     * Reopen a confirmed order for editing
     */
    async ordersControllerReopenRaw(requestParameters: OrdersControllerReopenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderResponseDto>> {
        const requestOptions = await this.ordersControllerReopenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderResponseDtoFromJSON(jsonValue));
    }

    /**
     * CONFIRMED -> DRAFT, unlocking its lines again — the inverse of confirm. Distinct from restore (see below): this order was never archived.
     * Reopen a confirmed order for editing
     */
    async ordersControllerReopen(requestParameters: OrdersControllerReopenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderResponseDto> {
        const response = await this.ordersControllerReopenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerRestore without sending the request
     */
    async ordersControllerRestoreRequestOpts(requestParameters: OrdersControllerRestoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerRestore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/restore`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ARCHIVED -> CONFIRMED — the inverse of archive.
     * Restore an archived order
     */
    async ordersControllerRestoreRaw(requestParameters: OrdersControllerRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderResponseDto>> {
        const requestOptions = await this.ordersControllerRestoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderResponseDtoFromJSON(jsonValue));
    }

    /**
     * ARCHIVED -> CONFIRMED — the inverse of archive.
     * Restore an archived order
     */
    async ordersControllerRestore(requestParameters: OrdersControllerRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderResponseDto> {
        const response = await this.ordersControllerRestoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ordersControllerUpdateLine without sending the request
     */
    async ordersControllerUpdateLineRequestOpts(requestParameters: OrdersControllerUpdateLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ordersControllerUpdateLine().'
            );
        }

        if (requestParameters['lineId'] == null) {
            throw new runtime.RequiredError(
                'lineId',
                'Required parameter "lineId" was null or undefined when calling ordersControllerUpdateLine().'
            );
        }

        if (requestParameters['updateOrderLineDto'] == null) {
            throw new runtime.RequiredError(
                'updateOrderLineDto',
                'Required parameter "updateOrderLineDto" was null or undefined when calling ordersControllerUpdateLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders/{id}/lines/{lineId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{lineId}', encodeURIComponent(String(requestParameters['lineId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrderLineDtoToJSON(requestParameters['updateOrderLineDto']),
        };
    }

    /**
     * quantity, supplierId, and/or isChecked. Not allowed once the order is CONFIRMED or ARCHIVED. Cannot move the line to a different item — remove and re-add instead.
     * Update a line of a DRAFT order
     */
    async ordersControllerUpdateLineRaw(requestParameters: OrdersControllerUpdateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderLineResponseDto>> {
        const requestOptions = await this.ordersControllerUpdateLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * quantity, supplierId, and/or isChecked. Not allowed once the order is CONFIRMED or ARCHIVED. Cannot move the line to a different item — remove and re-add instead.
     * Update a line of a DRAFT order
     */
    async ordersControllerUpdateLine(requestParameters: OrdersControllerUpdateLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderLineResponseDto> {
        const response = await this.ordersControllerUpdateLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const OrdersControllerFindAllStatusEnum = {
    Draft: 'DRAFT',
    Confirmed: 'CONFIRMED',
    Archived: 'ARCHIVED',
} as const;
export type OrdersControllerFindAllStatusEnum = typeof OrdersControllerFindAllStatusEnum[keyof typeof OrdersControllerFindAllStatusEnum];
