/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateProductionDto,
    CreateProductionDtoFromJSON,
    CreateProductionDtoToJSON,
} from '../models/CreateProductionDto';
import {
    type ProductionResponseDto,
    ProductionResponseDtoFromJSON,
    ProductionResponseDtoToJSON,
} from '../models/ProductionResponseDto';

export interface ProductionsControllerCreateRequest {
    /**
     * 
     */
    createProductionDto: CreateProductionDto;
}

export interface ProductionsControllerFindAllRequest {
    /**
     * Filter to productions of this recipe
     */
    recipeId?: string;
    /**
     * Filter to productions at this location
     */
    locationId?: string;
}

export interface ProductionsControllerFindOneRequest {
    /**
     * Production ID
     */
    id: string;
}

/**
 * 
 */
export class ProductionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for productionsControllerCreate without sending the request
     */
    async productionsControllerCreateRequestOpts(requestParameters: ProductionsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createProductionDto'] == null) {
            throw new runtime.RequiredError(
                'createProductionDto',
                'Required parameter "createProductionDto" was null or undefined when calling productionsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/productions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductionDtoToJSON(requestParameters['createProductionDto']),
        };
    }

    /**
     * Freezes the recipe\'s current cost (same calculation as GET /recipes/:id/cost) into costSnapshot, then consumes every ingredient\'s stock via FIFO — all inside one transaction: if any ingredient can\'t be fully consumed, nothing is consumed and no production is created.
     * Record a production, consuming ingredient stock
     */
    async productionsControllerCreateRaw(requestParameters: ProductionsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionResponseDto>> {
        const requestOptions = await this.productionsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Freezes the recipe\'s current cost (same calculation as GET /recipes/:id/cost) into costSnapshot, then consumes every ingredient\'s stock via FIFO — all inside one transaction: if any ingredient can\'t be fully consumed, nothing is consumed and no production is created.
     * Record a production, consuming ingredient stock
     */
    async productionsControllerCreate(requestParameters: ProductionsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionResponseDto> {
        const response = await this.productionsControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productionsControllerFindAll without sending the request
     */
    async productionsControllerFindAllRequestOpts(requestParameters: ProductionsControllerFindAllRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['recipeId'] != null) {
            queryParameters['recipeId'] = requestParameters['recipeId'];
        }

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/productions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Optionally filtered by recipeId and/or locationId. Newest first.
     * List the current tenant\'s productions
     */
    async productionsControllerFindAllRaw(requestParameters: ProductionsControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductionResponseDto>>> {
        const requestOptions = await this.productionsControllerFindAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductionResponseDtoFromJSON));
    }

    /**
     * Optionally filtered by recipeId and/or locationId. Newest first.
     * List the current tenant\'s productions
     */
    async productionsControllerFindAll(requestParameters: ProductionsControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductionResponseDto>> {
        const response = await this.productionsControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for productionsControllerFindOne without sending the request
     */
    async productionsControllerFindOneRequestOpts(requestParameters: ProductionsControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling productionsControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/productions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a production by ID
     */
    async productionsControllerFindOneRaw(requestParameters: ProductionsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionResponseDto>> {
        const requestOptions = await this.productionsControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a production by ID
     */
    async productionsControllerFindOne(requestParameters: ProductionsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionResponseDto> {
        const response = await this.productionsControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
