/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptExtractionLineDto,
    AcceptExtractionLineDtoFromJSON,
    AcceptExtractionLineDtoToJSON,
} from '../models/AcceptExtractionLineDto';
import {
    type ReceiptExtractionLineResponseDto,
    ReceiptExtractionLineResponseDtoFromJSON,
    ReceiptExtractionLineResponseDtoToJSON,
} from '../models/ReceiptExtractionLineResponseDto';
import {
    type ReceiptExtractionRunResponseDto,
    ReceiptExtractionRunResponseDtoFromJSON,
    ReceiptExtractionRunResponseDtoToJSON,
} from '../models/ReceiptExtractionRunResponseDto';
import {
    type ReceiptLineResponseDto,
    ReceiptLineResponseDtoFromJSON,
    ReceiptLineResponseDtoToJSON,
} from '../models/ReceiptLineResponseDto';

export interface ReceiptsControllerAcceptLineRequest {
    /**
     * Receipt ID
     */
    id: string;
    /**
     * Receipt extraction line ID
     */
    extractionLineId: string;
    /**
     * 
     */
    acceptExtractionLineDto: AcceptExtractionLineDto;
}

export interface ReceiptsControllerExtractRequest {
    /**
     * Receipt ID
     */
    id: string;
    /**
     * 
     */
    file: Blob;
}

export interface ReceiptsControllerRejectLineRequest {
    /**
     * Receipt ID
     */
    id: string;
    /**
     * Receipt extraction line ID
     */
    extractionLineId: string;
}

/**
 * 
 */
export class ReceiptsScanningApi extends runtime.BaseAPI {

    /**
     * Creates request options for receiptsControllerAcceptLine without sending the request
     */
    async receiptsControllerAcceptLineRequestOpts(requestParameters: ReceiptsControllerAcceptLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerAcceptLine().'
            );
        }

        if (requestParameters['extractionLineId'] == null) {
            throw new runtime.RequiredError(
                'extractionLineId',
                'Required parameter "extractionLineId" was null or undefined when calling receiptsControllerAcceptLine().'
            );
        }

        if (requestParameters['acceptExtractionLineDto'] == null) {
            throw new runtime.RequiredError(
                'acceptExtractionLineDto',
                'Required parameter "acceptExtractionLineDto" was null or undefined when calling receiptsControllerAcceptLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}/lines/{extractionLineId}/accept`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{extractionLineId}', encodeURIComponent(String(requestParameters['extractionLineId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptExtractionLineDtoToJSON(requestParameters['acceptExtractionLineDto']),
        };
    }

    /**
     * Resolves the item via itemId (existing) or createNewItem + newItem (opt-in creation, never automatic — same as the legacy). quantity/unitPrice can be edited from what was extracted.
     * Accept a proposed extraction line, creating a real receipt line
     */
    async receiptsControllerAcceptLineRaw(requestParameters: ReceiptsControllerAcceptLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptLineResponseDto>> {
        const requestOptions = await this.receiptsControllerAcceptLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * Resolves the item via itemId (existing) or createNewItem + newItem (opt-in creation, never automatic — same as the legacy). quantity/unitPrice can be edited from what was extracted.
     * Accept a proposed extraction line, creating a real receipt line
     */
    async receiptsControllerAcceptLine(requestParameters: ReceiptsControllerAcceptLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptLineResponseDto> {
        const response = await this.receiptsControllerAcceptLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerExtract without sending the request
     */
    async receiptsControllerExtractRequestOpts(requestParameters: ReceiptsControllerExtractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerExtract().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling receiptsControllerExtract().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/receipts/{id}/extract`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Uploads via the generic Document Extraction service, then creates a new extraction run with its proposed lines (all starting reviewStatus=PENDING). Only allowed while the receipt is PENDING. Can be called again (e.g. with a clearer photo) — each call creates a new run.
     * Upload the delivery-note image and run AI extraction
     */
    async receiptsControllerExtractRaw(requestParameters: ReceiptsControllerExtractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptExtractionRunResponseDto>> {
        const requestOptions = await this.receiptsControllerExtractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptExtractionRunResponseDtoFromJSON(jsonValue));
    }

    /**
     * Uploads via the generic Document Extraction service, then creates a new extraction run with its proposed lines (all starting reviewStatus=PENDING). Only allowed while the receipt is PENDING. Can be called again (e.g. with a clearer photo) — each call creates a new run.
     * Upload the delivery-note image and run AI extraction
     */
    async receiptsControllerExtract(requestParameters: ReceiptsControllerExtractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptExtractionRunResponseDto> {
        const response = await this.receiptsControllerExtractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerRejectLine without sending the request
     */
    async receiptsControllerRejectLineRequestOpts(requestParameters: ReceiptsControllerRejectLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerRejectLine().'
            );
        }

        if (requestParameters['extractionLineId'] == null) {
            throw new runtime.RequiredError(
                'extractionLineId',
                'Required parameter "extractionLineId" was null or undefined when calling receiptsControllerRejectLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}/lines/{extractionLineId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{extractionLineId}', encodeURIComponent(String(requestParameters['extractionLineId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sets reviewStatus=REJECTED — the row stays as a record of what was proposed and dismissed.
     * Discard a proposed extraction line without accepting it
     */
    async receiptsControllerRejectLineRaw(requestParameters: ReceiptsControllerRejectLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptExtractionLineResponseDto>> {
        const requestOptions = await this.receiptsControllerRejectLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptExtractionLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * Sets reviewStatus=REJECTED — the row stays as a record of what was proposed and dismissed.
     * Discard a proposed extraction line without accepting it
     */
    async receiptsControllerRejectLine(requestParameters: ReceiptsControllerRejectLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptExtractionLineResponseDto> {
        const response = await this.receiptsControllerRejectLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
