/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateReceiptDto,
    CreateReceiptDtoFromJSON,
    CreateReceiptDtoToJSON,
} from '../models/CreateReceiptDto';
import {
    type ReceiptDetailResponseDto,
    ReceiptDetailResponseDtoFromJSON,
    ReceiptDetailResponseDtoToJSON,
} from '../models/ReceiptDetailResponseDto';
import {
    type ReceiptResponseDto,
    ReceiptResponseDtoFromJSON,
    ReceiptResponseDtoToJSON,
} from '../models/ReceiptResponseDto';
import {
    type UpdateReceiptDto,
    UpdateReceiptDtoFromJSON,
    UpdateReceiptDtoToJSON,
} from '../models/UpdateReceiptDto';

export interface ReceiptsControllerArchiveRequest {
    /**
     * Receipt ID
     */
    id: string;
}

export interface ReceiptsControllerCancelRequest {
    /**
     * Receipt ID
     */
    id: string;
}

export interface ReceiptsControllerConfirmRequest {
    /**
     * Receipt ID
     */
    id: string;
}

export interface ReceiptsControllerCreateRequest {
    /**
     * 
     */
    createReceiptDto: CreateReceiptDto;
}

export interface ReceiptsControllerFindAllRequest {
    /**
     * 
     */
    status?: ReceiptsControllerFindAllStatusEnum;
    /**
     * 
     */
    locationId?: string;
}

export interface ReceiptsControllerFindOneRequest {
    /**
     * Receipt ID
     */
    id: string;
}

export interface ReceiptsControllerRemoveRequest {
    /**
     * Receipt ID
     */
    id: string;
}

export interface ReceiptsControllerRestoreRequest {
    /**
     * Receipt ID
     */
    id: string;
}

export interface ReceiptsControllerUpdateRequest {
    /**
     * Receipt ID
     */
    id: string;
    /**
     * 
     */
    updateReceiptDto: UpdateReceiptDto;
}

/**
 * 
 */
export class ReceiptsApi extends runtime.BaseAPI {

    /**
     * Creates request options for receiptsControllerArchive without sending the request
     */
    async receiptsControllerArchiveRequestOpts(requestParameters: ReceiptsControllerArchiveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerArchive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}/archive`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * CONFIRMED -> ARCHIVED only.
     * Archive a receipt
     */
    async receiptsControllerArchiveRaw(requestParameters: ReceiptsControllerArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerArchiveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * CONFIRMED -> ARCHIVED only.
     * Archive a receipt
     */
    async receiptsControllerArchive(requestParameters: ReceiptsControllerArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerArchiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerCancel without sending the request
     */
    async receiptsControllerCancelRequestOpts(requestParameters: ReceiptsControllerCancelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * PENDING -> CANCELED only. No stock effect — nothing was ever confirmed.
     * Cancel a receipt
     */
    async receiptsControllerCancelRaw(requestParameters: ReceiptsControllerCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerCancelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * PENDING -> CANCELED only. No stock effect — nothing was ever confirmed.
     * Cancel a receipt
     */
    async receiptsControllerCancel(requestParameters: ReceiptsControllerCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerCancelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerConfirm without sending the request
     */
    async receiptsControllerConfirmRequestOpts(requestParameters: ReceiptsControllerConfirmRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerConfirm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}/confirm`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * PENDING -> CONFIRMED. Requires at least one accepted line, all with a unitPrice, and a resolved supplierId. Atomically: creates a stock_lot per line and upserts each item\'s supplier_item_prices row (preserving isPreferred). Never touches items — no current_price column exists in this schema.
     * Confirm a receipt, generating stock
     */
    async receiptsControllerConfirmRaw(requestParameters: ReceiptsControllerConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerConfirmRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * PENDING -> CONFIRMED. Requires at least one accepted line, all with a unitPrice, and a resolved supplierId. Atomically: creates a stock_lot per line and upserts each item\'s supplier_item_prices row (preserving isPreferred). Never touches items — no current_price column exists in this schema.
     * Confirm a receipt, generating stock
     */
    async receiptsControllerConfirm(requestParameters: ReceiptsControllerConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerConfirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerCreate without sending the request
     */
    async receiptsControllerCreateRequestOpts(requestParameters: ReceiptsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createReceiptDto'] == null) {
            throw new runtime.RequiredError(
                'createReceiptDto',
                'Required parameter "createReceiptDto" was null or undefined when calling receiptsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReceiptDtoToJSON(requestParameters['createReceiptDto']),
        };
    }

    /**
     * Always starts as PENDING. supplierId can be set now or later via PATCH.
     * Create a new receipt
     */
    async receiptsControllerCreateRaw(requestParameters: ReceiptsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * Always starts as PENDING. supplierId can be set now or later via PATCH.
     * Create a new receipt
     */
    async receiptsControllerCreate(requestParameters: ReceiptsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerFindAll without sending the request
     */
    async receiptsControllerFindAllRequestOpts(requestParameters: ReceiptsControllerFindAllRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Optionally filtered by status and/or locationId. Newest first.
     * List the current tenant\'s receipts
     */
    async receiptsControllerFindAllRaw(requestParameters: ReceiptsControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReceiptResponseDto>>> {
        const requestOptions = await this.receiptsControllerFindAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReceiptResponseDtoFromJSON));
    }

    /**
     * Optionally filtered by status and/or locationId. Newest first.
     * List the current tenant\'s receipts
     */
    async receiptsControllerFindAll(requestParameters: ReceiptsControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReceiptResponseDto>> {
        const response = await this.receiptsControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerFindOne without sending the request
     */
    async receiptsControllerFindOneRequestOpts(requestParameters: ReceiptsControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Includes its accepted lines and the most recent extraction run (with only that run\'s still-pending lines).
     * Get a receipt by ID
     */
    async receiptsControllerFindOneRaw(requestParameters: ReceiptsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptDetailResponseDto>> {
        const requestOptions = await this.receiptsControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptDetailResponseDtoFromJSON(jsonValue));
    }

    /**
     * Includes its accepted lines and the most recent extraction run (with only that run\'s still-pending lines).
     * Get a receipt by ID
     */
    async receiptsControllerFindOne(requestParameters: ReceiptsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptDetailResponseDto> {
        const response = await this.receiptsControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerRemove without sending the request
     */
    async receiptsControllerRemoveRequestOpts(requestParameters: ReceiptsControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Only from CONFIRMED or ARCHIVED, and only if none of its stock_lots were ever consumed (quantity_remaining === quantity_received on every one). Physical delete: the qualifying stock_lots, its receipt_lines, and the receipt itself — the extraction audit trail cascades automatically.
     * Delete a receipt
     */
    async receiptsControllerRemoveRaw(requestParameters: ReceiptsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * Only from CONFIRMED or ARCHIVED, and only if none of its stock_lots were ever consumed (quantity_remaining === quantity_received on every one). Physical delete: the qualifying stock_lots, its receipt_lines, and the receipt itself — the extraction audit trail cascades automatically.
     * Delete a receipt
     */
    async receiptsControllerRemove(requestParameters: ReceiptsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerRestore without sending the request
     */
    async receiptsControllerRestoreRequestOpts(requestParameters: ReceiptsControllerRestoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerRestore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}/restore`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ARCHIVED -> CONFIRMED only — the inverse of archive.
     * Restore an archived receipt
     */
    async receiptsControllerRestoreRaw(requestParameters: ReceiptsControllerRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerRestoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * ARCHIVED -> CONFIRMED only — the inverse of archive.
     * Restore an archived receipt
     */
    async receiptsControllerRestore(requestParameters: ReceiptsControllerRestoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerRestoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiptsControllerUpdate without sending the request
     */
    async receiptsControllerUpdateRequestOpts(requestParameters: ReceiptsControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling receiptsControllerUpdate().'
            );
        }

        if (requestParameters['updateReceiptDto'] == null) {
            throw new runtime.RequiredError(
                'updateReceiptDto',
                'Required parameter "updateReceiptDto" was null or undefined when calling receiptsControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/receipts/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateReceiptDtoToJSON(requestParameters['updateReceiptDto']),
        };
    }

    /**
     * supplierId/docNumber/docDate/note. Not in the original scope — added to close a real gap: nothing else lets a receipt\'s supplier be resolved, which POST /receipts/:id/confirm requires.
     * Edit a PENDING receipt\'s header fields
     */
    async receiptsControllerUpdateRaw(requestParameters: ReceiptsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiptResponseDto>> {
        const requestOptions = await this.receiptsControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiptResponseDtoFromJSON(jsonValue));
    }

    /**
     * supplierId/docNumber/docDate/note. Not in the original scope — added to close a real gap: nothing else lets a receipt\'s supplier be resolved, which POST /receipts/:id/confirm requires.
     * Edit a PENDING receipt\'s header fields
     */
    async receiptsControllerUpdate(requestParameters: ReceiptsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiptResponseDto> {
        const response = await this.receiptsControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ReceiptsControllerFindAllStatusEnum = {
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    Archived: 'ARCHIVED',
    Canceled: 'CANCELED',
} as const;
export type ReceiptsControllerFindAllStatusEnum = typeof ReceiptsControllerFindAllStatusEnum[keyof typeof ReceiptsControllerFindAllStatusEnum];
