/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateRecipeDto,
    CreateRecipeDtoFromJSON,
    CreateRecipeDtoToJSON,
} from '../models/CreateRecipeDto';
import {
    type RecipeCostResponseDto,
    RecipeCostResponseDtoFromJSON,
    RecipeCostResponseDtoToJSON,
} from '../models/RecipeCostResponseDto';
import {
    type RecipeResponseDto,
    RecipeResponseDtoFromJSON,
    RecipeResponseDtoToJSON,
} from '../models/RecipeResponseDto';
import {
    type UpdateRecipeDto,
    UpdateRecipeDtoFromJSON,
    UpdateRecipeDtoToJSON,
} from '../models/UpdateRecipeDto';

export interface RecipesControllerCreateRequest {
    /**
     * 
     */
    createRecipeDto: CreateRecipeDto;
}

export interface RecipesControllerFindOneRequest {
    /**
     * Recipe ID
     */
    id: string;
}

export interface RecipesControllerGetCostRequest {
    /**
     * Recipe ID
     */
    id: string;
    /**
     * Location whose stock_lots to cost this recipe against. Required.
     */
    locationId: string;
}

export interface RecipesControllerRemoveRequest {
    /**
     * Recipe ID
     */
    id: string;
}

export interface RecipesControllerUpdateRequest {
    /**
     * Recipe ID
     */
    id: string;
    /**
     * 
     */
    updateRecipeDto: UpdateRecipeDto;
}

/**
 * 
 */
export class RecipesApi extends runtime.BaseAPI {

    /**
     * Creates request options for recipesControllerCreate without sending the request
     */
    async recipesControllerCreateRequestOpts(requestParameters: RecipesControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createRecipeDto'] == null) {
            throw new runtime.RequiredError(
                'createRecipeDto',
                'Required parameter "createRecipeDto" was null or undefined when calling recipesControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRecipeDtoToJSON(requestParameters['createRecipeDto']),
        };
    }

    /**
     * producedItemId, if given, must be an existing item belonging to the current tenant.
     * Create a recipe in the current tenant
     */
    async recipesControllerCreateRaw(requestParameters: RecipesControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeResponseDto>> {
        const requestOptions = await this.recipesControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeResponseDtoFromJSON(jsonValue));
    }

    /**
     * producedItemId, if given, must be an existing item belonging to the current tenant.
     * Create a recipe in the current tenant
     */
    async recipesControllerCreate(requestParameters: RecipesControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeResponseDto> {
        const response = await this.recipesControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipesControllerFindAll without sending the request
     */
    async recipesControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns only active recipes (is_active = true).
     * List the current tenant\'s recipes
     */
    async recipesControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RecipeResponseDto>>> {
        const requestOptions = await this.recipesControllerFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RecipeResponseDtoFromJSON));
    }

    /**
     * Returns only active recipes (is_active = true).
     * List the current tenant\'s recipes
     */
    async recipesControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RecipeResponseDto>> {
        const response = await this.recipesControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipesControllerFindOne without sending the request
     */
    async recipesControllerFindOneRequestOpts(requestParameters: RecipesControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recipesControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a recipe by ID
     */
    async recipesControllerFindOneRaw(requestParameters: RecipesControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeResponseDto>> {
        const requestOptions = await this.recipesControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a recipe by ID
     */
    async recipesControllerFindOne(requestParameters: RecipesControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeResponseDto> {
        const response = await this.recipesControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipesControllerGetCost without sending the request
     */
    async recipesControllerGetCostRequestOpts(requestParameters: RecipesControllerGetCostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recipesControllerGetCost().'
            );
        }

        if (requestParameters['locationId'] == null) {
            throw new runtime.RequiredError(
                'locationId',
                'Required parameter "locationId" was null or undefined when calling recipesControllerGetCost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{id}/cost`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Computed fresh on every call from the recipe\'s current ingredients and the current oldest available stock_lots price at the given location — never a stored/cached figure. locationId is required: a recipe isn\'t tied to one location, and costing without pinning one would be arbitrary for a multi-location tenant. Fails with NO_STOCK_AVAILABLE_FOR_COSTING if any ingredient has no stock at that location, instead of silently treating that line as free.
     * Calculate the current cost of a recipe at a location
     */
    async recipesControllerGetCostRaw(requestParameters: RecipesControllerGetCostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeCostResponseDto>> {
        const requestOptions = await this.recipesControllerGetCostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeCostResponseDtoFromJSON(jsonValue));
    }

    /**
     * Computed fresh on every call from the recipe\'s current ingredients and the current oldest available stock_lots price at the given location — never a stored/cached figure. locationId is required: a recipe isn\'t tied to one location, and costing without pinning one would be arbitrary for a multi-location tenant. Fails with NO_STOCK_AVAILABLE_FOR_COSTING if any ingredient has no stock at that location, instead of silently treating that line as free.
     * Calculate the current cost of a recipe at a location
     */
    async recipesControllerGetCost(requestParameters: RecipesControllerGetCostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeCostResponseDto> {
        const response = await this.recipesControllerGetCostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipesControllerRemove without sending the request
     */
    async recipesControllerRemoveRequestOpts(requestParameters: RecipesControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recipesControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Not a physical DELETE: sets is_active = false. The recipe stops appearing in GET /recipes but still exists in the database, along with its ingredients.
     * Deactivate a recipe (soft delete)
     */
    async recipesControllerRemoveRaw(requestParameters: RecipesControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeResponseDto>> {
        const requestOptions = await this.recipesControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Not a physical DELETE: sets is_active = false. The recipe stops appearing in GET /recipes but still exists in the database, along with its ingredients.
     * Deactivate a recipe (soft delete)
     */
    async recipesControllerRemove(requestParameters: RecipesControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeResponseDto> {
        const response = await this.recipesControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipesControllerUpdate without sending the request
     */
    async recipesControllerUpdateRequestOpts(requestParameters: RecipesControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recipesControllerUpdate().'
            );
        }

        if (requestParameters['updateRecipeDto'] == null) {
            throw new runtime.RequiredError(
                'updateRecipeDto',
                'Required parameter "updateRecipeDto" was null or undefined when calling recipesControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRecipeDtoToJSON(requestParameters['updateRecipeDto']),
        };
    }

    /**
     * Edit fields of a recipe
     */
    async recipesControllerUpdateRaw(requestParameters: RecipesControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeResponseDto>> {
        const requestOptions = await this.recipesControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Edit fields of a recipe
     */
    async recipesControllerUpdate(requestParameters: RecipesControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeResponseDto> {
        const response = await this.recipesControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
