/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateRecipeIngredientDto,
    CreateRecipeIngredientDtoFromJSON,
    CreateRecipeIngredientDtoToJSON,
} from '../models/CreateRecipeIngredientDto';
import {
    type RecipeIngredientResponseDto,
    RecipeIngredientResponseDtoFromJSON,
    RecipeIngredientResponseDtoToJSON,
} from '../models/RecipeIngredientResponseDto';
import {
    type UpdateRecipeIngredientDto,
    UpdateRecipeIngredientDtoFromJSON,
    UpdateRecipeIngredientDtoToJSON,
} from '../models/UpdateRecipeIngredientDto';

export interface RecipeIngredientsControllerCreateRequest {
    /**
     * Recipe ID
     */
    recipeId: string;
    /**
     * 
     */
    createRecipeIngredientDto: CreateRecipeIngredientDto;
}

export interface RecipeIngredientsControllerFindByRecipeRequest {
    /**
     * Recipe ID
     */
    recipeId: string;
}

export interface RecipeIngredientsControllerRemoveRequest {
    /**
     * Recipe ID
     */
    recipeId: string;
    /**
     * Recipe ingredient line ID
     */
    id: string;
}

export interface RecipeIngredientsControllerUpdateRequest {
    /**
     * Recipe ID
     */
    recipeId: string;
    /**
     * Recipe ingredient line ID
     */
    id: string;
    /**
     * 
     */
    updateRecipeIngredientDto: UpdateRecipeIngredientDto;
}

/**
 * 
 */
export class RecipeIngredientsApi extends runtime.BaseAPI {

    /**
     * Creates request options for recipeIngredientsControllerCreate without sending the request
     */
    async recipeIngredientsControllerCreateRequestOpts(requestParameters: RecipeIngredientsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['recipeId'] == null) {
            throw new runtime.RequiredError(
                'recipeId',
                'Required parameter "recipeId" was null or undefined when calling recipeIngredientsControllerCreate().'
            );
        }

        if (requestParameters['createRecipeIngredientDto'] == null) {
            throw new runtime.RequiredError(
                'createRecipeIngredientDto',
                'Required parameter "createRecipeIngredientDto" was null or undefined when calling recipeIngredientsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{recipeId}/ingredients`;
        urlPath = urlPath.replace('{recipeId}', encodeURIComponent(String(requestParameters['recipeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRecipeIngredientDtoToJSON(requestParameters['createRecipeIngredientDto']),
        };
    }

    /**
     * Exactly one of itemId (must already exist and belong to the tenant; quantityNet is in the item\'s own base unit, no conversion happens here) or subrecipeId (another recipe, used as a subrecipe — cannot equal the recipe itself; quantityNet is in the same \'yield unit\' as the subrecipe\'s own yieldPortions, see CLAUDE.md\'s Subrecipes section).
     * Add an ingredient line to a recipe
     */
    async recipeIngredientsControllerCreateRaw(requestParameters: RecipeIngredientsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeIngredientResponseDto>> {
        const requestOptions = await this.recipeIngredientsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeIngredientResponseDtoFromJSON(jsonValue));
    }

    /**
     * Exactly one of itemId (must already exist and belong to the tenant; quantityNet is in the item\'s own base unit, no conversion happens here) or subrecipeId (another recipe, used as a subrecipe — cannot equal the recipe itself; quantityNet is in the same \'yield unit\' as the subrecipe\'s own yieldPortions, see CLAUDE.md\'s Subrecipes section).
     * Add an ingredient line to a recipe
     */
    async recipeIngredientsControllerCreate(requestParameters: RecipeIngredientsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeIngredientResponseDto> {
        const response = await this.recipeIngredientsControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeIngredientsControllerFindByRecipe without sending the request
     */
    async recipeIngredientsControllerFindByRecipeRequestOpts(requestParameters: RecipeIngredientsControllerFindByRecipeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['recipeId'] == null) {
            throw new runtime.RequiredError(
                'recipeId',
                'Required parameter "recipeId" was null or undefined when calling recipeIngredientsControllerFindByRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{recipeId}/ingredients`;
        urlPath = urlPath.replace('{recipeId}', encodeURIComponent(String(requestParameters['recipeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List a recipe\'s ingredients
     */
    async recipeIngredientsControllerFindByRecipeRaw(requestParameters: RecipeIngredientsControllerFindByRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RecipeIngredientResponseDto>>> {
        const requestOptions = await this.recipeIngredientsControllerFindByRecipeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RecipeIngredientResponseDtoFromJSON));
    }

    /**
     * List a recipe\'s ingredients
     */
    async recipeIngredientsControllerFindByRecipe(requestParameters: RecipeIngredientsControllerFindByRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RecipeIngredientResponseDto>> {
        const response = await this.recipeIngredientsControllerFindByRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeIngredientsControllerRemove without sending the request
     */
    async recipeIngredientsControllerRemoveRequestOpts(requestParameters: RecipeIngredientsControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['recipeId'] == null) {
            throw new runtime.RequiredError(
                'recipeId',
                'Required parameter "recipeId" was null or undefined when calling recipeIngredientsControllerRemove().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recipeIngredientsControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{recipeId}/ingredients/{id}`;
        urlPath = urlPath.replace('{recipeId}', encodeURIComponent(String(requestParameters['recipeId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Physical delete, not a soft delete — a recipe line that no longer exists has no meaningful \"inactive\" state to preserve.
     * Remove an ingredient line from a recipe
     */
    async recipeIngredientsControllerRemoveRaw(requestParameters: RecipeIngredientsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeIngredientResponseDto>> {
        const requestOptions = await this.recipeIngredientsControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeIngredientResponseDtoFromJSON(jsonValue));
    }

    /**
     * Physical delete, not a soft delete — a recipe line that no longer exists has no meaningful \"inactive\" state to preserve.
     * Remove an ingredient line from a recipe
     */
    async recipeIngredientsControllerRemove(requestParameters: RecipeIngredientsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeIngredientResponseDto> {
        const response = await this.recipeIngredientsControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeIngredientsControllerUpdate without sending the request
     */
    async recipeIngredientsControllerUpdateRequestOpts(requestParameters: RecipeIngredientsControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['recipeId'] == null) {
            throw new runtime.RequiredError(
                'recipeId',
                'Required parameter "recipeId" was null or undefined when calling recipeIngredientsControllerUpdate().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling recipeIngredientsControllerUpdate().'
            );
        }

        if (requestParameters['updateRecipeIngredientDto'] == null) {
            throw new runtime.RequiredError(
                'updateRecipeIngredientDto',
                'Required parameter "updateRecipeIngredientDto" was null or undefined when calling recipeIngredientsControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipes/{recipeId}/ingredients/{id}`;
        urlPath = urlPath.replace('{recipeId}', encodeURIComponent(String(requestParameters['recipeId'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRecipeIngredientDtoToJSON(requestParameters['updateRecipeIngredientDto']),
        };
    }

    /**
     * Cannot move this line to a different item — delete and recreate instead.
     * Update the quantity or waste percentage of an ingredient line
     */
    async recipeIngredientsControllerUpdateRaw(requestParameters: RecipeIngredientsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeIngredientResponseDto>> {
        const requestOptions = await this.recipeIngredientsControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeIngredientResponseDtoFromJSON(jsonValue));
    }

    /**
     * Cannot move this line to a different item — delete and recreate instead.
     * Update the quantity or waste percentage of an ingredient line
     */
    async recipeIngredientsControllerUpdate(requestParameters: RecipeIngredientsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeIngredientResponseDto> {
        const response = await this.recipeIngredientsControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
