/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptRecipeExtractionLineDto,
    AcceptRecipeExtractionLineDtoFromJSON,
    AcceptRecipeExtractionLineDtoToJSON,
} from '../models/AcceptRecipeExtractionLineDto';
import {
    type RecipeExtractionLineResponseDto,
    RecipeExtractionLineResponseDtoFromJSON,
    RecipeExtractionLineResponseDtoToJSON,
} from '../models/RecipeExtractionLineResponseDto';
import {
    type RecipeExtractionRunResponseDto,
    RecipeExtractionRunResponseDtoFromJSON,
    RecipeExtractionRunResponseDtoToJSON,
} from '../models/RecipeExtractionRunResponseDto';
import {
    type RecipeResponseDto,
    RecipeResponseDtoFromJSON,
    RecipeResponseDtoToJSON,
} from '../models/RecipeResponseDto';
import {
    type UpdateRecipeExtractionRunDto,
    UpdateRecipeExtractionRunDtoFromJSON,
    UpdateRecipeExtractionRunDtoToJSON,
} from '../models/UpdateRecipeExtractionRunDto';

export interface RecipeScanningControllerAcceptLineRequest {
    /**
     * Recipe scan extraction run ID
     */
    runId: string;
    /**
     * Recipe scan extraction line ID
     */
    lineId: string;
    /**
     * 
     */
    acceptRecipeExtractionLineDto: AcceptRecipeExtractionLineDto;
}

export interface RecipeScanningControllerCommitRequest {
    /**
     * Recipe scan extraction run ID
     */
    runId: string;
}

export interface RecipeScanningControllerDiscardRequest {
    /**
     * Recipe scan extraction run ID
     */
    runId: string;
}

export interface RecipeScanningControllerExtractRequest {
    /**
     * 
     */
    file: Blob;
}

export interface RecipeScanningControllerFindOneRequest {
    /**
     * Recipe scan extraction run ID
     */
    runId: string;
}

export interface RecipeScanningControllerRejectLineRequest {
    /**
     * Recipe scan extraction run ID
     */
    runId: string;
    /**
     * Recipe scan extraction line ID
     */
    lineId: string;
}

export interface RecipeScanningControllerUpdateRequest {
    /**
     * Recipe scan extraction run ID
     */
    runId: string;
    /**
     * 
     */
    updateRecipeExtractionRunDto: UpdateRecipeExtractionRunDto;
}

/**
 * 
 */
export class RecipeScanningApi extends runtime.BaseAPI {

    /**
     * Creates request options for recipeScanningControllerAcceptLine without sending the request
     */
    async recipeScanningControllerAcceptLineRequestOpts(requestParameters: RecipeScanningControllerAcceptLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling recipeScanningControllerAcceptLine().'
            );
        }

        if (requestParameters['lineId'] == null) {
            throw new runtime.RequiredError(
                'lineId',
                'Required parameter "lineId" was null or undefined when calling recipeScanningControllerAcceptLine().'
            );
        }

        if (requestParameters['acceptRecipeExtractionLineDto'] == null) {
            throw new runtime.RequiredError(
                'acceptRecipeExtractionLineDto',
                'Required parameter "acceptRecipeExtractionLineDto" was null or undefined when calling recipeScanningControllerAcceptLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipe-scanning/{runId}/lines/{lineId}/accept`;
        urlPath = urlPath.replace('{runId}', encodeURIComponent(String(requestParameters['runId'])));
        urlPath = urlPath.replace('{lineId}', encodeURIComponent(String(requestParameters['lineId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptRecipeExtractionLineDtoToJSON(requestParameters['acceptRecipeExtractionLineDto']),
        };
    }

    /**
     * Resolves the ingredient via itemId (existing item), recipeId (existing recipe, used as a subrecipe), or createNewItem + newItem (opt-in creation, never automatic). Does NOT create anything in recipes/recipe_ingredients yet — that only happens at commit, since the real recipe does not exist until then. quantityNet/wastePct are editable from what was extracted.
     * Accept a proposed ingredient line
     */
    async recipeScanningControllerAcceptLineRaw(requestParameters: RecipeScanningControllerAcceptLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeExtractionLineResponseDto>> {
        const requestOptions = await this.recipeScanningControllerAcceptLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeExtractionLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * Resolves the ingredient via itemId (existing item), recipeId (existing recipe, used as a subrecipe), or createNewItem + newItem (opt-in creation, never automatic). Does NOT create anything in recipes/recipe_ingredients yet — that only happens at commit, since the real recipe does not exist until then. quantityNet/wastePct are editable from what was extracted.
     * Accept a proposed ingredient line
     */
    async recipeScanningControllerAcceptLine(requestParameters: RecipeScanningControllerAcceptLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeExtractionLineResponseDto> {
        const response = await this.recipeScanningControllerAcceptLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeScanningControllerCommit without sending the request
     */
    async recipeScanningControllerCommitRequestOpts(requestParameters: RecipeScanningControllerCommitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling recipeScanningControllerCommit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipe-scanning/{runId}/commit`;
        urlPath = urlPath.replace('{runId}', encodeURIComponent(String(requestParameters['runId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * PENDING -> COMMITTED. Requires suggestedName and suggestedYieldPortions to be resolved (edit via PATCH first) and at least one accepted line. Atomically: creates the recipe row from the suggested header, and one recipe_ingredients row per accepted line (itemId or subrecipeId, never both, per line). Returns the newly created recipe.
     * Commit the run, creating the real recipe
     */
    async recipeScanningControllerCommitRaw(requestParameters: RecipeScanningControllerCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeResponseDto>> {
        const requestOptions = await this.recipeScanningControllerCommitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeResponseDtoFromJSON(jsonValue));
    }

    /**
     * PENDING -> COMMITTED. Requires suggestedName and suggestedYieldPortions to be resolved (edit via PATCH first) and at least one accepted line. Atomically: creates the recipe row from the suggested header, and one recipe_ingredients row per accepted line (itemId or subrecipeId, never both, per line). Returns the newly created recipe.
     * Commit the run, creating the real recipe
     */
    async recipeScanningControllerCommit(requestParameters: RecipeScanningControllerCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeResponseDto> {
        const response = await this.recipeScanningControllerCommitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeScanningControllerDiscard without sending the request
     */
    async recipeScanningControllerDiscardRequestOpts(requestParameters: RecipeScanningControllerDiscardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling recipeScanningControllerDiscard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipe-scanning/{runId}/discard`;
        urlPath = urlPath.replace('{runId}', encodeURIComponent(String(requestParameters['runId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * PENDING -> DISCARDED. Creates nothing — no recipe, no recipe_ingredients.
     * Discard the run entirely
     */
    async recipeScanningControllerDiscardRaw(requestParameters: RecipeScanningControllerDiscardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeExtractionRunResponseDto>> {
        const requestOptions = await this.recipeScanningControllerDiscardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeExtractionRunResponseDtoFromJSON(jsonValue));
    }

    /**
     * PENDING -> DISCARDED. Creates nothing — no recipe, no recipe_ingredients.
     * Discard the run entirely
     */
    async recipeScanningControllerDiscard(requestParameters: RecipeScanningControllerDiscardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeExtractionRunResponseDto> {
        const response = await this.recipeScanningControllerDiscardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeScanningControllerExtract without sending the request
     */
    async recipeScanningControllerExtractRequestOpts(requestParameters: RecipeScanningControllerExtractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling recipeScanningControllerExtract().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/recipe-scanning/extract`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Uploads via the generic Document Extraction service, then creates a new draft (extraction run) with a suggested header (name/yieldPortions/prepSteps) and proposed ingredient lines, each auto-matched against your existing items AND recipes. Unlike Receipts, there is no separate \"create\" step — this call both starts the draft and extracts into it.
     * Upload a recipe photo and run AI extraction
     */
    async recipeScanningControllerExtractRaw(requestParameters: RecipeScanningControllerExtractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeExtractionRunResponseDto>> {
        const requestOptions = await this.recipeScanningControllerExtractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeExtractionRunResponseDtoFromJSON(jsonValue));
    }

    /**
     * Uploads via the generic Document Extraction service, then creates a new draft (extraction run) with a suggested header (name/yieldPortions/prepSteps) and proposed ingredient lines, each auto-matched against your existing items AND recipes. Unlike Receipts, there is no separate \"create\" step — this call both starts the draft and extracts into it.
     * Upload a recipe photo and run AI extraction
     */
    async recipeScanningControllerExtract(requestParameters: RecipeScanningControllerExtractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeExtractionRunResponseDto> {
        const response = await this.recipeScanningControllerExtractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeScanningControllerFindOne without sending the request
     */
    async recipeScanningControllerFindOneRequestOpts(requestParameters: RecipeScanningControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling recipeScanningControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipe-scanning/{runId}`;
        urlPath = urlPath.replace('{runId}', encodeURIComponent(String(requestParameters['runId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Includes the suggested header and every proposed ingredient line, in any reviewStatus.
     * Get a recipe scan run by ID
     */
    async recipeScanningControllerFindOneRaw(requestParameters: RecipeScanningControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeExtractionRunResponseDto>> {
        const requestOptions = await this.recipeScanningControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeExtractionRunResponseDtoFromJSON(jsonValue));
    }

    /**
     * Includes the suggested header and every proposed ingredient line, in any reviewStatus.
     * Get a recipe scan run by ID
     */
    async recipeScanningControllerFindOne(requestParameters: RecipeScanningControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeExtractionRunResponseDto> {
        const response = await this.recipeScanningControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeScanningControllerRejectLine without sending the request
     */
    async recipeScanningControllerRejectLineRequestOpts(requestParameters: RecipeScanningControllerRejectLineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling recipeScanningControllerRejectLine().'
            );
        }

        if (requestParameters['lineId'] == null) {
            throw new runtime.RequiredError(
                'lineId',
                'Required parameter "lineId" was null or undefined when calling recipeScanningControllerRejectLine().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipe-scanning/{runId}/lines/{lineId}`;
        urlPath = urlPath.replace('{runId}', encodeURIComponent(String(requestParameters['runId'])));
        urlPath = urlPath.replace('{lineId}', encodeURIComponent(String(requestParameters['lineId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sets reviewStatus=REJECTED — the row stays as a record of what was proposed and dismissed.
     * Discard a proposed ingredient line without accepting it
     */
    async recipeScanningControllerRejectLineRaw(requestParameters: RecipeScanningControllerRejectLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeExtractionLineResponseDto>> {
        const requestOptions = await this.recipeScanningControllerRejectLineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeExtractionLineResponseDtoFromJSON(jsonValue));
    }

    /**
     * Sets reviewStatus=REJECTED — the row stays as a record of what was proposed and dismissed.
     * Discard a proposed ingredient line without accepting it
     */
    async recipeScanningControllerRejectLine(requestParameters: RecipeScanningControllerRejectLineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeExtractionLineResponseDto> {
        const response = await this.recipeScanningControllerRejectLineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recipeScanningControllerUpdate without sending the request
     */
    async recipeScanningControllerUpdateRequestOpts(requestParameters: RecipeScanningControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling recipeScanningControllerUpdate().'
            );
        }

        if (requestParameters['updateRecipeExtractionRunDto'] == null) {
            throw new runtime.RequiredError(
                'updateRecipeExtractionRunDto',
                'Required parameter "updateRecipeExtractionRunDto" was null or undefined when calling recipeScanningControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/recipe-scanning/{runId}`;
        urlPath = urlPath.replace('{runId}', encodeURIComponent(String(requestParameters['runId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRecipeExtractionRunDtoToJSON(requestParameters['updateRecipeExtractionRunDto']),
        };
    }

    /**
     * suggestedName/suggestedYieldPortions/suggestedPrepSteps. Only allowed while the run is PENDING.
     * Edit the AI\'s suggested header before committing
     */
    async recipeScanningControllerUpdateRaw(requestParameters: RecipeScanningControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeExtractionRunResponseDto>> {
        const requestOptions = await this.recipeScanningControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeExtractionRunResponseDtoFromJSON(jsonValue));
    }

    /**
     * suggestedName/suggestedYieldPortions/suggestedPrepSteps. Only allowed while the run is PENDING.
     * Edit the AI\'s suggested header before committing
     */
    async recipeScanningControllerUpdate(requestParameters: RecipeScanningControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeExtractionRunResponseDto> {
        const response = await this.recipeScanningControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
