/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateStockLotDto,
    CreateStockLotDtoFromJSON,
    CreateStockLotDtoToJSON,
} from '../models/CreateStockLotDto';
import {
    type StockLotResponseDto,
    StockLotResponseDtoFromJSON,
    StockLotResponseDtoToJSON,
} from '../models/StockLotResponseDto';
import {
    type UpdateStockLotDto,
    UpdateStockLotDtoFromJSON,
    UpdateStockLotDtoToJSON,
} from '../models/UpdateStockLotDto';

export interface StockLotsControllerCreateRequest {
    /**
     * 
     */
    createStockLotDto: CreateStockLotDto;
}

export interface StockLotsControllerFindOneRequest {
    /**
     * Stock lot ID
     */
    id: string;
}

export interface StockLotsControllerUpdateRequest {
    /**
     * Stock lot ID
     */
    id: string;
    /**
     * 
     */
    updateStockLotDto: UpdateStockLotDto;
}

/**
 * 
 */
export class StockLotsApi extends runtime.BaseAPI {

    /**
     * Creates request options for stockLotsControllerCreate without sending the request
     */
    async stockLotsControllerCreateRequestOpts(requestParameters: StockLotsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createStockLotDto'] == null) {
            throw new runtime.RequiredError(
                'createStockLotDto',
                'Required parameter "createStockLotDto" was null or undefined when calling stockLotsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stock-lots`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStockLotDtoToJSON(requestParameters['createStockLotDto']),
        };
    }

    /**
     * quantityRemaining starts equal to quantityReceived — there\'s no way to set it directly. itemId/locationId must belong to the tenant; supplierId, if given, too.
     * Manually record a received stock lot
     */
    async stockLotsControllerCreateRaw(requestParameters: StockLotsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLotResponseDto>> {
        const requestOptions = await this.stockLotsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLotResponseDtoFromJSON(jsonValue));
    }

    /**
     * quantityRemaining starts equal to quantityReceived — there\'s no way to set it directly. itemId/locationId must belong to the tenant; supplierId, if given, too.
     * Manually record a received stock lot
     */
    async stockLotsControllerCreate(requestParameters: StockLotsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLotResponseDto> {
        const response = await this.stockLotsControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stockLotsControllerFindAll without sending the request
     */
    async stockLotsControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stock-lots`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Includes lots with quantityRemaining = 0 — nothing is ever hidden or deleted, see class description.
     * List the current tenant\'s stock lots
     */
    async stockLotsControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StockLotResponseDto>>> {
        const requestOptions = await this.stockLotsControllerFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StockLotResponseDtoFromJSON));
    }

    /**
     * Includes lots with quantityRemaining = 0 — nothing is ever hidden or deleted, see class description.
     * List the current tenant\'s stock lots
     */
    async stockLotsControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StockLotResponseDto>> {
        const response = await this.stockLotsControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stockLotsControllerFindOne without sending the request
     */
    async stockLotsControllerFindOneRequestOpts(requestParameters: StockLotsControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stockLotsControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stock-lots/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a stock lot by ID
     */
    async stockLotsControllerFindOneRaw(requestParameters: StockLotsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLotResponseDto>> {
        const requestOptions = await this.stockLotsControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLotResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a stock lot by ID
     */
    async stockLotsControllerFindOne(requestParameters: StockLotsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLotResponseDto> {
        const response = await this.stockLotsControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stockLotsControllerUpdate without sending the request
     */
    async stockLotsControllerUpdateRequestOpts(requestParameters: StockLotsControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stockLotsControllerUpdate().'
            );
        }

        if (requestParameters['updateStockLotDto'] == null) {
            throw new runtime.RequiredError(
                'updateStockLotDto',
                'Required parameter "updateStockLotDto" was null or undefined when calling stockLotsControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/stock-lots/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStockLotDtoToJSON(requestParameters['updateStockLotDto']),
        };
    }

    /**
     * The only editable field, for fixing a data-entry mistake. itemId, locationId, supplierId, quantityReceived, and receivedAt are immutable once the lot exists; quantityRemaining can only change via FIFO consumption, never through this endpoint.
     * Correct the unit cost of a stock lot
     */
    async stockLotsControllerUpdateRaw(requestParameters: StockLotsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StockLotResponseDto>> {
        const requestOptions = await this.stockLotsControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StockLotResponseDtoFromJSON(jsonValue));
    }

    /**
     * The only editable field, for fixing a data-entry mistake. itemId, locationId, supplierId, quantityReceived, and receivedAt are immutable once the lot exists; quantityRemaining can only change via FIFO consumption, never through this endpoint.
     * Correct the unit cost of a stock lot
     */
    async stockLotsControllerUpdate(requestParameters: StockLotsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StockLotResponseDto> {
        const response = await this.stockLotsControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
