/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateSupplierItemPriceDto,
    CreateSupplierItemPriceDtoFromJSON,
    CreateSupplierItemPriceDtoToJSON,
} from '../models/CreateSupplierItemPriceDto';
import {
    type SupplierItemPriceResponseDto,
    SupplierItemPriceResponseDtoFromJSON,
    SupplierItemPriceResponseDtoToJSON,
} from '../models/SupplierItemPriceResponseDto';
import {
    type UpdateSupplierItemPriceDto,
    UpdateSupplierItemPriceDtoFromJSON,
    UpdateSupplierItemPriceDtoToJSON,
} from '../models/UpdateSupplierItemPriceDto';

export interface SupplierItemPricesControllerCreateRequest {
    /**
     * Item ID
     */
    itemId: string;
    /**
     * 
     */
    createSupplierItemPriceDto: CreateSupplierItemPriceDto;
}

export interface SupplierItemPricesControllerFindByItemRequest {
    /**
     * Item ID
     */
    itemId: string;
}

export interface SupplierItemPricesControllerRemoveRequest {
    /**
     * Item ID
     */
    itemId: string;
    /**
     * Supplier ID
     */
    supplierId: string;
}

export interface SupplierItemPricesControllerUpdateRequest {
    /**
     * Item ID
     */
    itemId: string;
    /**
     * Supplier ID
     */
    supplierId: string;
    /**
     * 
     */
    updateSupplierItemPriceDto: UpdateSupplierItemPriceDto;
}

/**
 * 
 */
export class SupplierItemPricesApi extends runtime.BaseAPI {

    /**
     * Creates request options for supplierItemPricesControllerCreate without sending the request
     */
    async supplierItemPricesControllerCreateRequestOpts(requestParameters: SupplierItemPricesControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling supplierItemPricesControllerCreate().'
            );
        }

        if (requestParameters['createSupplierItemPriceDto'] == null) {
            throw new runtime.RequiredError(
                'createSupplierItemPriceDto',
                'Required parameter "createSupplierItemPriceDto" was null or undefined when calling supplierItemPricesControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{itemId}/suppliers`;
        urlPath = urlPath.replace('{itemId}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSupplierItemPriceDtoToJSON(requestParameters['createSupplierItemPriceDto']),
        };
    }

    /**
     * Both the item and the supplier (dto.supplierId) must already exist and belong to the current tenant. Fails with SUPPLIER_PRICE_ALREADY_LINKED if this item/supplier pair is already linked — PATCH it instead. Setting isPreferred: true unmarks any other price row for this item that was previously preferred, in the same transaction.
     * Link an existing supplier to an item, at a price
     */
    async supplierItemPricesControllerCreateRaw(requestParameters: SupplierItemPricesControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierItemPriceResponseDto>> {
        const requestOptions = await this.supplierItemPricesControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierItemPriceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Both the item and the supplier (dto.supplierId) must already exist and belong to the current tenant. Fails with SUPPLIER_PRICE_ALREADY_LINKED if this item/supplier pair is already linked — PATCH it instead. Setting isPreferred: true unmarks any other price row for this item that was previously preferred, in the same transaction.
     * Link an existing supplier to an item, at a price
     */
    async supplierItemPricesControllerCreate(requestParameters: SupplierItemPricesControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierItemPriceResponseDto> {
        const response = await this.supplierItemPricesControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for supplierItemPricesControllerFindByItem without sending the request
     */
    async supplierItemPricesControllerFindByItemRequestOpts(requestParameters: SupplierItemPricesControllerFindByItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling supplierItemPricesControllerFindByItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{itemId}/suppliers`;
        urlPath = urlPath.replace('{itemId}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Every supplier currently linked to this item, with the price they charge and the supplier data embedded — not just the supplier ID.
     * List suppliers and prices for an item
     */
    async supplierItemPricesControllerFindByItemRaw(requestParameters: SupplierItemPricesControllerFindByItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SupplierItemPriceResponseDto>>> {
        const requestOptions = await this.supplierItemPricesControllerFindByItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SupplierItemPriceResponseDtoFromJSON));
    }

    /**
     * Every supplier currently linked to this item, with the price they charge and the supplier data embedded — not just the supplier ID.
     * List suppliers and prices for an item
     */
    async supplierItemPricesControllerFindByItem(requestParameters: SupplierItemPricesControllerFindByItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SupplierItemPriceResponseDto>> {
        const response = await this.supplierItemPricesControllerFindByItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for supplierItemPricesControllerRemove without sending the request
     */
    async supplierItemPricesControllerRemoveRequestOpts(requestParameters: SupplierItemPricesControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling supplierItemPricesControllerRemove().'
            );
        }

        if (requestParameters['supplierId'] == null) {
            throw new runtime.RequiredError(
                'supplierId',
                'Required parameter "supplierId" was null or undefined when calling supplierItemPricesControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{itemId}/suppliers/{supplierId}`;
        urlPath = urlPath.replace('{itemId}', encodeURIComponent(String(requestParameters['itemId'])));
        urlPath = urlPath.replace('{supplierId}', encodeURIComponent(String(requestParameters['supplierId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Physical delete, not a soft delete — a price link that no longer exists has no meaningful \"inactive\" state to preserve, unlike an item or a supplier.
     * Unlink a supplier from an item
     */
    async supplierItemPricesControllerRemoveRaw(requestParameters: SupplierItemPricesControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierItemPriceResponseDto>> {
        const requestOptions = await this.supplierItemPricesControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierItemPriceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Physical delete, not a soft delete — a price link that no longer exists has no meaningful \"inactive\" state to preserve, unlike an item or a supplier.
     * Unlink a supplier from an item
     */
    async supplierItemPricesControllerRemove(requestParameters: SupplierItemPricesControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierItemPriceResponseDto> {
        const response = await this.supplierItemPricesControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for supplierItemPricesControllerUpdate without sending the request
     */
    async supplierItemPricesControllerUpdateRequestOpts(requestParameters: SupplierItemPricesControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling supplierItemPricesControllerUpdate().'
            );
        }

        if (requestParameters['supplierId'] == null) {
            throw new runtime.RequiredError(
                'supplierId',
                'Required parameter "supplierId" was null or undefined when calling supplierItemPricesControllerUpdate().'
            );
        }

        if (requestParameters['updateSupplierItemPriceDto'] == null) {
            throw new runtime.RequiredError(
                'updateSupplierItemPriceDto',
                'Required parameter "updateSupplierItemPriceDto" was null or undefined when calling supplierItemPricesControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/catalog/{itemId}/suppliers/{supplierId}`;
        urlPath = urlPath.replace('{itemId}', encodeURIComponent(String(requestParameters['itemId'])));
        urlPath = urlPath.replace('{supplierId}', encodeURIComponent(String(requestParameters['supplierId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSupplierItemPriceDtoToJSON(requestParameters['updateSupplierItemPriceDto']),
        };
    }

    /**
     * Setting isPreferred: true unmarks any other price row for this item that was previously preferred, in the same transaction. Cannot move this price to a different supplier — delete and recreate instead.
     * Update the price, conversion factor, or preferred flag
     */
    async supplierItemPricesControllerUpdateRaw(requestParameters: SupplierItemPricesControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierItemPriceResponseDto>> {
        const requestOptions = await this.supplierItemPricesControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierItemPriceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Setting isPreferred: true unmarks any other price row for this item that was previously preferred, in the same transaction. Cannot move this price to a different supplier — delete and recreate instead.
     * Update the price, conversion factor, or preferred flag
     */
    async supplierItemPricesControllerUpdate(requestParameters: SupplierItemPricesControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierItemPriceResponseDto> {
        const response = await this.supplierItemPricesControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
