/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateSupplierDto,
    CreateSupplierDtoFromJSON,
    CreateSupplierDtoToJSON,
} from '../models/CreateSupplierDto';
import {
    type SupplierResponseDto,
    SupplierResponseDtoFromJSON,
    SupplierResponseDtoToJSON,
} from '../models/SupplierResponseDto';
import {
    type UpdateSupplierDto,
    UpdateSupplierDtoFromJSON,
    UpdateSupplierDtoToJSON,
} from '../models/UpdateSupplierDto';

export interface SuppliersControllerCreateRequest {
    /**
     * 
     */
    createSupplierDto: CreateSupplierDto;
}

export interface SuppliersControllerFindOneRequest {
    /**
     * Supplier ID
     */
    id: string;
}

export interface SuppliersControllerRemoveRequest {
    /**
     * Supplier ID
     */
    id: string;
}

export interface SuppliersControllerUpdateRequest {
    /**
     * Supplier ID
     */
    id: string;
    /**
     * 
     */
    updateSupplierDto: UpdateSupplierDto;
}

/**
 * 
 */
export class SuppliersApi extends runtime.BaseAPI {

    /**
     * Creates request options for suppliersControllerCreate without sending the request
     */
    async suppliersControllerCreateRequestOpts(requestParameters: SuppliersControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSupplierDto'] == null) {
            throw new runtime.RequiredError(
                'createSupplierDto',
                'Required parameter "createSupplierDto" was null or undefined when calling suppliersControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/suppliers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSupplierDtoToJSON(requestParameters['createSupplierDto']),
        };
    }

    /**
     * Create a supplier in the current tenant\'s catalog
     */
    async suppliersControllerCreateRaw(requestParameters: SuppliersControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierResponseDto>> {
        const requestOptions = await this.suppliersControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a supplier in the current tenant\'s catalog
     */
    async suppliersControllerCreate(requestParameters: SuppliersControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierResponseDto> {
        const response = await this.suppliersControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suppliersControllerFindAll without sending the request
     */
    async suppliersControllerFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/suppliers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns only active suppliers (is_active = true) for the authenticated user\'s tenant.
     * List the current tenant\'s suppliers
     */
    async suppliersControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SupplierResponseDto>>> {
        const requestOptions = await this.suppliersControllerFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SupplierResponseDtoFromJSON));
    }

    /**
     * Returns only active suppliers (is_active = true) for the authenticated user\'s tenant.
     * List the current tenant\'s suppliers
     */
    async suppliersControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SupplierResponseDto>> {
        const response = await this.suppliersControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suppliersControllerFindOne without sending the request
     */
    async suppliersControllerFindOneRequestOpts(requestParameters: SuppliersControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling suppliersControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/suppliers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a supplier by ID
     */
    async suppliersControllerFindOneRaw(requestParameters: SuppliersControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierResponseDto>> {
        const requestOptions = await this.suppliersControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a supplier by ID
     */
    async suppliersControllerFindOne(requestParameters: SuppliersControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierResponseDto> {
        const response = await this.suppliersControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suppliersControllerRemove without sending the request
     */
    async suppliersControllerRemoveRequestOpts(requestParameters: SuppliersControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling suppliersControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/suppliers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Not a physical DELETE: sets is_active = false. Existing supplier_item_prices rows for this supplier are left untouched — the supplier just stops appearing in GET /suppliers and GET /catalog/:itemId/suppliers keeps returning its price rows regardless.
     * Deactivate a supplier (soft delete)
     */
    async suppliersControllerRemoveRaw(requestParameters: SuppliersControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierResponseDto>> {
        const requestOptions = await this.suppliersControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierResponseDtoFromJSON(jsonValue));
    }

    /**
     * Not a physical DELETE: sets is_active = false. Existing supplier_item_prices rows for this supplier are left untouched — the supplier just stops appearing in GET /suppliers and GET /catalog/:itemId/suppliers keeps returning its price rows regardless.
     * Deactivate a supplier (soft delete)
     */
    async suppliersControllerRemove(requestParameters: SuppliersControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierResponseDto> {
        const response = await this.suppliersControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suppliersControllerUpdate without sending the request
     */
    async suppliersControllerUpdateRequestOpts(requestParameters: SuppliersControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling suppliersControllerUpdate().'
            );
        }

        if (requestParameters['updateSupplierDto'] == null) {
            throw new runtime.RequiredError(
                'updateSupplierDto',
                'Required parameter "updateSupplierDto" was null or undefined when calling suppliersControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/suppliers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSupplierDtoToJSON(requestParameters['updateSupplierDto']),
        };
    }

    /**
     * Edit fields of a supplier
     */
    async suppliersControllerUpdateRaw(requestParameters: SuppliersControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplierResponseDto>> {
        const requestOptions = await this.suppliersControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplierResponseDtoFromJSON(jsonValue));
    }

    /**
     * Edit fields of a supplier
     */
    async suppliersControllerUpdate(requestParameters: SuppliersControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplierResponseDto> {
        const response = await this.suppliersControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
