/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type UsageCounterResponseDto,
    UsageCounterResponseDtoFromJSON,
    UsageCounterResponseDtoToJSON,
} from '../models/UsageCounterResponseDto';

export interface UsageCountersControllerFindCurrentPeriodRequest {
    /**
     * Which billing period to report. Only "current" exists today.
     */
    period?: UsageCountersControllerFindCurrentPeriodPeriodEnum;
}

/**
 * 
 */
export class UsageCountersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usageCountersControllerFindCurrentPeriod without sending the request
     */
    async usageCountersControllerFindCurrentPeriodRequestOpts(requestParameters: UsageCountersControllerFindCurrentPeriodRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/usage-counters`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Always returns one entry per known counter_key (receipt_scans, recipe_scans), defaulting count to 0 for a key unused this period. Measured only — nothing here blocks a request; see CLAUDE.md.
     * List the current tenant\'s AI usage counters
     */
    async usageCountersControllerFindCurrentPeriodRaw(requestParameters: UsageCountersControllerFindCurrentPeriodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsageCounterResponseDto>>> {
        const requestOptions = await this.usageCountersControllerFindCurrentPeriodRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsageCounterResponseDtoFromJSON));
    }

    /**
     * Always returns one entry per known counter_key (receipt_scans, recipe_scans), defaulting count to 0 for a key unused this period. Measured only — nothing here blocks a request; see CLAUDE.md.
     * List the current tenant\'s AI usage counters
     */
    async usageCountersControllerFindCurrentPeriod(requestParameters: UsageCountersControllerFindCurrentPeriodRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsageCounterResponseDto>> {
        const response = await this.usageCountersControllerFindCurrentPeriodRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const UsageCountersControllerFindCurrentPeriodPeriodEnum = {
    Current: 'current',
} as const;
export type UsageCountersControllerFindCurrentPeriodPeriodEnum = typeof UsageCountersControllerFindCurrentPeriodPeriodEnum[keyof typeof UsageCountersControllerFindCurrentPeriodPeriodEnum];
