/* tslint:disable */
/* eslint-disable */
/**
 * Mixzi API
 * Core Mixzi API — Back of House management for restaurants
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CaptureWasteDto,
    CaptureWasteDtoFromJSON,
    CaptureWasteDtoToJSON,
} from '../models/CaptureWasteDto';
import {
    type CreateWasteDto,
    CreateWasteDtoFromJSON,
    CreateWasteDtoToJSON,
} from '../models/CreateWasteDto';
import {
    type UpdateWasteDto,
    UpdateWasteDtoFromJSON,
    UpdateWasteDtoToJSON,
} from '../models/UpdateWasteDto';
import {
    type WasteAnalyticsResponseDto,
    WasteAnalyticsResponseDtoFromJSON,
    WasteAnalyticsResponseDtoToJSON,
} from '../models/WasteAnalyticsResponseDto';
import {
    type WasteResponseDto,
    WasteResponseDtoFromJSON,
    WasteResponseDtoToJSON,
} from '../models/WasteResponseDto';

export interface WasteControllerCancelRequest {
    /**
     * Waste record ID
     */
    id: string;
}

export interface WasteControllerCaptureRequest {
    /**
     * 
     */
    captureWasteDto: CaptureWasteDto;
}

export interface WasteControllerConfirmRequest {
    /**
     * Waste record ID
     */
    id: string;
}

export interface WasteControllerCreateRequest {
    /**
     * 
     */
    createWasteDto: CreateWasteDto;
}

export interface WasteControllerFindAllRequest {
    /**
     * 
     */
    status?: WasteControllerFindAllStatusEnum;
    /**
     * 
     */
    locationId?: string;
    /**
     * 
     */
    itemId?: string;
    /**
     * 
     */
    reason?: WasteControllerFindAllReasonEnum;
}

export interface WasteControllerFindOneRequest {
    /**
     * Waste record ID
     */
    id: string;
}

export interface WasteControllerGetAnalyticsRequest {
    /**
     * Inclusive lower bound on confirmedAt
     */
    from?: string;
    /**
     * Inclusive upper bound on confirmedAt
     */
    to?: string;
    /**
     * 
     */
    locationId?: string;
}

export interface WasteControllerUpdateRequest {
    /**
     * Waste record ID
     */
    id: string;
    /**
     * 
     */
    updateWasteDto: UpdateWasteDto;
}

/**
 * 
 */
export class WasteApi extends runtime.BaseAPI {

    /**
     * Creates request options for wasteControllerCancel without sending the request
     */
    async wasteControllerCancelRequestOpts(requestParameters: WasteControllerCancelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling wasteControllerCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Allowed from any status except CONFIRMED — a confirmed record already affected real stock and cannot be cancelled.
     * Cancel a waste record
     */
    async wasteControllerCancelRaw(requestParameters: WasteControllerCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteResponseDto>> {
        const requestOptions = await this.wasteControllerCancelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteResponseDtoFromJSON(jsonValue));
    }

    /**
     * Allowed from any status except CONFIRMED — a confirmed record already affected real stock and cannot be cancelled.
     * Cancel a waste record
     */
    async wasteControllerCancel(requestParameters: WasteControllerCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteResponseDto> {
        const response = await this.wasteControllerCancelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerCapture without sending the request
     */
    async wasteControllerCaptureRequestOpts(requestParameters: WasteControllerCaptureRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['captureWasteDto'] == null) {
            throw new runtime.RequiredError(
                'captureWasteDto',
                'Required parameter "captureWasteDto" was null or undefined when calling wasteControllerCapture().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste/capture`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CaptureWasteDtoToJSON(requestParameters['captureWasteDto']),
        };
    }

    /**
     * Does a basic name match of rawText against the tenant\'s items — no heavy matching, no speech recognition/OCR here (that already happened upstream, see CaptureWasteDto). Forced into REVIEW if confidence < 80, no item could be matched, or quantity is unknown.
     * Report a waste record from an already-transcribed voice note or photo
     */
    async wasteControllerCaptureRaw(requestParameters: WasteControllerCaptureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteResponseDto>> {
        const requestOptions = await this.wasteControllerCaptureRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteResponseDtoFromJSON(jsonValue));
    }

    /**
     * Does a basic name match of rawText against the tenant\'s items — no heavy matching, no speech recognition/OCR here (that already happened upstream, see CaptureWasteDto). Forced into REVIEW if confidence < 80, no item could be matched, or quantity is unknown.
     * Report a waste record from an already-transcribed voice note or photo
     */
    async wasteControllerCapture(requestParameters: WasteControllerCaptureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteResponseDto> {
        const response = await this.wasteControllerCaptureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerConfirm without sending the request
     */
    async wasteControllerConfirmRequestOpts(requestParameters: WasteControllerConfirmRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling wasteControllerConfirm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste/{id}/confirm`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Only allowed from DRAFT or REVIEW. Freezes costSnapshot = quantity * (current FIFO unit cost) and consumes that stock atomically: if stock is insufficient, nothing changes and the record stays exactly as it was — a deliberate deviation from the legacy, which allowed stock to go negative on confirm (see CLAUDE.md).
     * Confirm a waste record, consuming stock
     */
    async wasteControllerConfirmRaw(requestParameters: WasteControllerConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteResponseDto>> {
        const requestOptions = await this.wasteControllerConfirmRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteResponseDtoFromJSON(jsonValue));
    }

    /**
     * Only allowed from DRAFT or REVIEW. Freezes costSnapshot = quantity * (current FIFO unit cost) and consumes that stock atomically: if stock is insufficient, nothing changes and the record stays exactly as it was — a deliberate deviation from the legacy, which allowed stock to go negative on confirm (see CLAUDE.md).
     * Confirm a waste record, consuming stock
     */
    async wasteControllerConfirm(requestParameters: WasteControllerConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteResponseDto> {
        const response = await this.wasteControllerConfirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerCreate without sending the request
     */
    async wasteControllerCreateRequestOpts(requestParameters: WasteControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWasteDto'] == null) {
            throw new runtime.RequiredError(
                'createWasteDto',
                'Required parameter "createWasteDto" was null or undefined when calling wasteControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWasteDtoToJSON(requestParameters['createWasteDto']),
        };
    }

    /**
     * Always lands in DRAFT — itemId, locationId, quantity, and reason are all required, and confidence is always 100 for a manual entry.
     * Report a waste record manually
     */
    async wasteControllerCreateRaw(requestParameters: WasteControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteResponseDto>> {
        const requestOptions = await this.wasteControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteResponseDtoFromJSON(jsonValue));
    }

    /**
     * Always lands in DRAFT — itemId, locationId, quantity, and reason are all required, and confidence is always 100 for a manual entry.
     * Report a waste record manually
     */
    async wasteControllerCreate(requestParameters: WasteControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteResponseDto> {
        const response = await this.wasteControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerFindAll without sending the request
     */
    async wasteControllerFindAllRequestOpts(requestParameters: WasteControllerFindAllRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        if (requestParameters['itemId'] != null) {
            queryParameters['itemId'] = requestParameters['itemId'];
        }

        if (requestParameters['reason'] != null) {
            queryParameters['reason'] = requestParameters['reason'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Optionally filtered by status, locationId, itemId, and/or reason. Newest first.
     * List the current tenant\'s waste records
     */
    async wasteControllerFindAllRaw(requestParameters: WasteControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WasteResponseDto>>> {
        const requestOptions = await this.wasteControllerFindAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WasteResponseDtoFromJSON));
    }

    /**
     * Optionally filtered by status, locationId, itemId, and/or reason. Newest first.
     * List the current tenant\'s waste records
     */
    async wasteControllerFindAll(requestParameters: WasteControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WasteResponseDto>> {
        const response = await this.wasteControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerFindOne without sending the request
     */
    async wasteControllerFindOneRequestOpts(requestParameters: WasteControllerFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling wasteControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a waste record by ID
     */
    async wasteControllerFindOneRaw(requestParameters: WasteControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteResponseDto>> {
        const requestOptions = await this.wasteControllerFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a waste record by ID
     */
    async wasteControllerFindOne(requestParameters: WasteControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteResponseDto> {
        const response = await this.wasteControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerGetAnalytics without sending the request
     */
    async wasteControllerGetAnalyticsRequestOpts(requestParameters: WasteControllerGetAnalyticsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['locationId'] != null) {
            queryParameters['locationId'] = requestParameters['locationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste/analytics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Total money lost, and a breakdown by item / reason / responsible user (each sorted by cost descending — the first entries are already \"top by loss\"), over an optional confirmedAt date range and location.
     * Waste control analytics (CONFIRMED records only)
     */
    async wasteControllerGetAnalyticsRaw(requestParameters: WasteControllerGetAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteAnalyticsResponseDto>> {
        const requestOptions = await this.wasteControllerGetAnalyticsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteAnalyticsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Total money lost, and a breakdown by item / reason / responsible user (each sorted by cost descending — the first entries are already \"top by loss\"), over an optional confirmedAt date range and location.
     * Waste control analytics (CONFIRMED records only)
     */
    async wasteControllerGetAnalytics(requestParameters: WasteControllerGetAnalyticsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteAnalyticsResponseDto> {
        const response = await this.wasteControllerGetAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wasteControllerUpdate without sending the request
     */
    async wasteControllerUpdateRequestOpts(requestParameters: WasteControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling wasteControllerUpdate().'
            );
        }

        if (requestParameters['updateWasteDto'] == null) {
            throw new runtime.RequiredError(
                'updateWasteDto',
                'Required parameter "updateWasteDto" was null or undefined when calling wasteControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/waste/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWasteDtoToJSON(requestParameters['updateWasteDto']),
        };
    }

    /**
     * Lets a human fill in what a voice/photo capture couldn\'t resolve (itemId/quantity/reason) or correct a manual entry, before confirming. Not allowed once CONFIRMED or CANCELLED.
     * Complete or correct a DRAFT/REVIEW waste record
     */
    async wasteControllerUpdateRaw(requestParameters: WasteControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WasteResponseDto>> {
        const requestOptions = await this.wasteControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WasteResponseDtoFromJSON(jsonValue));
    }

    /**
     * Lets a human fill in what a voice/photo capture couldn\'t resolve (itemId/quantity/reason) or correct a manual entry, before confirming. Not allowed once CONFIRMED or CANCELLED.
     * Complete or correct a DRAFT/REVIEW waste record
     */
    async wasteControllerUpdate(requestParameters: WasteControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WasteResponseDto> {
        const response = await this.wasteControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const WasteControllerFindAllStatusEnum = {
    Draft: 'DRAFT',
    Review: 'REVIEW',
    Confirmed: 'CONFIRMED',
    Cancelled: 'CANCELLED',
} as const;
export type WasteControllerFindAllStatusEnum = typeof WasteControllerFindAllStatusEnum[keyof typeof WasteControllerFindAllStatusEnum];
/**
 * @export
 */
export const WasteControllerFindAllReasonEnum = {
    MalEstado: 'Mal estado',
    Caducado: 'Caducado',
    Rotura: 'Rotura',
    ErrorDeProduccin: 'Error de producción',
    Quemado: 'Quemado',
    SobranteNoReutilizable: 'Sobrante no reutilizable',
    ContaminacinCruzada: 'Contaminación cruzada',
    DevolucinInterna: 'Devolución interna',
    PruebaTest: 'Prueba / test',
    Otro: 'Otro',
} as const;
export type WasteControllerFindAllReasonEnum = typeof WasteControllerFindAllReasonEnum[keyof typeof WasteControllerFindAllReasonEnum];
